"""Specialize Frobenius swap networks to compile-time masks."""
from codegen.gensigma import permutation, route


def generate(inline):
    lines = ['// Generated by gen_fixed_sigma.py; inside eccPacked131.', '#pragma once']
    for power in (4, 8, 16, 32, 65):
        perm = permutation(power)
        net = route(perm)
        for bit in range(256):
            x = 1 << bit
            for shift, mask in net:
                t = ((x >> shift) ^ x) & mask
                x ^= t ^ (t << shift)
            assert x == 1 << perm[bit]
        qualifier = 'ECC_HD' if inline else 'ECC_BIG'
        lines += [f'static {qualifier} P131 goal22Sigma{power}(P131 a) {{',
                  'uint32_t v0=a.v[0],v1=a.v[1],v2=a.v[2],v3=a.v[3],v4=a.v[4];',
                  'uint32_t v5=0,v6=0,v7=0,t;']
        for shift, mask in net:
            for word in range(8):
                m = (mask >> (32*word)) & 0xffffffff
                if not m:
                    continue
                if shift < 32:
                    lines += [f't=((v{word} >> {shift})^v{word}) & 0x{m:08x}u;',
                              f'v{word} ^= t ^ (t << {shift});']
                else:
                    other = word + shift//32
                    assert other < 8
                    lines += [f't=(v{word}^v{other}) & 0x{m:08x}u;', f'v{word}^=t; v{other}^=t;']
        lines += ['return P131{{v0,v1,v2,v3,v4&7u}};', '}']
    return '\n'.join(lines) + '\n'


def patch(source):
    old = 'ECC_HD P131 sigma131(P131 a,int k){'
    assert source.count(old) == 1
    switches = ''.join(f' if(k=={k}) return goal22Sigma{k}(a);\n' for k in (4,8,16,32,65))
    return source.replace(old, '#include "fixed_sigma.h"\n' + old + '\n' + switches)


PROBE_HEADER = '''#pragma once
namespace eccPacked131 {
template<int I> ECC_HD P131 goal22Frobenius(P131 a) {
    const int powers[6]={2,4,8,16,32,65};
    return toPolynomial131(sigma131(fromPolynomial131(a),powers[I]));
}
ECC_HD P131 goal22FrobeniusInverse(P131 a) {
    return toPolynomial131(inv131(fromPolynomial131(a)));
}
}
'''
