"""Generate exact polynomial-basis Frobenius lookup maps for inversion.

The modulus is independently evaluated by bit-polynomial long division.
Output tables live in device global memory, not the serialized constant cache.
"""
from pathlib import Path
import argparse

MODULUS = sum(w << (32*i) for i, w in enumerate((0xD, 0, 0xD, 0x1D0D000D, 0xD)))
POWERS = (2, 4, 8, 16, 32, 65)


def square(a):
    out = sum(((a >> i) & 1) << (2*i) for i in range(131))
    while out.bit_length() > 131:
        out ^= MODULUS << (out.bit_length() - 132)
    return out


def generate(bits):
    assert bits in (4, 8)
    size = 1 << bits
    chunks = (131 + bits - 1) // bits
    values = []
    for power in POWERS:
        basis = []
        for i in range(131):
            a = 1 << i
            for _ in range(power):
                a = square(a)
            basis.append(a)
        for chunk in range(chunks):
            row = [0] * size
            for v in range(1, size):
                bit = (v & -v).bit_length() - 1
                pos = chunk * bits + bit
                row[v] = row[v ^ (1 << bit)] ^ (basis[pos] if pos < 131 else 0)
            values.extend(row)
    head = '''// Generated by gen_frobenius_inverse.py; do not edit tables.
#pragma once
namespace eccPacked131 {
#ifdef __CUDACC__
#define GOAL22_TABLE __device__ static const
#define GOAL22_MAP __device__ __noinline__
#define GOAL22_INV __device__ __forceinline__
using Goal22Low = uint4;
#else
#define GOAL22_TABLE static const
#define GOAL22_MAP inline
#define GOAL22_INV inline
struct alignas(16) Goal22Low { uint32_t x,y,z,w; };
#endif
'''
    low = ',\n'.join('{' + ','.join(f'0x{(a >> (32*w)) & 0xffffffff:08x}u' for w in range(4)) + '}' for a in values)
    top = ','.join(str(a >> 128) for a in values)
    head += f'GOAL22_TABLE Goal22Low goal22FrobLow[{len(values)}] = {{\n{low}\n}};\n'
    head += f'GOAL22_TABLE unsigned char goal22FrobTop[{len(values)}] = {{{top}}};\n'
    head += f'''
template<int POWER_INDEX> GOAL22_MAP P131 goal22Frobenius(P131 a) {{
    P131 r = {{}};
#pragma unroll
    for (int i=0; i<{chunks}; ++i) {{
        const unsigned digit = (a.v[i / {32//bits}] >> ((i % {32//bits}) * {bits})) & {size-1}u;
        const unsigned index = (POWER_INDEX * {chunks} + i) * {size} + digit;
#ifdef __CUDA_ARCH__
        const Goal22Low v = __ldg(goal22FrobLow + index);
        const unsigned top = __ldg(goal22FrobTop + index);
#else
        const Goal22Low v = goal22FrobLow[index];
        const unsigned top = goal22FrobTop[index];
#endif
        r.v[0] ^= v.x; r.v[1] ^= v.y; r.v[2] ^= v.z; r.v[3] ^= v.w; r.v[4] ^= top;
    }}
    return r;
}}
GOAL22_INV P131 goal22FrobeniusInverse(P131 a) {{
    // beta_2,4,8,16,32,64,65,130; the final square yields a^(2^131-2).
    // All intermediates stay reduced in the polynomial basis, including zero.
    P131 acc = mulPolynomial131(squarePolynomial131(a), a);
    acc = mulPolynomial131(goal22Frobenius<0>(acc), acc);
    acc = mulPolynomial131(goal22Frobenius<1>(acc), acc);
    acc = mulPolynomial131(goal22Frobenius<2>(acc), acc);
    acc = mulPolynomial131(goal22Frobenius<3>(acc), acc);
    acc = mulPolynomial131(goal22Frobenius<4>(acc), acc);
    acc = mulPolynomial131(squarePolynomial131(acc), a);
    acc = mulPolynomial131(goal22Frobenius<5>(acc), acc);
    return squarePolynomial131(acc);
}}
#undef GOAL22_TABLE
#undef GOAL22_MAP
#undef GOAL22_INV
}} // namespace eccPacked131
'''
    return head


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--bits', type=int, choices=(4, 8), default=4)
    parser.add_argument('--out', type=Path, required=True)
    args = parser.parse_args()
    args.out.write_text(generate(args.bits))
