"""Exact cyclic predecessor search for the table-walk pivot."""
def generate(group):
    assert group in (1, 4)
    linv = [min(pow(2,k,263), 263-pow(2,k,263))-1 for k in range(131)]
    assert sorted(linv) == list(range(131))
    words = [sum(linv[(k-j)%131] << (8*j) for j in range(4)) for k in range(131)]
    source = '// Generated by gen_pivot_search.py; included inside eccPacked131.\n#pragma once\n'
    if group == 4:
        source += '#ifdef __CUDACC__\nstatic __device__ const\n#else\nstatic const\n#endif\n'
        source += 'uint32_t goal22PivotGroups[131] = {' + ','.join(hex(w)+'u' for w in words) + '};\n'
    source += '''
TW_FN unsigned goal22CoordinateSet(const P131 &x, unsigned position) {
    const unsigned word = position >> 5;
    const uint32_t value = word == 0 ? x.v[0] : word == 1 ? x.v[1]
        : word == 2 ? x.v[2] : word == 3 ? x.v[3] : x.v[4];
    return (value >> (position & 31)) & 1u;
}
TW_FN int goal22PivotSearch(const P131 &x, int k, const uint8_t *linv) {
    int rank = k ? k-1 : 130;
'''
    if group == 1:
        source += '''
#pragma unroll 1
    for (int checked=0; checked<131; ++checked) {
        const unsigned p = linv[rank];
        if (goal22CoordinateSet(x,p)) return int(p);
        rank = rank ? rank-1 : 130;
    }
'''
    else:
        source += '''
#pragma unroll 1
    for (int checked=0; checked<131; checked+=4) {
#ifdef __CUDA_ARCH__
        const uint32_t group = __ldg(goal22PivotGroups + rank);
#else
        const uint32_t group = goal22PivotGroups[rank];
#endif
        const unsigned p0=group&255u, p1=(group>>8)&255u, p2=(group>>16)&255u, p3=group>>24;
        const unsigned b0=goal22CoordinateSet(x,p0), b1=goal22CoordinateSet(x,p1);
        const unsigned b2=goal22CoordinateSet(x,p2), b3=goal22CoordinateSet(x,p3);
        if(b0|b1|b2|b3) return int(b0?p0:b1?p1:b2?p2:p3);
        rank-=4;
        if(rank<0)rank+=131;
    }
'''
    return source + '''
    // Valid subgroup points have nonzero x. Keep malformed input bounded.
    return 0;
}
'''


def patch(source):
    start = source.index('TW_FN int twPivot(')
    end = source.index('// Coordinate p of', start)
    signature = source[start:source.index('{',start)]
    return source[:start] + '#include "pivot_search.cuh"\n' + signature + '''{
    (void)maskLt; (void)maxL;
    return goal22PivotSearch(x, k, linv);
}

''' + source[end:]
