"""Reduce a polynomial square in its packed even/odd coefficient streams.

For H=a^2 as an unreduced polynomial and B=a>>66, H>>131 = spread(B)<<1.
Conjugate the existing quotient/remainder circuit by this interleaving:
  E = B ^ B>>4 ^ B>>12 ^ B>>28 ^ B>>60
  O = B ^ E>>1 ^ E>>2
The quotient Q is spread(E) ^ (spread(O)<<1). All reduction work can then
stay in the two 65/66-bit streams until the final zip. Long division is the
independent oracle; no alternate walk or field polynomial is introduced.
"""
import argparse
from pathlib import Path
import random

MODULUS = 0xD1D0D000D0000000D000000000000000D


def spread(a):
    return sum(((a >> i) & 1) << (2*i) for i in range(a.bit_length()))


def reference(a):
    h = spread(a)
    while h.bit_length() > 131:
        h ^= MODULUS << (h.bit_length() - 132)
    return h


def packed(a):
    b = a >> 66
    e = b ^ (b >> 4) ^ (b >> 12) ^ (b >> 28) ^ (b >> 60)
    o = b ^ (e >> 1) ^ (e >> 2)
    te = e ^ (e << 1) ^ (o << 2)
    to = o ^ (o << 1) ^ (e << 1)
    ev = a ^ te ^ (e << 62)
    od = to ^ (o << 62)
    for s in (32, 48, 56, 60, 64):
        ev ^= te << s
        od ^= to << s
    return spread(ev & ((1 << 66) - 1)) ^ (spread(od & ((1 << 65) - 1)) << 1)


def check():
    rng = random.Random(220131)
    cases = [0, (1 << 131)-1] + [1 << i for i in range(131)]
    cases += [rng.getrandbits(131) for _ in range(10000)]
    for a in cases:
        assert packed(a) == reference(a), hex(a)
    return len(cases)


def shifted(prefix, shift, word, width):
    """32-bit word of a width-bit vector shifted left by shift (right if <0)."""
    parts = []
    for j in range((width + 31)//32):
        delta = 32*j + shift - 32*word
        n = min(32, width - 32*j)
        if delta >= 32 or delta + n <= 0:
            continue
        v = f'{prefix}{j}'
        parts.append(v if delta == 0 else f'({v} {"<<" if delta > 0 else ">>"} {abs(delta)})')
    return '(' + ' | '.join(parts) + ')' if parts else None


def generate():
    count = check()
    lines = ['// Generated by research/gen_square_reduce.py; inside eccPacked131.',
             f'// Checked against polynomial long division on {count} inputs.',
             '#pragma once', '#include "zip_square.h"',
             'ECC_HD P131 goal22SquareReduced(P131 a) {']
    for i in range(3):
        expr = f'(a.v[{i+2}] >> 2)'
        if i < 2:
            expr += f' | (a.v[{i+3}] << 30)'
        lines.append(f'    const uint32_t b{i} = {expr};')
    stages = [
        ('e', 65, [('b', 65, s) for s in (0, -4, -12, -28, -60)]),
        ('o', 65, [('b', 65, 0), ('e', 65, -1), ('e', 65, -2)]),
        ('te', 66, [('e', 65, 0), ('e', 65, 1), ('o', 65, 2)]),
        ('to', 65, [('o', 65, 0), ('o', 65, 1), ('e', 65, 1)]),
        ('ev', 66, [('te', 66, s) for s in (0, 32, 48, 56, 60, 64)] + [('e', 65, 62)]),
        ('od', 65, [('to', 65, s) for s in (0, 32, 48, 56, 60, 64)] + [('o', 65, 62)]),
    ]
    for prefix, width, terms in stages:
        for i in range(3):
            parts = [shifted(p, s, i, w) for p, w, s in terms]
            if prefix == 'ev':
                parts.insert(0, f'a.v[{i}]')
            expr = ' ^ '.join(p for p in parts if p)
            if i == 2:
                expr = '(' + expr + f') & {(1 << (width-64))-1}u'
            lines.append(f'    const uint32_t {prefix}{i} = {expr};')
    lines += ['    P131 out;',
              '    goal22Zip2(ev0, od0, &out.v[0], &out.v[1]);',
              '    goal22Zip2(ev1, od1, &out.v[2], &out.v[3]);',
              '    out.v[4] = (ev2 & 1u) | ((od2 & 1u) << 1) | ((ev2 & 2u) << 1);',
              '    return out;', '}']
    return '\n'.join(lines) + '\n'


def patch(source):
    start = source.index('ECC_HD P131 squarePolynomial131(P131 a) {')
    end = source.index('ECC_HD P131 sqr131(', start)
    return source[:start] + '#include "square_reduce.h"\n' + \
        'ECC_HD P131 squarePolynomial131(P131 a) { return goal22SquareReduced(a); }\n' + source[end:]


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out', type=Path, required=True)
    args = parser.parse_args()
    args.out.write_text(generate())
    print('PASS square reduction: 131 basis vectors, 2 edges and 10000 random values')
