//! Build script for `cryptanalysis-cuda`.
//!
//! Its only job is the *optional* build-time PTX: if a CUDA compiler can be
//! found it compiles the repository's `cuda/rho_kernel.cu` to PTX into
//! `$OUT_DIR` and tells the crate to embed it with `include_str!`.  When no
//! compiler works the build still succeeds (a `cargo:warning` is emitted) and
//! the crate falls back to compiling `src/kernel_nvrtc.cu` with NVRTC at run
//! time.  Nothing here ever links against libcuda.
//!
//! Environment:
//!   * `CA_CUDA_ARCH`  - GPU architecture, default `sm_70`.
//!   * `CUDA_PATH` / `CUDA_HOME` - CUDA toolkit root (used for `nvcc` lookup
//!     and for clang's `--cuda-path`).
//!   * `CA_CUDA_NO_PTX` - set to skip the build-time PTX entirely.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    // bindings/rust/cryptanalysis-cuda -> bindings/rust -> bindings -> <repo>
    let repo = manifest
        .ancestors()
        .nth(3)
        .expect("crate must live in <repo>/bindings/rust/<crate>")
        .to_path_buf();
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/kernel_nvrtc.cu");
    println!("cargo:rerun-if-changed={}", repo.join("cuda").display());
    println!(
        "cargo:rerun-if-changed={}",
        repo.join("cuda/ca_device.cuh").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        repo.join("cuda/rho_kernel.cu").display()
    );
    for var in [
        "CA_CUDA_ARCH",
        "CA_CUDA_NO_PTX",
        "CUDA_PATH",
        "CUDA_HOME",
        "NVCC",
    ] {
        println!("cargo:rerun-if-env-changed={var}");
    }
    println!("cargo::rustc-check-cfg=cfg(ca_embedded_ptx)");

    write_kernel_consts(&repo, &out_dir);

    if env::var_os("CA_CUDA_NO_PTX").is_some() {
        println!(
            "cargo:warning=CA_CUDA_NO_PTX is set: no PTX embedded, the NVRTC fallback will be used"
        );
        return;
    }

    let arch = env::var("CA_CUDA_ARCH").unwrap_or_else(|_| "sm_70".to_string());
    let kernel = repo.join("cuda/rho_kernel.cu");
    if !kernel.is_file() {
        println!(
            "cargo:warning={} not found: no PTX embedded",
            kernel.display()
        );
        return;
    }
    let ptx = out_dir.join("rho_kernel.ptx");

    let mut tried = Vec::new();
    for candidate in candidates() {
        let _ = fs::remove_file(&ptx);
        match candidate.compile(&repo, &kernel, &ptx, &arch) {
            Ok(()) => {
                println!("cargo:rustc-env=CA_CUDA_PTX={}", ptx.display());
                println!("cargo:rustc-cfg=ca_embedded_ptx");
                return;
            }
            Err(why) => tried.push(format!("{}: {why}", candidate.describe())),
        }
    }
    let _ = fs::remove_file(&ptx);
    println!(
        "cargo:warning=no working CUDA compiler for {arch} PTX ({}); \
         cryptanalysis-cuda will compile the kernel with NVRTC at run time",
        tried.join("; ")
    );
}

/// Mirror `CA_GPU_W` / `CA_GPU_AUX` from `cuda/ca_device.cuh` into Rust
/// constants so that the two can never drift apart silently.
fn write_kernel_consts(repo: &Path, out_dir: &Path) {
    let header = fs::read_to_string(repo.join("cuda/ca_device.cuh")).unwrap_or_default();
    let walks = define_value(&header, "CA_GPU_W").unwrap_or(8);
    let aux = define_value(&header, "CA_GPU_AUX").unwrap_or(8);
    let src = format!(
        "// Generated by build.rs from cuda/ca_device.cuh -- do not edit.\n\
         /// Walks per thread (`CA_GPU_W`).\n\
         pub const WALKS_PER_THREAD: u32 = {walks};\n\
         /// Auxiliary `u64` words per walk (`CA_GPU_AUX`).\n\
         pub const AUX_WORDS: usize = {aux};\n"
    );
    fs::write(out_dir.join("kernel_consts.rs"), src).expect("write kernel_consts.rs");
}

/// Value of a `#define NAME <integer>` in `text` (tolerating `#  define`).
fn define_value(text: &str, name: &str) -> Option<u64> {
    text.lines()
        .map(str::trim)
        .filter(|l| l.starts_with('#'))
        .filter_map(|l| {
            l.trim_start_matches('#')
                .trim()
                .strip_prefix("define")?
                .trim()
                .strip_prefix(name)
        })
        .find_map(|rest| {
            // Require a token boundary so that CA_GPU_W does not match CA_GPU_WINDOW.
            if !rest.starts_with(char::is_whitespace) {
                return None;
            }
            rest.split_whitespace().next()?.parse().ok()
        })
}

/// A CUDA compiler we know how to drive to produce PTX.
enum Candidate {
    Nvcc(PathBuf),
    Clang(String, Option<PathBuf>),
}

impl Candidate {
    fn describe(&self) -> String {
        match self {
            Candidate::Nvcc(p) => format!("nvcc ({})", p.display()),
            Candidate::Clang(c, None) => format!("{c} -x cuda"),
            Candidate::Clang(c, Some(p)) => format!("{c} -x cuda --cuda-path={}", p.display()),
        }
    }

    fn compile(&self, repo: &Path, kernel: &Path, ptx: &Path, arch: &str) -> Result<(), String> {
        let mut cmd = match self {
            Candidate::Nvcc(exe) => {
                let mut c = Command::new(exe);
                c.arg("--ptx").arg(format!("-arch={arch}")).arg("-O3");
                c
            }
            Candidate::Clang(exe, cuda_path) => {
                let mut c = Command::new(exe);
                c.arg("-x").arg("cuda").arg("--cuda-device-only");
                if let Some(p) = cuda_path {
                    c.arg(format!("--cuda-path={}", p.display()));
                }
                c.arg(format!("--cuda-gpu-arch={arch}"))
                    .arg("-O3")
                    .arg("-Wno-unknown-cuda-version")
                    .arg("-S");
                c
            }
        };
        cmd.arg("-I")
            .arg(repo.join("include"))
            .arg("-I")
            .arg(repo.join("cuda"))
            .arg("-I")
            .arg(repo.join("src"))
            .arg("-o")
            .arg(ptx)
            .arg(kernel);

        let out = cmd.output().map_err(|e| e.to_string())?;
        if !out.status.success() {
            let msg = String::from_utf8_lossy(&out.stderr);
            return Err(format!(
                "exited with {:?}: {}",
                out.status.code(),
                msg.lines().next_back().unwrap_or("no diagnostics").trim()
            ));
        }
        // A toolkit shim can exit 0 without producing anything useful, so
        // check that this really is PTX for the requested architecture.
        let text = fs::read_to_string(ptx).map_err(|e| format!("reading output: {e}"))?;
        if !text.contains(".target ") || !text.contains("ca_rho_walk_kernel") {
            return Err("output is not PTX containing ca_rho_walk_kernel".into());
        }
        Ok(())
    }
}

/// `nvcc` first (it is the vendor compiler), then `clang -x cuda`.  Each
/// candidate is validated by actually compiling, so a stub `nvcc` that only
/// answers `--version` does not shadow a working clang.
fn candidates() -> Vec<Candidate> {
    let mut out = Vec::new();
    let mut roots: Vec<PathBuf> = Vec::new();
    for var in [
        "CUDA_PATH",
        "CUDA_HOME",
        "CUDA_ROOT",
        "CUDA_TOOLKIT_ROOT_DIR",
    ] {
        if let Some(v) = env::var_os(var) {
            let p = PathBuf::from(v);
            if !roots.contains(&p) {
                roots.push(p);
            }
        }
    }

    if let Some(nvcc) = env::var_os("NVCC") {
        out.push(Candidate::Nvcc(PathBuf::from(nvcc)));
    }
    for root in &roots {
        let exe = root.join("bin").join(exe_name("nvcc"));
        if exe.is_file() {
            out.push(Candidate::Nvcc(exe));
        }
    }
    out.push(Candidate::Nvcc(PathBuf::from("nvcc")));

    let clang = env::var("CA_CUDA_CLANG").unwrap_or_else(|_| "clang".to_string());
    for root in &roots {
        out.push(Candidate::Clang(clang.clone(), Some(root.clone())));
    }
    out.push(Candidate::Clang(clang, None));
    out
}

fn exe_name(stem: &str) -> String {
    if cfg!(windows) {
        format!("{stem}.exe")
    } else {
        stem.to_string()
    }
}
