//! Elliptic-curve challenge corpus.
//!
//! The instances live in `challenges/elliptic/corpus.json`, generated by
//! `challenges/elliptic/generate.py`.  They are known-answer discrete-log
//! problems (and, at the top of the range, order-known parameter sets)
//! spread across prime fields, binary and ternary fields, odd-characteristic
//! extensions, Koblitz and proper subfield curves, j-invariants 0 and 1728,
//! generic j, supersingular and anomalous curves, twist pairs, and
//! multi-level isogeny volcanoes.  Field cardinalities run from a few bits
//! up to 768.
//!
//! Tiers:
//!
//! * `open` — small group, scalar published.  Solve these.
//! * `bench` — scalar published, group large enough that a solve is a
//!   measurement rather than a unit test.
//! * `shape` — cryptographic-size field.  The scalar is either published
//!   as a short witness, or withheld and committed as
//!   `sha256(utf8(id + "\n" + decimal_scalar))`.
//!
//! Prime-field instances materialise as [`CurveParams`] for the suite's
//! Pollard rho and index-calculus drivers.  Binary instances carry the
//! sparse irreducible the generator used, so they drop onto
//! [`crate::binary_ecc::BinaryCurve`].

use crate::cryptanalysis::modular_polynomial::{phi_2, phi_3, ModularPolynomial};
use crate::ecc::curve::CurveParams;
use crate::ecc::field::FieldElement;
use crate::ecc::point::Point;
use num_bigint::{BigInt, BigUint, Sign};
use num_traits::Zero;
use serde::Deserialize;
use std::sync::OnceLock;

const CORPUS_JSON: &str = include_str!("../../../challenges/elliptic/corpus.json");

/// The whole corpus, parsed once.
#[derive(Debug, Clone, Deserialize)]
pub struct CorpusFile {
    pub version: u32,
    pub seed: u64,
    pub scalar_commitment: String,
    pub summary: Summary,
    pub instances: Vec<Instance>,
    pub volcanoes: Vec<Volcano>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Summary {
    pub instances: usize,
    pub volcanoes: usize,
    pub cardinality_bits_min: u32,
    pub cardinality_bits_max: u32,
    pub families: std::collections::BTreeMap<String, usize>,
    pub tiers: std::collections::BTreeMap<String, usize>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Instance {
    pub id: String,
    pub family: String,
    pub tier: String,
    pub tags: Vec<String>,
    pub field: FieldDesc,
    pub model: String,
    pub a: Vec<String>,
    pub b: Vec<String>,
    #[serde(default)]
    pub j: Option<String>,
    #[serde(default)]
    pub trace: Option<String>,
    #[serde(default)]
    pub trace_base_field: Option<String>,
    pub group_order: String,
    pub subgroup_order: String,
    pub cofactor: String,
    #[serde(default)]
    pub factored_completely: bool,
    #[serde(default)]
    pub largest_prime_factor: Option<String>,
    #[serde(default)]
    pub embedding_degree: Option<u32>,
    pub endomorphisms: Vec<String>,
    pub solvers: Vec<String>,
    #[serde(default)]
    pub relation: Option<Relation>,
    #[serde(default)]
    pub witness: Option<Witness>,
    pub note: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct FieldDesc {
    pub kind: String,
    pub characteristic: String,
    pub degree: u32,
    pub degree_kind: String,
    pub cardinality: String,
    pub cardinality_bits: u32,
    #[serde(default)]
    pub irreducible_low_terms: Vec<u32>,
    #[serde(default)]
    pub polynomial: Option<String>,
    #[serde(default)]
    pub irreducible: Vec<String>,
    #[serde(default)]
    pub subfield_degree: Option<u32>,
    #[serde(default)]
    pub extension_over_subfield: Option<u32>,
    #[serde(default)]
    pub subfield_degree_kind: Option<String>,
    #[serde(default)]
    pub extension_degree_kind: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Affine {
    pub x: Vec<String>,
    pub y: Vec<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Relation {
    #[serde(default)]
    pub base: Option<Affine>,
    #[serde(default)]
    pub target: Option<Affine>,
    #[serde(default)]
    pub scalar: Option<String>,
    #[serde(default)]
    pub scalar_sha256: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Witness {
    pub scalar: String,
    #[serde(default)]
    pub point: Option<Affine>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Volcano {
    pub id: String,
    pub ell: u32,
    pub height: u32,
    pub prime: String,
    pub trace: String,
    pub frobenius_discriminant: String,
    pub fundamental_discriminant: String,
    pub conductor: String,
    pub crater_size: u32,
    pub node_count: u32,
    pub levels: Vec<Level>,
    pub edges: Vec<Edge>,
    pub note: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Level {
    pub depth: u32,
    pub role: String,
    pub j: Vec<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Edge {
    pub j1: String,
    pub j2: String,
}

/// Parsed corpus.  Panics if the shipped JSON does not match this schema:
/// that is a build failure, not a runtime condition.
pub fn corpus() -> &'static CorpusFile {
    static CACHE: OnceLock<CorpusFile> = OnceLock::new();
    CACHE.get_or_init(|| {
        serde_json::from_str(CORPUS_JSON)
            .expect("challenges/elliptic/corpus.json matches CorpusFile")
    })
}

pub fn find<'a>(corpus: &'a CorpusFile, id: &str) -> Option<&'a Instance> {
    corpus.instances.iter().find(|inst| inst.id == id)
}

pub fn select<'a>(
    corpus: &'a CorpusFile,
    family: Option<&str>,
    tier: Option<&str>,
    tag: Option<&str>,
    max_bits: Option<u32>,
) -> Vec<&'a Instance> {
    corpus
        .instances
        .iter()
        .filter(|inst| family.is_none_or(|f| inst.family == f))
        .filter(|inst| tier.is_none_or(|t| inst.tier == t))
        .filter(|inst| tag.is_none_or(|tag| inst.tags.iter().any(|t| t == tag)))
        .filter(|inst| max_bits.is_none_or(|b| inst.field.cardinality_bits <= b))
        .collect()
}

pub fn format_summary(corpus: &CorpusFile) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "elliptic challenge corpus v{} (seed {})\n",
        corpus.version, corpus.seed
    ));
    out.push_str(&format!(
        "{} instances, {} volcanoes, cardinality bits {}..{}\n",
        corpus.summary.instances,
        corpus.summary.volcanoes,
        corpus.summary.cardinality_bits_min,
        corpus.summary.cardinality_bits_max
    ));
    out.push_str(&format!("commitment: {}\n", corpus.scalar_commitment));
    out.push_str("tiers:\n");
    for (tier, n) in &corpus.summary.tiers {
        out.push_str(&format!("  {tier:<8} {n}\n"));
    }
    out.push_str("families:\n");
    for (family, n) in &corpus.summary.families {
        out.push_str(&format!("  {family:<24} {n}\n"));
    }
    out.push_str("volcanoes:\n");
    for v in &corpus.volcanoes {
        out.push_str(&format!(
            "  {}  ell={} height={} nodes={} crater={} p={}\n",
            v.id, v.ell, v.height, v.node_count, v.crater_size, v.prime
        ));
    }
    out
}

pub fn format_list(rows: &[&Instance]) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "{:<28} {:<22} {:<6} {:>5}  solvers\n",
        "id", "family", "tier", "bits"
    ));
    for inst in rows {
        let solvers = inst.solvers.join(",");
        out.push_str(&format!(
            "{:<28} {:<22} {:<6} {:>5}  {}\n",
            inst.id, inst.family, inst.tier, inst.field.cardinality_bits, solvers
        ));
    }
    out.push_str(&format!("{} instances\n", rows.len()));
    out
}

pub fn format_instance(inst: &Instance) -> String {
    let mut out = String::new();
    out.push_str(&format!("id: {}\n", inst.id));
    out.push_str(&format!("family: {}   tier: {}\n", inst.family, inst.tier));
    out.push_str(&format!("tags: {}\n", inst.tags.join(", ")));
    out.push_str(&format!(
        "field: {}  char {}  degree {} ({})  |F| = 2^{} ({})\n",
        inst.field.kind,
        inst.field.characteristic,
        inst.field.degree,
        inst.field.degree_kind,
        inst.field.cardinality_bits,
        inst.field.cardinality
    ));
    if let Some(poly) = &inst.field.polynomial {
        out.push_str(&format!("polynomial: {poly}\n"));
    }
    out.push_str(&format!("model: {}\n", inst.model));
    out.push_str(&format!("a: {}\n", inst.a.join(", ")));
    out.push_str(&format!("b: {}\n", inst.b.join(", ")));
    if let Some(j) = &inst.j {
        out.push_str(&format!("j: {j}\n"));
    }
    out.push_str(&format!(
        "group order: {}\nsubgroup: {}  cofactor: {}\n",
        inst.group_order, inst.subgroup_order, inst.cofactor
    ));
    out.push_str(&format!(
        "endomorphisms: {}\n",
        inst.endomorphisms.join(", ")
    ));
    out.push_str(&format!("solvers: {}\n", inst.solvers.join(", ")));
    if let Some(rel) = &inst.relation {
        out.push_str(&format!(
            "scalar: {}\n",
            rel.scalar.as_deref().unwrap_or("(withheld)")
        ));
        if let Some(h) = &rel.scalar_sha256 {
            out.push_str(&format!("scalar sha256: {h}\n"));
        }
    }
    out.push_str(&format!("note: {}\n", inst.note));
    out
}

/// Short-Weierstrass prime-field view of an instance, for Pollard rho and
/// the prime-field index calculus.  `n` is the subgroup order the relation
/// lives in.
pub fn prime_curve(inst: &Instance) -> Option<CurveParams> {
    if inst.field.kind != "prime" || inst.model != "short-weierstrass" {
        return None;
    }
    let rel = inst.relation.as_ref()?;
    let base = rel.base.as_ref()?;
    let p = parse_uint(&inst.field.characteristic)?;
    let a = parse_uint(inst.a.first()?)?;
    let b = parse_uint(inst.b.first()?)?;
    let gx = parse_uint(base.x.first()?)?;
    let gy = parse_uint(base.y.first()?)?;
    let n = parse_uint(&inst.subgroup_order)?;
    let cofactor = parse_uint(&inst.cofactor)?;
    let h = u32::try_from(cofactor).unwrap_or(0);
    Some(CurveParams {
        name: "ec-challenge",
        p,
        a,
        b,
        gx,
        gy,
        n,
        h,
    })
}

fn parse_uint(s: &str) -> Option<BigUint> {
    BigUint::parse_bytes(s.as_bytes(), 10)
}

fn parse_int(s: &str) -> Option<BigInt> {
    let (sign, digits) = if let Some(rest) = s.strip_prefix('-') {
        (Sign::Minus, rest)
    } else {
        (Sign::Plus, s)
    };
    let mag = parse_uint(digits)?;
    Some(if mag.is_zero() {
        BigInt::zero()
    } else {
        BigInt::from_biguint(sign, mag)
    })
}

fn fe(v: &BigUint, p: &BigUint) -> FieldElement {
    FieldElement::new(v.clone(), p.clone())
}

fn on_short(p: &BigUint, a: &BigUint, b: &BigUint, x: &BigUint, y: &BigUint) -> bool {
    let x = fe(x, p);
    let y = fe(y, p);
    let a = fe(a, p);
    let b = fe(b, p);
    y.mul(&y) == x.mul(&x).mul(&x).add(&a.mul(&x)).add(&b)
}

fn j_short(p: &BigUint, a: &BigUint, b: &BigUint) -> Option<BigUint> {
    let a = fe(a, p);
    let b = fe(b, p);
    let a3 = a.mul(&a).mul(&a);
    let disc = fe(&BigUint::from(4u32), p)
        .mul(&a3)
        .add(&fe(&BigUint::from(27u32), p).mul(&b.mul(&b)));
    if disc.is_zero() {
        return None;
    }
    let num = fe(&BigUint::from(6912u32), p).mul(&a3);
    Some(num.mul(&disc.inv()?).value)
}

/// `#E(F_{q^e}) = q^e + 1 - s_e` with `s_0 = 2`, `s_1 = t`,
/// `s_i = t s_{i-1} - q s_{i-2}`.
pub fn trace_order(trace: &BigInt, q: &BigInt, e: u32) -> BigInt {
    let mut s_prev = BigInt::from(2);
    let mut s_cur = trace.clone();
    for _ in 1..e {
        let next = trace * &s_cur - q * &s_prev;
        s_prev = s_cur;
        s_cur = next;
    }
    let qe = q.pow(e);
    qe + 1 - s_cur
}

fn phi_zero(phi: &ModularPolynomial, x: &BigInt, y: &BigInt, p: &BigInt, deg: u32) -> bool {
    let mut acc = BigInt::zero();
    for i in 0..=deg {
        for j in 0..=deg {
            let c = phi.coeff(i, j);
            if c.is_zero() {
                continue;
            }
            acc += c * x.modpow(&BigInt::from(i), p) * y.modpow(&BigInt::from(j), p);
            acc %= p;
        }
    }
    acc == BigInt::zero()
}

fn sha256(data: &[u8]) -> [u8; 32] {
    // Compact FIPS 180-4.  Used only to check corpus commitments.
    const K: [u32; 64] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4,
        0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe,
        0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f,
        0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
        0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc,
        0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
        0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116,
        0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7,
        0xc67178f2,
    ];
    let mut h: [u32; 8] = [
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab,
        0x5be0cd19,
    ];
    let bit_len = (data.len() as u64).wrapping_mul(8);
    let mut msg = data.to_vec();
    msg.push(0x80);
    while (msg.len() % 64) != 56 {
        msg.push(0);
    }
    msg.extend_from_slice(&bit_len.to_be_bytes());
    for chunk in msg.chunks(64) {
        let mut w = [0u32; 64];
        for i in 0..16 {
            w[i] = u32::from_be_bytes(chunk[4 * i..4 * i + 4].try_into().unwrap());
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16]
                .wrapping_add(s0)
                .wrapping_add(w[i - 7])
                .wrapping_add(s1);
        }
        let mut a = h[0];
        let mut b = h[1];
        let mut c = h[2];
        let mut d = h[3];
        let mut e = h[4];
        let mut f = h[5];
        let mut g = h[6];
        let mut hh = h[7];
        for i in 0..64 {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let ch = (e & f) ^ (!e & g);
            let t1 = hh
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(K[i])
                .wrapping_add(w[i]);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let t2 = s0.wrapping_add(maj);
            hh = g;
            g = f;
            f = e;
            e = d.wrapping_add(t1);
            d = c;
            c = b;
            b = a;
            a = t1.wrapping_add(t2);
        }
        h[0] = h[0].wrapping_add(a);
        h[1] = h[1].wrapping_add(b);
        h[2] = h[2].wrapping_add(c);
        h[3] = h[3].wrapping_add(d);
        h[4] = h[4].wrapping_add(e);
        h[5] = h[5].wrapping_add(f);
        h[6] = h[6].wrapping_add(g);
        h[7] = h[7].wrapping_add(hh);
    }
    let mut out = [0u8; 32];
    for (i, word) in h.iter().enumerate() {
        out[4 * i..4 * i + 4].copy_from_slice(&word.to_be_bytes());
    }
    out
}

fn hex32(bytes: &[u8; 32]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut s = String::with_capacity(64);
    for b in bytes {
        s.push(HEX[(b >> 4) as usize] as char);
        s.push(HEX[(b & 0xf) as usize] as char);
    }
    s
}

/// Check every structural claim this module can recompute without
/// re-running the generator's field arithmetic: orders from recurrences,
/// prime-field group law on the published relations, volcano edges, and
/// the scalar commitment.
pub fn check_instance(inst: &Instance) -> Result<(), String> {
    let order = parse_uint(&inst.group_order).ok_or("group order")?;
    let subgroup = parse_uint(&inst.subgroup_order).ok_or("subgroup")?;
    let cofactor = parse_uint(&inst.cofactor).ok_or("cofactor")?;
    if &cofactor * &subgroup != order {
        return Err(format!("{}: cofactor * subgroup != group order", inst.id));
    }
    let card = parse_uint(&inst.field.cardinality).ok_or("cardinality")?;
    // Python's `bit_length() - 1` is `BigUint::bits() - 1`.
    let py_bits = card.bits().saturating_sub(1);
    if py_bits != u64::from(inst.field.cardinality_bits) {
        return Err(format!(
            "{}: cardinality bits {} != {py_bits}",
            inst.id, inst.field.cardinality_bits
        ));
    }
    if inst.family == "koblitz" {
        let a: u8 = inst.a.first().ok_or("a")?.parse().map_err(|_| "a")?;
        let n = inst.field.degree;
        let t = if a == 0 {
            BigInt::from(-1)
        } else {
            BigInt::from(1)
        };
        let expect = trace_order(&t, &BigInt::from(2), n);
        if expect != BigInt::from(order.clone()) {
            return Err(format!("{}: Koblitz recurrence mismatch", inst.id));
        }
    }
    if inst.family == "binary-subfield" {
        let k = inst.field.subfield_degree.ok_or("subfield degree")?;
        let e = inst.field.extension_over_subfield.ok_or("extension")?;
        let t = parse_int(inst.trace.as_deref().ok_or("trace")?).ok_or("trace")?;
        let q = BigInt::from(1u32) << k;
        let expect = trace_order(&t, &q, e);
        if expect != BigInt::from(order.clone()) {
            return Err(format!("{}: subfield recurrence mismatch", inst.id));
        }
    }
    if inst.family == "ternary-lift" || (inst.family == "odd-subfield" && inst.relation.is_none()) {
        if let (Some(t), Some(1)) = (
            inst.trace.as_deref(),
            Some(inst.field.subfield_degree.unwrap_or(1)),
        ) {
            // trace stored is the base-field trace; q is the characteristic.
            let t = parse_int(t).ok_or("trace")?;
            let q = parse_int(&inst.field.characteristic).ok_or("characteristic")?;
            let e = inst.field.degree;
            let expect = trace_order(&t, &q, e);
            if expect != BigInt::from(order.clone()) {
                return Err(format!("{}: lift recurrence mismatch", inst.id));
            }
        }
    }
    if let Some(rel) = &inst.relation {
        if let Some(scalar) = &rel.scalar {
            let digest = sha256(format!("{}\n{scalar}", inst.id).as_bytes());
            let want = rel.scalar_sha256.as_deref().unwrap_or("");
            if hex32(&digest) != want {
                return Err(format!("{}: scalar commitment mismatch", inst.id));
            }
        }
    }
    if inst.field.kind == "prime" && inst.model == "short-weierstrass" {
        check_prime_field(inst, &order)?;
    }
    Ok(())
}

fn check_prime_field(inst: &Instance, order: &BigUint) -> Result<(), String> {
    let p = parse_uint(&inst.field.characteristic).ok_or("p")?;
    let a = parse_uint(inst.a.first().ok_or("a")?).ok_or("a")?;
    let b = parse_uint(inst.b.first().ok_or("b")?).ok_or("b")?;
    let j = j_short(&p, &a, &b).ok_or_else(|| format!("{}: singular", inst.id))?;
    if let Some(want) = &inst.j {
        let want = parse_uint(want).ok_or("j")?;
        if j != want {
            return Err(format!("{}: j-invariant {} != {want}", inst.id, j));
        }
    }
    let trace = BigInt::from(p.clone()) + 1 - BigInt::from(order.clone());
    let four_p = BigInt::from(p.clone()) * 4;
    if &trace * &trace > four_p {
        return Err(format!("{}: trace outside Hasse", inst.id));
    }
    let a_fe = fe(&a, &p);
    let check_mul = |pt: &Affine, k: &BigUint, expect: Option<&Affine>| -> Result<(), String> {
        let x = parse_uint(pt.x.first().ok_or("x")?).ok_or("x")?;
        let y = parse_uint(pt.y.first().ok_or("y")?).ok_or("y")?;
        if !on_short(&p, &a, &b, &x, &y) {
            return Err(format!("{}: point off the curve", inst.id));
        }
        let point = Point::Affine {
            x: fe(&x, &p),
            y: fe(&y, &p),
        };
        let got = point.scalar_mul(k, &a_fe);
        match expect {
            None => {
                if got != Point::Infinity {
                    return Err(format!("{}: [order]P is not infinity", inst.id));
                }
            }
            Some(q) => {
                let qx = parse_uint(q.x.first().ok_or("qx")?).ok_or("qx")?;
                let qy = parse_uint(q.y.first().ok_or("qy")?).ok_or("qy")?;
                let want = Point::Affine {
                    x: fe(&qx, &p),
                    y: fe(&qy, &p),
                };
                if got != want {
                    return Err(format!("{}: scalar relation failed", inst.id));
                }
            }
        }
        Ok(())
    };
    if let Some(w) = &inst.witness {
        let k = parse_uint(&w.scalar).ok_or("witness scalar")?;
        let pt = w.point.as_ref().ok_or("witness point")?;
        // The witness is [k] of the relation base, when a base is present.
        if let Some(base) = inst.relation.as_ref().and_then(|r| r.base.as_ref()) {
            check_mul(base, &k, Some(pt))?;
        }
    }
    if let Some(rel) = &inst.relation {
        if let (Some(base), Some(scalar)) = (&rel.base, &rel.scalar) {
            let k = parse_uint(scalar).ok_or("scalar")?;
            // A missing target is the point at infinity.  [k]P = O is not a
            // discrete-log challenge, and the published scalar is then only
            // determined modulo the (smaller) order of P.
            let target = match &rel.target {
                Some(target) => target,
                None => {
                    return Err(format!("{}: relation target is the identity", inst.id));
                }
            };
            check_mul(base, &k, Some(target))?;
            // Full order annihilation stays cheap through 160-bit fields and
            // is the check that the published order really kills the base.
            if inst.field.cardinality_bits <= 160 {
                check_mul(base, order, None)?;
            }
        } else if let Some(base) = &rel.base {
            if inst.field.cardinality_bits <= 96 {
                check_mul(base, order, None)?;
            }
        }
    }
    Ok(())
}

pub fn check_volcano(v: &Volcano) -> Result<(), String> {
    if v.height < 2 {
        return Err(format!("{}: height {} < 2", v.id, v.height));
    }
    if v.ell != 2 && v.ell != 3 {
        return Err(format!("{}: unsupported ell", v.id));
    }
    let phi = if v.ell == 2 { phi_2() } else { phi_3() };
    let p = BigInt::from(parse_uint(&v.prime).ok_or("p")?);
    let deg = v.ell + 1;
    if v.edges.is_empty() {
        return Err(format!("{}: no edges", v.id));
    }
    for e in &v.edges {
        let j1 = BigInt::from(parse_uint(&e.j1).ok_or("j1")?);
        let j2 = BigInt::from(parse_uint(&e.j2).ok_or("j2")?);
        if !phi_zero(&phi, &j1, &j2, &p, deg) {
            return Err(format!("{}: Φ_{}({}, {}) ≠ 0", v.id, v.ell, e.j1, e.j2));
        }
    }
    let depths: Vec<u32> = v.levels.iter().map(|l| l.depth).collect();
    if !depths.contains(&0) || !depths.contains(&v.height) {
        return Err(format!("{}: crater or floor level missing", v.id));
    }
    let conductor = parse_uint(&v.conductor).ok_or("conductor")?;
    let mut c = conductor;
    let mut val = 0u32;
    let ell = BigUint::from(v.ell);
    while !c.is_zero() && &c % &ell == BigUint::zero() {
        c /= &ell;
        val += 1;
    }
    if val != v.height {
        return Err(format!(
            "{}: v_{}(conductor) = {val}, height {}",
            v.id, v.ell, v.height
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cryptanalysis::ec_index_calculus::pollard_rho_ecdlp;

    #[test]
    fn sha256_empty() {
        let d = sha256(b"");
        assert_eq!(
            hex32(&d),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
    }

    #[test]
    fn corpus_loads_and_covers_the_axes() {
        let c = corpus();
        assert_eq!(c.version, 1);
        assert!(c.summary.instances >= 80, "corpus is too small");
        assert!(c.summary.cardinality_bits_min <= 2);
        assert!(c.summary.cardinality_bits_max >= 768);
        let tags: Vec<&str> = c
            .instances
            .iter()
            .flat_map(|i| i.tags.iter().map(String::as_str))
            .collect();
        for need in [
            "koblitz",
            "subfield-curve",
            "proper-subfield",
            "j0",
            "j1728",
            "j-generic",
            "supersingular",
            "anomalous",
            "ordinary",
            "twist-insecure",
            "smooth-order",
            "volcano",
            "ghs",
            "gaudry-shape",
            "prime-degree",
            "composite-degree",
            "char-2",
            "char-3",
            "frobenius",
            "glv",
        ] {
            assert!(tags.contains(&need), "missing tag {need}");
        }
        assert!(c.instances.iter().any(|i| i.field.cardinality_bits == 61));
        assert!(c.instances.iter().any(|i| {
            i.field.kind == "binary" && i.field.degree_kind == "prime" && i.field.degree > 2
        }));
        assert!(c
            .instances
            .iter()
            .any(|i| { i.field.kind == "binary" && i.field.degree_kind == "composite" }));
        assert!(c
            .instances
            .iter()
            .any(|i| { i.field.characteristic == "3" && i.field.degree_kind == "prime" }));
        assert!(c
            .instances
            .iter()
            .any(|i| { i.field.characteristic == "3" && i.field.degree_kind == "composite" }));
        assert!(c
            .instances
            .iter()
            .any(|i| i.endomorphisms.iter().any(|e| e == "glv-6")));
        assert!(c
            .instances
            .iter()
            .any(|i| i.endomorphisms.iter().any(|e| e == "glv-4")));
        assert!(c.volcanoes.iter().any(|v| v.height >= 3));
        assert!(c.volcanoes.iter().any(|v| v.ell == 2));
        assert!(c.volcanoes.iter().any(|v| v.ell == 3));
        let mut ids = std::collections::BTreeSet::new();
        for inst in &c.instances {
            assert!(ids.insert(inst.id.clone()), "duplicate {}", inst.id);
        }
    }

    #[test]
    fn every_instance_rechecks() {
        let c = corpus();
        for inst in &c.instances {
            check_instance(inst).unwrap_or_else(|e| panic!("{e}"));
        }
        for v in &c.volcanoes {
            check_volcano(v).unwrap_or_else(|e| panic!("{e}"));
        }
    }

    #[test]
    fn open_prime_challenge_falls_to_pollard_rho() {
        let c = corpus();
        // Pin a prime-order subgroup.  The shortest order string in the
        // corpus is a char-3 or volcano curve whose model is not the
        // short-Weierstrass group law this driver uses.
        let inst = find(c, "pf-generic-b7").expect("pf-generic-b7");
        assert_eq!(inst.tier, "open");
        assert!(inst.field.cardinality_bits <= 16);
        let curve = prime_curve(inst).expect("prime curve");
        let scalar = inst
            .relation
            .as_ref()
            .and_then(|r| r.scalar.as_ref())
            .and_then(|s| parse_uint(s))
            .expect("published scalar");
        let target_pt = inst
            .relation
            .as_ref()
            .and_then(|r| r.target.as_ref())
            .unwrap();
        let tx = parse_uint(target_pt.x.first().unwrap()).unwrap();
        let ty = parse_uint(target_pt.y.first().unwrap()).unwrap();
        let p = curve.p.clone();
        let target = Point::Affine {
            x: fe(&tx, &p),
            y: fe(&ty, &p),
        };
        let base = curve.generator();
        let n = curve.n.bits() as usize;
        let steps = 32 * (1usize << n.div_ceil(2));
        let got = pollard_rho_ecdlp(&curve, &base, &target, steps).expect("rho finds the log");
        assert_eq!(got, scalar);
    }
}
