/*
 * fuzz_dlog.c - libFuzzer harness for the discrete-logarithm solvers:
 * ca_bsgs_solve / ca_bsgs_table_*, ca_kangaroo_solve, ca_grumpy_solve,
 * ca_rho_solve, ca_dlog_prime_order, ca_pohlig_hellman and ca_dlog.
 *
 * A small group (modulus masked to at most 20 bits) is built from the
 * fuzzed bytes, a base element and a known exponent x0 are chosen, and
 * target = x0 * base.  The solvers are then driven with fuzzed intervals
 * and fuzzed tuning parameters.  Two contracts are asserted:
 *
 *   soundness:    CA_OK => the returned x verifies (x*base == target),
 *                 and for BSGS also lies in [lo, hi].
 *   completeness: the exhaustive solvers (BSGS over the interval, and the
 *                 brute-force solver of ca_dlog_prime_order) must not answer
 *                 CA_ERR_NOT_FOUND when x0 really is in range.
 *
 * Bounding: the group is tiny and every solver gets a max_ops budget, so
 * one input costs well under a millisecond.
 *
 * dp_bits is fuzzed over the whole int32 range and the interval half of the
 * contract is asserted for every solver: both used to be restricted here to
 * work around library defects, which are fixed (see fuzz/crashes/).
 *
 * herd_size is still bounded unless -DCA_FUZZ_WILD_PARAMS is set, but only
 * for cost: the library clamps it, and a herd near the clamp allocates
 * hundreds of megabytes.
 */
#include "cryptanalysis/cryptanalysis.h"

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#define CHK(cond)                                                                                  \
    do {                                                                                           \
        if (!(cond)) __builtin_trap();                                                             \
    } while (0)

typedef struct {
    const uint8_t *d;
    size_t n, i;
} fz;

static uint8_t fz_u8(fz *f) { return f->i < f->n ? f->d[f->i++] : 0; }
static uint32_t fz_u32(fz *f)
{
    uint32_t v = 0;
    for (int k = 0; k < 4; k++) v |= (uint32_t)fz_u8(f) << (8 * k);
    return v;
}
static uint64_t fz_u64(fz *f)
{
    uint64_t v = 0;
    for (int k = 0; k < 8; k++) v |= (uint64_t)fz_u8(f) << (8 * k);
    return v;
}

/* The whole int32 range: the solvers clamp dp_bits, as their headers say. */
static int32_t pick_dp_bits(fz *f) { return (int32_t)fz_u32(f); }

static uint32_t pick_herd(fz *f)
{
    uint32_t h = fz_u32(f);
#ifndef CA_FUZZ_WILD_PARAMS
    /* Bounded for cost, not for correctness: the library clamps herd_size to
     * CA_KANGAROO_MAX_HERD, but a herd near that bound allocates hundreds of
     * megabytes and would dominate the fuzzer's time budget. */
    h &= 0x3FF;
#endif
    return h;
}

/* x*base == target */
static int verifies(const ca_group *g, const ca_elem *base, const ca_elem *target, uint64_t x)
{
    ca_elem t;
    ca_group_mul(g, &t, base, x, NULL);
    return ca_group_equal(g, &t, target);
}

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size);

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    if (size < 32) return 0;
    fz f = {data, size, 0};

    uint8_t flags = fz_u8(&f);
    uint8_t bits = 4 + (uint8_t)(fz_u8(&f) % 17); /* 4 .. 20 bit modulus */
    uint64_t praw = fz_u64(&f) & ((1ULL << bits) - 1);
    uint64_t ca = fz_u64(&f), cb = fz_u64(&f);
    uint64_t basew = fz_u64(&f);
    uint64_t x0raw = fz_u64(&f);
    uint64_t lo = fz_u64(&f), hi = fz_u64(&f);
    uint64_t max_ops = 1 + (fz_u64(&f) & 0xFFFFu); /* always bounded */
    uint8_t solver_sel = fz_u8(&f);

    int ec = flags & 1;
    ca_group g;
    ca_elem base, target;

    uint64_t p = ca_next_prime(ec ? 4 + praw : 2 + praw);
    if (p == 0) return 0;

    if (ec) {
        int ok = 0;
        for (int t = 0; t < 8 && !ok; t++, cb++) ok = ca_group_ec_init(&g, p, ca, cb, 0) == CA_OK;
        if (!ok) return 0;
        /* A curve needs its real order for rho / Pohlig-Hellman.  p is at
         * most 2^20 so Mestre's method is cheap here. */
        uint64_t n = 0;
        if (ca_ec_count_points(p, g.a, g.b, &n, NULL) != CA_OK || n < 2) return 0;
        uint64_t ea = g.a, eb = g.b;
        if (ca_group_ec_init(&g, p, ea, eb, n) != CA_OK) return 0;
        g.cofactor = 1;
        if (!ca_ec_lift_x(&g, &base, basew)) ca_ec_random_point(&g, &base, basew | 1);
    } else {
        if (ca_group_zp_init(&g, p, 0) != CA_OK) return 0;
        const uint64_t w[4] = {basew, 0, 0, 0};
        if (!ca_group_encode(&g, &base, w)) return 0;
        /* optionally work in the subgroup generated by the cofactor */
        if (flags & 2) {
            ca_factorization fac;
            CHK(ca_factorize(p - 1, &fac) == CA_OK);
            if (fac.count) {
                uint64_t q = fac.f[fac.count - 1].p;
                if (ca_group_zp_init(&g, p, q) == CA_OK) {
                    ca_elem t;
                    ca_group_mul(&g, &t, &base, (p - 1) / q, NULL);
                    if (!ca_group_is_identity(&g, &t)) base = t;
                }
            }
        }
    }
    CHK(ca_group_is_valid(&g, &base));
    uint64_t n = g.order;
    if (n < 2) return 0;

    /* Known solution, and the target built from it. */
    uint64_t x0 = x0raw % n;
    ca_group_mul(&g, &target, &base, x0, NULL);
    CHK(verifies(&g, &base, &target, x0));

    /* Interval: clamped into [0, n-1] so the solvers' work stays bounded.
     * lo == hi == 0 keeps its documented meaning (the whole group). */
    uint64_t ilo = lo % n, ihi = hi % n;
    if (ihi < ilo) {
        uint64_t t = ilo;
        ilo = ihi;
        ihi = t;
    }
    int whole = (flags & 4) != 0;
    if (whole) {
        ilo = 0;
        ihi = 0;
    } else {
        /* make sure x0 is inside, so completeness can be asserted */
        if (x0 < ilo) ilo = x0;
        if (x0 > ihi) ihi = x0;
        if (ilo == 0 && ihi == 0) ihi = n - 1;
    }
    uint64_t eff_lo = (ilo == 0 && ihi == 0) ? 0 : ilo;
    uint64_t eff_hi = (ilo == 0 && ihi == 0) ? n - 1 : ihi;
    CHK(x0 >= eff_lo && x0 <= eff_hi);

    uint64_t x = 0;
    ca_stats st;

    /* ---- BSGS: exhaustive, so it must find a solution ------------------ */
    {
        ca_bsgs_params bp;
        ca_bsgs_params_default(&bp);
        bp.table_size = fz_u64(&f) & 0xFFFu; /* 0 => sqrt(width) */
        bp.max_ops = 0;                      /* the group is tiny */
        memset(&st, 0, sizeof(st));
        x = ~0ULL;
        ca_status rc = ca_bsgs_solve(&g, &base, &target, ilo, ihi, &bp, &x, &st);
        /* completeness: x0 is in [eff_lo, eff_hi] and BSGS scans all of it */
        CHK(rc != CA_ERR_NOT_FOUND);
        if (rc == CA_OK) {
            CHK(verifies(&g, &base, &target, x));
            CHK(x >= eff_lo && x <= eff_hi);
        }
    }

    /* ---- amortised table ------------------------------------------------ */
    if (flags & 8) {
        uint64_t m = 1 + (fz_u64(&f) & 0x3FFu);
        ca_bsgs_table *tab = NULL;
        ca_status rc = ca_bsgs_table_new(&g, &base, m, &tab);
        if (rc == CA_OK) {
            CHK(tab != NULL);
            x = ~0ULL;
            rc = ca_bsgs_table_solve(tab, &target, ilo, ihi, &x, NULL);
            CHK(rc != CA_ERR_NOT_FOUND);
            if (rc == CA_OK) {
                CHK(verifies(&g, &base, &target, x));
                CHK(x >= eff_lo && x <= eff_hi);
            }
            ca_bsgs_table_free(tab);
        }
        ca_bsgs_table_free(NULL); /* documented no-op */
    }

    /* ---- kangaroo ------------------------------------------------------- */
    {
        ca_kangaroo_params kp;
        ca_kangaroo_params_default(&kp);
        kp.herd_size = pick_herd(&f);
        kp.dp_bits = pick_dp_bits(&f);
        kp.jumps = fz_u32(&f) & 0x7F;
        kp.seed = fz_u64(&f) | 1;
        kp.max_ops = max_ops;
        memset(&st, 0, sizeof(st));
        x = ~0ULL;
        ca_status rc = ca_kangaroo_solve(&g, &base, &target, ilo, ihi, &kp, &x, &st);
        if (rc == CA_OK) {
            CHK(verifies(&g, &base, &target, x));
            CHK(x >= eff_lo && x <= eff_hi);
        }
    }

    /* ---- grumpy giants -------------------------------------------------- */
    {
        ca_grumpy_params gp;
        ca_grumpy_params_default(&gp);
        gp.m = fz_u64(&f) & 0xFFFFu;
        /* alpha is bounded and finite: the library casts alpha*sqrt(width)
         * to uint64_t, which is undefined for inf/NaN. */
        gp.alpha = (double)(fz_u8(&f)) / 16.0;
        gp.max_ops = max_ops;
        memset(&st, 0, sizeof(st));
        x = ~0ULL;
        ca_status rc = ca_grumpy_solve(&g, &base, &target, ilo, ihi, &gp, &x, &st);
        if (rc == CA_OK) {
            CHK(verifies(&g, &base, &target, x));
            CHK(x >= eff_lo && x <= eff_hi);
        }
    }

    /* ---- Pollard rho (whole group) --------------------------------------- */
    {
        ca_rho_params rp;
        ca_rho_params_default(&rp);
        rp.threads = 1; /* keep one input single-threaded */
        rp.r = fz_u32(&f) & 0xFF;
        rp.dp_bits = pick_dp_bits(&f);
        rp.walks_per_thread = fz_u32(&f) & 0xFF;
        rp.negation_map = (int)(fz_u8(&f) & 1);
        rp.seed = fz_u64(&f) | 1;
        rp.max_ops = max_ops;
        rp.max_table_entries = fz_u64(&f) & 0xFFFFu;
        memset(&st, 0, sizeof(st));
        x = ~0ULL;
        ca_status rc = ca_rho_solve(&g, &base, &target, &rp, &x, &st);
        if (rc == CA_OK) {
            CHK(verifies(&g, &base, &target, x));
            CHK(x < n);
        }
    }

    /* ---- the dlog driver, with every solver selectable ------------------- */
    {
        ca_dlog_params dp;
        ca_dlog_params_default(&dp);
        dp.solver = (ca_solver)(solver_sel % 6);
        dp.bsgs_max_prime = fz_u64(&f) & 0xFFFFFFu;
        dp.bsgs.max_ops = max_ops;
        dp.bsgs.table_size = fz_u64(&f) & 0xFFFu;
        dp.rho.threads = 1;
        dp.rho.seed = 1;
        dp.rho.max_ops = max_ops;
        dp.rho.dp_bits = pick_dp_bits(&f);
        dp.kangaroo.seed = 1;
        dp.kangaroo.max_ops = max_ops;
        dp.kangaroo.dp_bits = pick_dp_bits(&f);
        dp.kangaroo.herd_size = pick_herd(&f);
        dp.grumpy.max_ops = max_ops;
        dp.grumpy.alpha = 0.7;

        /* brute force ignores max_ops, so keep its interval short */
        uint64_t blo = ilo, bhi = ihi;
        if (dp.solver == CA_SOLVER_BRUTE) {
            blo = x0 > 512 ? x0 - 512 : 0;
            bhi = x0 + 512 < n ? x0 + 512 : n - 1;
        }
        memset(&st, 0, sizeof(st));
        x = ~0ULL;
        ca_status rc = ca_dlog_prime_order(&g, &base, &target, blo, bhi, &dp, &x, &st);
        if (rc == CA_OK) CHK(verifies(&g, &base, &target, x));
        if (dp.solver == CA_SOLVER_BRUTE) CHK(rc == CA_OK); /* exhaustive */

        memset(&st, 0, sizeof(st));
        x = ~0ULL;
        rc = ca_pohlig_hellman(&g, &base, &target, &dp, &x, &st);
        if (rc == CA_OK) {
            CHK(verifies(&g, &base, &target, x));
            CHK(x < n);
        }

        memset(&st, 0, sizeof(st));
        x = ~0ULL;
        rc = ca_dlog(&g, &base, &target, &x, &st);
        if (rc == CA_OK) {
            CHK(verifies(&g, &base, &target, x));
            CHK(x < n);
        }
    }

    /* ---- documented rejections ------------------------------------------ */
    if (n >= 2) {
        uint64_t dummy;
        /* empty interval */
        CHK(ca_bsgs_solve(&g, &base, &target, 5, 4, NULL, &dummy, NULL) == CA_ERR_INVALID);
        CHK(ca_kangaroo_solve(&g, &base, &target, 5, 4, NULL, &dummy, NULL) == CA_ERR_INVALID);
        CHK(ca_grumpy_solve(&g, &base, &target, 5, 4, NULL, &dummy, NULL) == CA_ERR_INVALID);
        /* unknown order */
        ca_group g0 = g;
        g0.order = 0;
        CHK(ca_rho_solve(&g0, &base, &target, NULL, &dummy, NULL) == CA_ERR_INVALID ||
            ca_group_is_identity(&g0, &target));
        CHK(ca_bsgs_solve(&g0, &base, &target, 0, 0, NULL, &dummy, NULL) == CA_ERR_INVALID);
    }

    CHK(ca_solver_name((ca_solver)(solver_sel % 6)) != NULL);
    return 0;
}
