"""Generate the existing degree-131 remainder in direct coefficient order.

Conjugating the reciprocal quotient circuit by reversal changes its left
shifts to right shifts. D is the 130-bit high part of a degree-260 dividend:
R = D + (D >> 1) + (D >> 3),
Q = D + (R >> 1) + (R >> 9) + (R >> 25) + (R >> 57) + (R >> 121).
The existing final remainder circuit is then applied to Q directly.
"""
import argparse
from pathlib import Path
import random

from genpolyreduce import left, polynomial, reference


def direct(x):
    d = (x >> 131) & ((1 << 130) - 1)
    r = d ^ (d >> 1) ^ (d >> 3)
    q = d ^ (r >> 1) ^ (r >> 9) ^ (r >> 25) ^ (r >> 57) ^ (r >> 121)
    t = q ^ (q << 2) ^ (q << 3)
    return (x ^ t ^ (q << 124) ^ (t << 64) ^ (t << 96)
            ^ (t << 112) ^ (t << 120) ^ (t << 128)) & ((1 << 131) - 1)


def right(prefix, shift, word):
    offset, bits = divmod(shift, 32)
    src = word + offset
    if src > 4:
        return None
    if not bits:
        return '%s%d' % (prefix, src)
    # Every intermediate remains at most 130 bits. Its top word has two bits.
    parts = [] if src == 4 and bits >= 2 else ['(%s%d >> %d)' % (prefix, src, bits)]
    if src < 4:
        parts.append('(%s%d << %d)' % (prefix, src + 1, 32 - bits))
    return '(' + ' | '.join(parts) + ')' if parts else None


def raw_reduce(h):
    z = h >> 128
    r = z ^ (z >> 2) ^ (z >> 6)
    t = z ^ (z >> 7) ^ (r >> 9) ^ (r >> 25) ^ (r >> 57) ^ (r >> 121)
    v = z ^ (z >> 8) ^ (z >> 24) ^ (z >> 56) ^ (z >> 120)
    q = (z >> 3) ^ (v >> 4) ^ (v >> 5) ^ (v >> 7)
    t = (t & ~7) | ((q ^ (q << 2)) & 7)
    return (h ^ t ^ (t << 64) ^ (t << 96) ^ (t << 112) ^ (t << 120) ^ (t << 128) ^ ((q & 127) << 124)) & ((1 << 131)-1)


def rawRight(prefix, shift, word):
    offset,bits = divmod(shift,32)
    i = word+offset
    if i>4:return None
    if not bits:return f'{prefix}{i}'
    parts=[] if i==4 and bits>=5 else [f'({prefix}{i} >> {bits})']
    if i<4:parts.append(f'({prefix}{i+1} << {32-bits})')
    return '('+' | '.join(parts)+')' if parts else None


def emitRaw():
    lines=['ECC_HD P131 reducePolynomial131(const uint32_t *h) {']
    lines += [f'    const uint32_t z{i}=h[{i+4}]'+(' & 31u' if i==4 else '')+';' for i in range(5)]
    for i in range(5):
        parts=[f'z{i}']+[rawRight('z',s,i) for s in (2,6)]
        lines.append(f'    const uint32_t r{i}='+' ^ '.join(p for p in parts if p)+';')
    for i in range(5):
        parts=[f'z{i}',rawRight('z',7,i)]+[rawRight('r',s,i) for s in (9,25,57,121)]
        lines.append(f'    uint32_t t{i}='+' ^ '.join(p for p in parts if p)+';')
    lines += ['    const uint32_t v=z0 ^ (z0 >> 8) ^ ((z0 ^ z1 ^ z3) >> 24) ^ ((z1 ^ z2 ^ z4) << 8);',
              '    const uint32_t q=(z0 >> 3) ^ (v >> 4) ^ (v >> 5) ^ (v >> 7);',
              '    t0=(t0 & ~7u) | ((q ^ (q << 2)) & 7u);', '    P131 out;',
              '    out.v[0]=h[0] ^ t0;', '    out.v[1]=h[1] ^ t1;',
              '    out.v[2]=h[2] ^ t2 ^ t0;',
              '    out.v[3]=h[3] ^ t3 ^ t1 ^ t0 ^ (t0 << 16) ^ (t0 << 24) ^ (q << 28);',
              '    out.v[4]=(h[4] ^ t4 ^ t2 ^ t1 ^ ((t1 << 16) | (t0 >> 16)) ^ ((t1 << 24) | (t0 >> 8)) ^ t0 ^ (q >> 4)) & 7u;',
              '    return out;', '}']
    return lines


def check():
    f = polynomial()
    if f != 0xd1d0d000d0000000d000000000000000d:
        raise ValueError('existing field polynomial changed')
    rng = random.Random(20260910)
    cases = [0, (1 << 261) - 1] + [1 << i for i in range(261)]
    cases += [rng.getrandbits(261) for _ in range(10000)]
    for x in cases:
        if direct(x) != reference(x, f) or raw_reduce(x) != reference(x, f):
            raise ValueError(('direct reduction mismatch', x))


def generate():
    check()
    lines = ['// Generated by codegen/gendirectreduce.py; included inside eccPacked131.',
             '#pragma once', 'ECC_HD P131 reducePolynomial131(const uint32_t *h) {']
    for i in range(4):
        lines.append('    uint32_t d%d=(h[%d] >> 3) | (h[%d] << 29);' % (i, i + 4, i + 5))
    # Match the original reducer's degree-260 input boundary even if unused
    # high bits of h[8] are set. Valid field products have those bits zero.
    lines.append('    uint32_t d4=(h[8] >> 3)&3u;')
    for i in range(5):
        parts = ['d%d' % i] + [right('d', shift, i) for shift in (1, 3)]
        lines.append('    uint32_t r%d=%s;' % (i, ' ^ '.join(p for p in parts if p)))
    for i in range(5):
        parts = ['d%d' % i] + [right('r', shift, i) for shift in (1, 9, 25, 57, 121)]
        lines.append('    uint32_t q%d=%s;' % (i, ' ^ '.join(p for p in parts if p)))
    for i in range(5):
        lines.append('    uint32_t t%d=q%d ^ %s ^ %s;' % (i, i, left('q', 2, i), left('q', 3, i)))
    lines.append('    P131 out;')
    for i in range(5):
        parts = ['h[%d]' % i, 't%d' % i] + [left('t', s, i) for s in (64, 96, 112, 120, 128)]
        parts.append(left('q', 124, i))
        expr = ' ^ '.join(p for p in parts if p)
        if i == 4:
            expr = '(' + expr + ')&7u'
        lines.append('    out.v[%d]=%s;' % (i, expr))
    return '\n'.join(lines[:2] + ['#if ECC_FROBENIUS_FUSED'] + emitRaw() + ['#else'] + lines[2:] + ['    return out;', '}', '#endif']) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--out', default='../include/packeddirectreduce131.h')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if Path(args.out).read_text() != generated:
            raise SystemExit('direct reduction header does not match the generator')
    else:
        Path(args.out).write_text(generated)
    print('PASS: direct reduction against long division on 261 basis, 2 edge and 10000 dense inputs')
