"""Square reduction through even/odd coefficients of the aligned reducer."""
import argparse
import random
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
from genpolyreduce import polynomial,reference


def square(x):
    b=x>>64
    r=b^(b>>1)^(b>>3)
    s=b^(b>>4)^(b>>12)^(b>>28)^(b>>60)
    qe=s>>2
    qo=(b>>2)^(s>>3)^(s>>4)
    te=(b&~3)|((qe^(qe<<1))&3)
    u=(b>>4)^(r>>5)^(r>>13)^(r>>29)^(r>>61)
    to=(u&~1)|(qo&1)
    even=x^te^(te<<32)^(te<<48)^(te<<56)^(te<<60)^(te<<64)^(qe<<62)
    odd=to^(to<<32)^(to<<48)^(to<<56)^(to<<60)^(to<<64)^(qo<<62)
    return sum(((even>>i)&1)<<(2*i) for i in range(66)) | sum(((odd>>i)&1)<<(2*i+1) for i in range(65))


def right(p,s,i):
    w,k=divmod(s,32);i+=w
    if i>2:return None
    if not k:return f'{p}{i}'
    parts=[] if i==2 and k>=3 else [f'({p}{i} >> {k})']
    if i<2:parts.append(f'({p}{i+1} << {32-k})')
    return '('+' | '.join(parts)+')' if parts else None


def left(p,s,i):
    w,k=divmod(s,32);i-=w
    if i<0:return None
    if not k:return f'{p}{i}'
    parts=[f'({p}{i} << {k})']
    if i:parts.append(f'({p}{i-1} >> {32-k})')
    return '('+' | '.join(parts)+')'


def generate():
    rng=random.Random(20260921)
    values=[0,(1<<131)-1]+[1<<i for i in range(131)]+[rng.getrandbits(131) for _ in range(10000)]
    for x in values:
        h=sum(((x>>i)&1)<<(2*i) for i in range(131))
        assert square(x)==reference(h,polynomial()),x
    lines=['// Generated by codegen/gensquareraw.py; inside eccPacked131.', '#pragma once',
           '#include "zip_square.h"','ECC_HD P131 goal22SquareReduced(P131 a) {',
           '    const uint32_t b0=a.v[2], b1=a.v[3], b2=a.v[4];']
    for i in range(3):
        parts=[f'b{i}']+[right('b',s,i) for s in (1,3)]
        lines.append(f'    const uint32_t r{i}='+' ^ '.join(p for p in parts if p)+';')
    # Only seven low quotient bits survive in the degree-130 remainder.
    parts=['b0']+[right('b',s,0) for s in (4,12,28,60)]
    lines += ['    const uint32_t s='+' ^ '.join(p for p in parts if p)+';',
              '    const uint32_t qe=s>>2, qo=(b0>>2)^(s>>3)^(s>>4);',
              '    const uint32_t te0=(b0 & ~3u) | ((qe ^ (qe<<1)) & 3u);',
              '    const uint32_t te1=b1, te2=b2;']
    for i in range(3):
        parts=[right('b',4,i)]+[right('r',s,i) for s in (5,13,29,61)]
        expr=' ^ '.join(p for p in parts if p) or '0u'
        if i==0:expr='(('+expr+') & ~1u) | (qo & 1u)'
        lines.append(f'    const uint32_t to{i}={expr};')
    for p,axis in [('te','ev'),('to','od')]:
        for i in range(3):
            parts=([f'a.v[{i}]'] if axis=='ev' else [])+[f'{p}{i}']+[left(p,s,i) for s in (32,48,56,60,64)]
            parts.append(('(qe << 30)' if axis=='ev' else '(qo << 30)') if i==1 else ('(qe >> 2)' if axis=='ev' else '(qo >> 2)') if i==2 else None)
            expr=' ^ '.join(p for p in parts if p)
            if i==2:expr='('+expr+') & '+('3u' if axis=='ev' else '1u')
            lines.append(f'    const uint32_t {axis}{i}={expr};')
    lines += ['    P131 out;', '    goal22Zip2(ev0,od0,&out.v[0],&out.v[1]);',
              '    goal22Zip2(ev1,od1,&out.v[2],&out.v[3]);',
              '    out.v[4]=(ev2&1u)|((od2&1u)<<1)|((ev2&2u)<<1);','    return out;','}']
    return '\n'.join(lines)+'\n'


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out',default=str(ROOT/'include/packedsquareraw131.h'))
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    generated=generate()
    if args.check:
        if Path(args.out).read_text()!=generated:
            raise SystemExit('raw square header does not match generator')
    else:
        Path(args.out).write_text(generated)
    print('PASS: aligned square reduction against long division on 10133 inputs')


if __name__=='__main__':main()
