"""Frobenius difference in the expanded polynomial coordinates.

The normal-basis complement represents one and cancels in a + sigma(a).
Only wires 1..130 of the expanded value enter the permutation. Wire zero is
the complement flag and wire 131 is initially zero. This is not a general
replacement for the canonical normal-basis Frobenius API.
"""
import json
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

import genpacked
import gensigma
import argparse

MASK = (1 << 131) - 1


def linear(x, inverse):
    for distance, mask in genpacked.stages(131, inverse):
        x ^= (x >> distance) & mask
    return x


def apply(x, net):
    for distance, mask in net:
        t = ((x >> distance) ^ x) & mask
        x ^= t ^ (t << distance)
    return x


def operations(nets):
    ops=[]
    for stage in range(len(nets[0])):
        distance=nets[0][stage][0]
        for word in range(8):
            masks=[(net[stage][1] >> (32*word)) & 0xffffffff for net in nets]
            if any(masks):ops.append((distance,word,masks))
    return ops, list(dict.fromkeys(tuple(row) for _,_,row in ops))


def cost(nets):
    ops, _ = operations(nets)
    return sum(1 + 2 * (2 if d in (8, 16) else 4 if d < 32 else 3)
               for d, _, _ in ops), len(ops)


def generate(nets):
    ops, _ = operations(nets)
    # Store already expanded byte masks; this table is used only by this API.
    ops = [(d, w, tuple(m | (m << d) if d in (8, 16) else m for m in row))
           for d, w, row in ops]
    rows = list(dict.fromkeys(row for _, _, row in ops))
    lines = ['// Generated by codegen/genshiftedsigma.py; inside eccPacked131.', '#pragma once',
             '#ifdef __CUDACC__', 'static __device__ const', '#else', 'static const', '#endif',
             f'uint32_t sigmaShiftedWalkMasks131[{len(rows)}][8] = {{']
    lines += ['    {' + ','.join(f'0x{m:08x}u' for m in row) + '},' for row in rows]
    lines += ['};', '#ifdef __CUDACC__',
              f'static __shared__ uint32_t sigmaShiftedWalkShared131[{len(rows)}][8];', '#endif',
              'ECC_HD void initShiftedSigmaWalk131() {', '#ifdef __CUDA_ARCH__',
              f'    for (unsigned i=threadIdx.x; i<{len(rows)*8}; i+=blockDim.x)',
              '        sigmaShiftedWalkShared131[i/8][i%8] = __ldg(&sigmaShiftedWalkMasks131[i/8][i%8]);',
              '    __syncthreads();', '#endif', '}',
              'ECC_HD P131 expandedPolynomial131(const P131 &a) {']
    lines += [f'    uint32_t v{i}=a.v[{i}];' for i in range(5)]
    lines += genpacked.emitStages(131, False)
    lines += ['    return P131{{v0,v1,v2,v3,v4}};', '}',
              'ECC_HD P131 normalFromExpanded131(const P131 &a) {',
              '    const uint32_t sign = 0u - (a.v[0] & 1u);', '    P131 out;']
    lines += [f'    out.v[{i}] = ((a.v[{i}] >> 1) | (a.v[{i+1}] << 31)) ^ sign;'
              for i in range(4)]
    lines += ['    out.v[4] = ((a.v[4] >> 1) ^ sign) & 7u;', '    return out;', '}',
              'ECC_HD P131 polynomialFromShiftedDifference131(const P131 &a) {',
              '    const uint32_t sign = 0u - ((a.v[4] >> 3) & 1u);',
              '    uint32_t v0 = (a.v[0] & ~1u) ^ sign;']
    lines += [f'    uint32_t v{i} = a.v[{i}] ^ sign;' for i in range(1, 4)]
    lines += ['    uint32_t v4 = (a.v[4] ^ sign) & 7u;']
    lines += genpacked.emitStages(131, True, combineTail=True)
    lines += ['    return P131{{v0,v1,v2,v3,v4}};', '}',
              'ECC_HD SigmaWalkPair131 sigmaShiftedWalkPair131(P131 a, P131 b, int index) {',
              '#if defined(__CUDACC__) && !defined(__CUDA_ARCH__)',
              '    a.v[0] &= ~1u; b.v[0] &= ~1u;',
              '    a = normalFromExpanded131(a); b = normalFromExpanded131(b);',
              '    for (int i=0;i<index+3;++i) { a=sqr131(a); b=sqr131(b); }',
              '    P131 aa, bb;']
    for v in ('a', 'b'):
        lines.append(f'    {v}{v}.v[0] = {v}.v[0] << 1;')
        lines += [f'    {v}{v}.v[{i}] = ({v}.v[{i}] << 1) | ({v}.v[{i-1}] >> 31);'
                  for i in range(1, 5)]
    lines += ['    return SigmaWalkPair131{aa,bb};', '#else']
    lastWord = max(word + (distance // 32 if distance >= 32 else 0)
                   for distance, word, _ in ops)
    for v in ('a', 'b'):
        lines.append(f'    uint32_t {v}0={v}.v[0]&~1u, ' + ', '.join(f'{v}{i}={v}.v[{i}]' for i in range(1, 5)) + ';')
        if lastWord >= 5:
            lines.append('    uint32_t ' + ', '.join(f'{v}{i}=0' for i in range(5,lastWord+1)) + ';')
    lines.append('    uint32_t t, mask;')
    for distance, word, row in ops:
        index = rows.index(row)
        lines += ['#ifdef __CUDA_ARCH__', f'    mask=sigmaShiftedWalkShared131[{index}][index];',
                  '#else', f'    mask=sigmaShiftedWalkMasks131[{index}][index];', '#endif']
        for v in ('a', 'b'):
            name = f'{v}{word}'
            if distance in (8, 16):
                selector = 0x2301 if distance == 8 else 0x1032
                lines.append(f'    {name}=({name}&~mask)|(goal22BytePerm({name},{name},0x{selector:04x}u)&mask);')
            elif distance < 32:
                lines += [f'    t=(({name}>>{distance})^{name})&mask;', f'    {name}^=t^(t<<{distance});']
            else:
                other = f'{v}{word+distance//32}'
                lines += [f'    t=({name}^{other})&mask;', f'    {name}^=t; {other}^=t;']
    lines += ['    return SigmaWalkPair131{P131{{a0,a1,a2,a3,a4&15u}},P131{{b0,b1,b2,b3,b4&15u}}};',
              '#endif', '}']
    return '\n'.join(lines) + '\n'


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out',default=str(ROOT/'include/packedshiftedsigma131.h'))
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    encoded=json.loads((Path(__file__).parent/'shifted_sigma_routes.json').read_text())
    nets=[[(d,int(mask,16)) for d,mask in net] for net in encoded]
    rng=random.Random(2026092123)
    for k, net in zip(range(3, 11), nets):
        for i in range(130):
            assert apply(1 << (i+1), net) == 1 << (gensigma.permutation(k)[i]+1)
    vectors = [0, MASK] + [1 << i for i in range(131)] + [rng.getrandbits(131) for _ in range(1000)]
    for poly in vectors:
        expanded = linear(poly, False)
        normal = (expanded >> 1) ^ (MASK if expanded & 1 else 0)
        assert normal.bit_count() == (131-(expanded.bit_count()-1) if expanded & 1 else expanded.bit_count())
        for k, net in zip(range(3, 11), nets):
            permutation = gensigma.permutation(k)
            sigma = sum(((normal >> i) & 1) << permutation[i] for i in range(131))
            delta = normal ^ sigma
            expected = linear(((delta << 1) ^ (MASK if delta >> 130 else 0)) & MASK, True)
            shifted = expanded ^ apply(expanded & ~1, net)
            actual = linear(((shifted & ~1) ^ (MASK if (shifted >> 131) & 1 else 0)) & MASK, True)
            assert expected == actual, (poly, k)
    generated=generate(nets)
    if args.check:
        if Path(args.out).read_text()!=generated:
            raise SystemExit('shifted Frobenius header does not match generator')
    else:
        Path(args.out).write_text(generated)
    print('PASS: shifted Frobenius difference: 130 live wires x 8 powers; 1133 polynomial basis/random vectors x 8 powers')


if __name__ == '__main__':
    main()
