//! Loader for the elliptic-curve challenge corpus in `challenges/ecc/`.
//!
//! The corpus is generated by `challenges/ecc/generate.py`. This module
//! reads the catalog and individual records. Prime-field short-Weierstrass
//! records can be turned into a collaborative Pollard-rho job. Extension,
//! binary, and characteristic-3 records stay as JSON for the index-calculus
//! tools; their coordinates are not prime-field points.

use std::fs;
use std::path::{Path, PathBuf};

use num_bigint::BigUint;
use num_traits::One;
use serde_json::Value;

use crate::cryptanalysis::pollard_collab::job::{hex_of, HexPoint, JobSpec, PROTOCOL_VERSION};
use crate::ecc::field::FieldElement;
use crate::ecc::point::Point;

/// Repository-root corpus, relative to the suite crate manifest.
pub fn default_corpus_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../challenges/ecc")
}

/// One row of `catalog.json`.
#[derive(Clone, Debug)]
pub struct CatalogEntry {
    pub id: String,
    pub family: String,
    pub tier: String,
    pub cardinality_bits: u64,
    pub field_type: String,
    pub degree: Option<u64>,
    pub degree_kind: Option<String>,
    pub tags: Vec<String>,
    pub subgroup_probable_prime: bool,
    pub verification: String,
    pub order_certificate: String,
    pub inspect: bool,
}

/// Parsed `catalog.json`.
#[derive(Clone, Debug)]
pub struct Catalog {
    pub schema_version: u64,
    pub curve_count: u64,
    pub cardinality_bits_min: u64,
    pub cardinality_bits_max: u64,
    pub families: Vec<(String, u64)>,
    pub curves: Vec<CatalogEntry>,
}

/// A prime-field short-Weierstrass challenge, ready for the group law.
#[derive(Clone, Debug)]
pub struct PrimeFieldChallenge {
    pub id: String,
    pub family: String,
    pub tier: String,
    pub p: BigUint,
    pub a: BigUint,
    pub b: BigUint,
    pub subgroup_order: BigUint,
    pub cofactor: BigUint,
    pub generator: Point,
    pub target: Point,
    pub known_log: Option<BigUint>,
}

impl Catalog {
    pub fn load(root: &Path) -> Result<Self, String> {
        let path = root.join("catalog.json");
        let text =
            fs::read_to_string(&path).map_err(|e| format!("read {}: {e}", path.display()))?;
        let value: Value =
            serde_json::from_str(&text).map_err(|e| format!("parse {}: {e}", path.display()))?;
        let curves = value["curves"]
            .as_array()
            .ok_or("catalog.curves is not an array")?
            .iter()
            .map(parse_entry)
            .collect::<Result<Vec<_>, _>>()?;
        let families = value["families"]
            .as_object()
            .ok_or("catalog.families is not an object")?
            .iter()
            .map(|(k, v)| {
                v.as_u64()
                    .map(|n| (k.clone(), n))
                    .ok_or_else(|| format!("family count for {k} is not an integer"))
            })
            .collect::<Result<Vec<_>, _>>()?;
        Ok(Self {
            schema_version: value["schema_version"].as_u64().unwrap_or(0),
            curve_count: value["curve_count"].as_u64().unwrap_or(curves.len() as u64),
            cardinality_bits_min: value["cardinality_bits_min"].as_u64().unwrap_or(0),
            cardinality_bits_max: value["cardinality_bits_max"].as_u64().unwrap_or(0),
            families,
            curves,
        })
    }

    pub fn get(&self, id: &str) -> Option<&CatalogEntry> {
        self.curves.iter().find(|c| c.id == id)
    }
}

fn parse_entry(value: &Value) -> Result<CatalogEntry, String> {
    let id = value["id"]
        .as_str()
        .ok_or("catalog entry missing id")?
        .to_string();
    Ok(CatalogEntry {
        family: value["family"].as_str().unwrap_or("").to_string(),
        tier: value["tier"].as_str().unwrap_or("").to_string(),
        cardinality_bits: value["cardinality_bits"].as_u64().unwrap_or(0),
        field_type: value["field_type"].as_str().unwrap_or("").to_string(),
        degree: value["degree"].as_u64(),
        degree_kind: value["degree_kind"].as_str().map(str::to_string),
        tags: value["tags"]
            .as_array()
            .map(|tags| {
                tags.iter()
                    .filter_map(|t| t.as_str().map(str::to_string))
                    .collect()
            })
            .unwrap_or_default(),
        subgroup_probable_prime: value["subgroup_probable_prime"].as_bool().unwrap_or(false),
        verification: value["verification"].as_str().unwrap_or("").to_string(),
        order_certificate: value["order_certificate"]
            .as_str()
            .unwrap_or("")
            .to_string(),
        inspect: value["inspect"].as_bool().unwrap_or(false),
        id,
    })
}

/// Read `curves/<id>.json`.
pub fn load_record(root: &Path, id: &str) -> Result<Value, String> {
    if id.is_empty() || id.contains(['/', '\\', '.']) {
        return Err(format!("refusing curve id `{id}`"));
    }
    let path = root.join("curves").join(format!("{id}.json"));
    let text = fs::read_to_string(&path).map_err(|e| format!("read {}: {e}", path.display()))?;
    serde_json::from_str(&text).map_err(|e| format!("parse {}: {e}", path.display()))
}

/// Prime-field short Weierstrass record, or an error if the record is another model.
pub fn prime_field_challenge(record: &Value) -> Result<PrimeFieldChallenge, String> {
    let model = record["model"].as_str().unwrap_or("");
    let field_type = record["field"]["type"].as_str().unwrap_or("");
    if model != "short-weierstrass" || field_type != "prime" {
        return Err(format!(
            "rho jobs need a prime-field short-Weierstrass curve (got {field_type}/{model})"
        ));
    }
    let id = record["id"].as_str().unwrap_or("").to_string();
    let p = parse_uint(
        record["field"]["cardinality"].as_str().unwrap_or(""),
        "modulus",
    )?;
    let a = parse_uint(record["a"].as_str().unwrap_or(""), "a")?;
    let b = parse_uint(record["b"].as_str().unwrap_or(""), "b")?;
    let subgroup_order = parse_uint(
        record["subgroup_order"].as_str().unwrap_or(""),
        "subgroup_order",
    )?;
    let cofactor = parse_uint(record["cofactor"].as_str().unwrap_or(""), "cofactor")?;
    let generator = point_from(&record["generator"], &p)?;
    let target = point_from(&record["target"], &p)?;
    let known_log = match record.get("known_log") {
        Some(Value::String(s)) => Some(parse_uint(s, "known_log")?),
        Some(Value::Null) | None => None,
        Some(_) => return Err("known_log must be a hex string or null".into()),
    };
    Ok(PrimeFieldChallenge {
        id,
        family: record["family"].as_str().unwrap_or("").to_string(),
        tier: record["tier"].as_str().unwrap_or("").to_string(),
        p,
        a,
        b,
        subgroup_order,
        cofactor,
        generator,
        target,
        known_log,
    })
}

impl PrimeFieldChallenge {
    pub fn a_fe(&self) -> FieldElement {
        FieldElement::new(self.a.clone(), self.p.clone())
    }

    /// `y^2 = x^3 + a x + b` over `F_p`.
    pub fn is_on_curve(&self, point: &Point) -> bool {
        match point {
            Point::Infinity => true,
            Point::Affine { x, y } => {
                let lhs = y.mul(y);
                let a = self.a_fe();
                let rhs = x
                    .mul(&x.mul(x))
                    .add(&a.mul(x))
                    .add(&FieldElement::new(self.b.clone(), self.p.clone()));
                lhs == rhs
            }
        }
    }

    /// Collaborative rho job for this curve's published target.
    ///
    /// The secret is not copied into the job. `check` records keep
    /// `known_log` in the curve JSON so a solver can be graded afterwards.
    pub fn rho_job(&self, seed: u64) -> Result<JobSpec, String> {
        if self.subgroup_order <= BigUint::one() {
            return Err("subgroup order must be at least 2".into());
        }
        let dp_bits = ((self.subgroup_order.bits() as u32) / 4).clamp(2, 20) as u8;
        Ok(JobSpec {
            version: PROTOCOL_VERSION,
            name: self.id.clone(),
            p: hex_of(&self.p),
            a: hex_of(&self.a),
            b: hex_of(&self.b),
            generator: HexPoint::from_point(&self.generator).ok_or("generator is the identity")?,
            target: HexPoint::from_point(&self.target).ok_or("target is the identity")?,
            order: hex_of(&self.subgroup_order),
            dp_bits,
            num_branches: 32,
            negation_map: false,
            unit_size: 256,
            max_steps_per_walker: 0,
            seed,
        })
    }
}

fn point_from(value: &Value, p: &BigUint) -> Result<Point, String> {
    let x = parse_uint(value["x"].as_str().unwrap_or(""), "x")?;
    let y = parse_uint(value["y"].as_str().unwrap_or(""), "y")?;
    if &x >= p || &y >= p {
        return Err("point coordinate is outside the field".into());
    }
    Ok(Point::Affine {
        x: FieldElement::new(x, p.clone()),
        y: FieldElement::new(y, p.clone()),
    })
}

fn parse_uint(text: &str, label: &str) -> Result<BigUint, String> {
    let digits = text.trim().strip_prefix("0x").unwrap_or(text.trim());
    if digits.is_empty() {
        return Err(format!("{label} is empty"));
    }
    BigUint::parse_bytes(digits.as_bytes(), 16)
        .ok_or_else(|| format!("{label} is not hexadecimal: {text}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn corpus() -> PathBuf {
        default_corpus_root()
    }

    #[test]
    fn catalog_spans_the_requested_families() {
        let catalog = Catalog::load(&corpus()).expect("catalog");
        assert_eq!(catalog.schema_version, 1);
        assert_eq!(catalog.curve_count, catalog.curves.len() as u64);
        assert!(
            catalog.curve_count >= 150,
            "curve count {}",
            catalog.curve_count
        );
        assert!(catalog.cardinality_bits_min <= 8);
        assert!(catalog.cardinality_bits_max >= 760);

        let families: Vec<&str> = catalog.families.iter().map(|(n, _)| n.as_str()).collect();
        for required in [
            "prime-j0",
            "prime-j1728",
            "prime-cm",
            "prime-anomalous",
            "prime-supersingular",
            "prime-bn-pairing",
            "isogeny-volcano",
            "binary-koblitz",
            "binary-random",
            "binary-subfield",
            "binary-supersingular",
            "char3-subfield",
            "char3-supersingular",
            "odd-extension-subfield",
        ] {
            assert!(families.contains(&required), "missing family {required}");
        }

        let mut tags = std::collections::BTreeSet::new();
        let mut field_types = std::collections::BTreeSet::new();
        let mut degree_kinds = std::collections::BTreeSet::new();
        for curve in &catalog.curves {
            tags.extend(curve.tags.iter().cloned());
            field_types.insert(curve.field_type.clone());
            if let Some(kind) = &curve.degree_kind {
                degree_kinds.insert(kind.clone());
            }
        }
        for tag in [
            "j0",
            "j1728",
            "koblitz",
            "volcano",
            "composite-degree",
            "prime-degree",
            "subfield",
        ] {
            assert!(tags.contains(tag), "missing tag {tag}");
        }
        for kind in ["prime", "composite", "prime-field"] {
            assert!(degree_kinds.contains(kind), "missing degree kind {kind}");
        }
        for ty in ["prime", "binary", "extension"] {
            assert!(field_types.contains(ty), "missing field type {ty}");
        }

        let exhibit = load_record(&corpus(), "fp-volcano-d7-l3-exhibit").expect("volcano exhibit");
        let height = exhibit["volcanoes"]
            .as_array()
            .into_iter()
            .flatten()
            .filter_map(|v| v["height"].as_u64())
            .max()
            .unwrap_or(0);
        let depth = exhibit["volcano_depth_reached"].as_u64().unwrap_or(0);
        let levels = exhibit["layers"].as_array().map(Vec::len).unwrap_or(0);
        assert!(height >= 2, "volcano height {height}");
        assert!(
            depth >= 2 && levels >= 3,
            "volcano depth {depth} levels {levels}"
        );

        let wide = load_record(&corpus(), "fp-j0-b768").expect("768-bit j=0");
        assert_eq!(wide["a"].as_str(), Some("0x0"));
        assert_eq!(wide["field"]["cardinality_bits"].as_u64(), Some(768));

        let koblitz = load_record(&corpus(), "f2-koblitz-a0-m768").expect("koblitz 768");
        assert_eq!(koblitz["field"]["degree"].as_u64(), Some(768));
        assert_eq!(koblitz["b"].as_str(), Some("0x1"));
    }

    #[test]
    fn small_prime_field_challenges_match_the_group_law() {
        let catalog = Catalog::load(&corpus()).expect("catalog");
        let mut checked = 0u32;
        for entry in &catalog.curves {
            if entry.field_type != "prime" || entry.cardinality_bits > 32 {
                continue;
            }
            let record = load_record(&corpus(), &entry.id).expect("record");
            if record["model"] != "short-weierstrass" {
                continue;
            }
            let curve = prime_field_challenge(&record).expect("prime challenge");
            assert!(
                curve.is_on_curve(&curve.generator),
                "{} generator",
                curve.id
            );
            assert!(curve.is_on_curve(&curve.target), "{} target", curve.id);
            let a = curve.a_fe();
            assert_eq!(
                curve.generator.scalar_mul(&curve.subgroup_order, &a),
                Point::Infinity,
                "{} subgroup",
                curve.id
            );
            assert_eq!(
                curve.target.scalar_mul(&curve.subgroup_order, &a),
                Point::Infinity,
                "{} target order",
                curve.id
            );
            if let Some(k) = &curve.known_log {
                assert_eq!(
                    curve.generator.scalar_mul(k, &a),
                    curve.target,
                    "{} known log",
                    curve.id
                );
            }
            let job = curve.rho_job(1).expect("rho job");
            assert_eq!(job.name, curve.id);
            checked += 1;
        }
        assert!(checked >= 8, "only checked {checked} small prime curves");
    }
}
