// Generated by codegen/gensigma.py; included inside eccPacked131.
#pragma once
#ifdef __CUDACC__
#define ECC_SIGMA_WALK_STORAGE static __device__ __align__(32) const
#define ECC_SIGMA_INV_STORAGE static __constant__ __align__(32) const
#else
#define ECC_SIGMA_WALK_STORAGE alignas(32) static const
#define ECC_SIGMA_INV_STORAGE alignas(32) static const
#endif
ECC_SIGMA_WALK_STORAGE uint32_t sigmaWalkNetwork131Masks[56][8] = {
    {0x00000000u,0x00000000u,0x00550000u,0x00000000u,0x11100000u,0x55540000u,0x00000000u,0x00000000u},
    {0x00000000u,0x00015555u,0x00000005u,0x00000000u,0x00000051u,0x00555501u,0x00554000u,0x00000000u},
    {0x00000000u,0x00000155u,0x01540155u,0x40000000u,0x44444100u,0x40000400u,0x15555400u,0x00000000u},
    {0x55540000u,0x00000000u,0x05540154u,0x00004141u,0x00000444u,0x55541555u,0x55550000u,0x54005000u},
    {0x00000005u,0x00000000u,0x00000000u,0x00000000u,0x00000000u,0x00000005u,0x00000005u,0x00000005u},
    {0x00000000u,0x22112200u,0x30001100u,0x31001300u,0x30303030u,0x33300020u,0x00000000u,0x11220000u},
    {0x11110000u,0x00223333u,0x20131100u,0x21010300u,0x20000010u,0x23322001u,0x11222000u,0x00133200u},
    {0x00000001u,0x00000000u,0x32000220u,0x01130111u,0x11313120u,0x03331002u,0x22233111u,0x11101220u},
    {0x00000000u,0x10000002u,0x31200223u,0x01120011u,0x21203313u,0x11311200u,0x02200000u,0x23220000u},
    {0x00000001u,0x00000003u,0x00000000u,0x00000002u,0x00000001u,0x00000000u,0x00000000u,0x00000002u},
    {0x00000000u,0x000a0000u,0x01080b00u,0x00040000u,0x0c0a0100u,0x05030c00u,0x08000000u,0x04040400u},
    {0x03030f0fu,0x03090800u,0x0e03050au,0x060f0e00u,0x010f0d00u,0x04030408u,0x0c00080au,0x090c0402u},
    {0x00010303u,0x08040c01u,0x0201090au,0x09010008u,0x0005010du,0x04030400u,0x0501030eu,0x08080208u},
    {0x05040404u,0x0c04060au,0x0b070109u,0x0703020au,0x0c07030fu,0x00030002u,0x0f060f0fu,0x09000305u},
    {0x00000000u,0x0000000cu,0x00000007u,0x00000005u,0x00000005u,0x00000002u,0x0000000bu,0x00000002u},
    {0x00000000u,0x00ff0000u,0x00020000u,0x005c0000u,0x00460000u,0x00220000u,0x00ba0000u,0x00510000u},
    {0x009a0011u,0x006a008du,0x0080008au,0x00c10009u,0x00d500b7u,0x00a200ccu,0x003000b5u,0x00840007u},
    {0x000300aeu,0x00ea0054u,0x00ff00d3u,0x001f0004u,0x00e70084u,0x002b0070u,0x0032009eu,0x00380035u},
    {0x002b0003u,0x0006009bu,0x005700e1u,0x001a000au,0x00dd00d5u,0x00f000c1u,0x00110081u,0x005e004eu},
    {0x0000000au,0x00000041u,0x00000020u,0x00000018u,0x00000012u,0x00000000u,0x00000000u,0x00000021u},
    {0x00002020u,0x00005001u,0x00002c80u,0x0000a010u,0x00009009u,0x000086d7u,0x0000020au,0x00002319u},
    {0x0000cdcdu,0x00000656u,0x000022acu,0x00007700u,0x000011efu,0x00005928u,0x00004048u,0x00006198u},
    {0x0000ccdeu,0x00001550u,0x0000048au,0x0000e3bcu,0x0000b190u,0x000088f0u,0x000021e9u,0x00004980u},
    {0x00000204u,0x00000000u,0x00002000u,0x00001000u,0x00001000u,0x00000008u,0x00000090u,0x00000000u},
    {0xbebe0110u,0x36001488u,0xf0151500u,0xa9080800u,0x743bdcd6u,0x03e350d6u,0x00004766u,0x4110f0c3u},
    {0x02040800u,0x00004080u,0x20000050u,0x10000840u,0x10000240u,0x00000001u,0x00100020u,0x00000108u},
    {0x00000000u,0x00000100u,0x00000000u,0x00000000u,0x00000000u,0x00000020u,0x00000000u,0x00000000u},
    {0x02000800u,0x00004000u,0x20000040u,0x10000800u,0x10000200u,0x00000000u,0x00100000u,0x00000008u},
    {0x00000000u,0x00000000u,0x00000000u,0x00000000u,0x00000000u,0x00080000u,0x00800000u,0x00002000u},
    {0x00040000u,0x00000080u,0x00000010u,0x00000040u,0x00000040u,0x00000001u,0x00000020u,0x00000100u},
    {0x00ffff00u,0x5a0f0ff0u,0xccb4d23cu,0xc7323966u,0xe7855555u,0x7adffe00u,0xc53a3ff0u,0x80f49c7cu},
    {0xbe41ce31u,0x2d29d27cu,0x34638fdcu,0x2e0d84bfu,0x107e89abu,0x792ca6d7u,0x0c31489eu,0xc5a76ca3u},
    {0x0fe61ef0u,0x919c9cfcu,0x050fe16au,0x6d997555u,0x807bef11u,0xb73fe9f0u,0x6052da4cu,0xb397d48au},
    {0xe60ff01eu,0x19c9c9cau,0x492dc5d9u,0x6593aaaau,0xa076ba5du,0xa6fc2cb8u,0x36f387c7u,0xce2d149au},
    {0x0000c4ecu,0x000044bau,0x00009407u,0x0000aa51u,0x0000c0a4u,0x0000a99cu,0x0000c7ceu,0x0000ca71u},
    {0x00007ccdu,0x000017e9u,0x000078a6u,0x00001ef7u,0x0000e0c3u,0x00005166u,0x0000718au,0x0000000fu},
    {0x0000fcc6u,0x00004de2u,0x0000740cu,0x0000f908u,0x0000cc97u,0x000095feu,0x00009ce8u,0x00005136u},
    {0x0000cc6cu,0x0000359eu,0x0000b888u,0x0000deafu,0x0000e747u,0x00001261u,0x00006b27u,0x00008ad1u},
    {0x00ab00beu,0x0056003bu,0x00830047u,0x004a00e3u,0x007700f8u,0x001a000au,0x00af0011u,0x001700d8u},
    {0x008a00ebu,0x005b00fcu,0x0082009eu,0x003700a8u,0x00e900b2u,0x000c00e7u,0x00e400d7u,0x00e9000cu},
    {0x00540045u,0x002c00b6u,0x000c0098u,0x00270059u,0x00d20006u,0x00cd00beu,0x0095002fu,0x00e10014u},
    {0x00750014u,0x00a300cau,0x00080002u,0x006f00d0u,0x00ad0097u,0x000d0073u,0x00ec00a1u,0x00120018u},
    {0x0a050307u,0x0a000905u,0x03080907u,0x08070209u,0x0a060b03u,0x03060f03u,0x0c060502u,0x0c0d000bu},
    {0x050a0c08u,0x0c0a0400u,0x020a0902u,0x0f010f06u,0x04090100u,0x090c090bu,0x0f0a0103u,0x06060200u},
    {0x0a050307u,0x050d060au,0x0f0c020du,0x09070106u,0x0e080103u,0x090c090bu,0x0c07090au,0x0d00020eu},
    {0x050a0d08u,0x03050b0fu,0x0e090208u,0x0e000304u,0x090d0109u,0x080e090fu,0x0508070eu,0x050c0b06u},
    {0x12232010u,0x30011333u,0x13302312u,0x01122110u,0x32323320u,0x31321133u,0x12222312u,0x01201330u},
    {0x12232110u,0x03122200u,0x21222301u,0x12232201u,0x33232333u,0x11311333u,0x10111102u,0x03221000u},
    {0x12232110u,0x30211133u,0x20021020u,0x01001220u,0x11321031u,0x11111111u,0x02322223u,0x33223320u},
    {0x12232110u,0x03122200u,0x12113112u,0x20122332u,0x33132103u,0x00101111u,0x23301111u,0x11100123u},
    {0x00000001u,0x00000003u,0x00000001u,0x00000003u,0x00000001u,0x00000002u,0x00000002u,0x00000000u},
    {0x05500550u,0x11014054u,0x50004140u,0x40550154u,0x01100454u,0x00010515u,0x10451440u,0x15054054u},
    {0x05500550u,0x11014454u,0x05151414u,0x50154055u,0x40110044u,0x00000000u,0x41045144u,0x54050150u},
    {0x05500550u,0x11014454u,0x50404141u,0x15005401u,0x40110044u,0x00000000u,0x44104514u,0x50150540u},
    {0x05500550u,0x11014454u,0x05151414u,0x05401500u,0x40011004u,0x00000000u,0x14410451u,0x40540501u},
    {0x00000004u,0x00000000u,0x00000001u,0x00000000u,0x00000001u,0x00000004u,0x00000005u,0x00000005u},
};
static ECC_BIG P131 sigmaWalkNetwork131(P131 a, int index) {
#if defined(__CUDACC__) && !defined(__CUDA_ARCH__)
    const int exponents[] = {3,4,5,6,7,8,9,10};
    for (int i=0;i<exponents[index];i++) a=sqr131(a);
    return a;
#else
    uint32_t v0=a.v[0], v1=a.v[1], v2=a.v[2], v3=a.v[3], v4=a.v[4];
    uint32_t v5=0, v6=0, v7=0, t, mask;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[0][index]);
#else
    mask=sigmaWalkNetwork131Masks[0][index];
#endif
    t=((v0 >> 1)^v0)&mask;
    v0^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[1][index]);
#else
    mask=sigmaWalkNetwork131Masks[1][index];
#endif
    t=((v1 >> 1)^v1)&mask;
    v1^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[2][index]);
#else
    mask=sigmaWalkNetwork131Masks[2][index];
#endif
    t=((v2 >> 1)^v2)&mask;
    v2^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[3][index]);
#else
    mask=sigmaWalkNetwork131Masks[3][index];
#endif
    t=((v3 >> 1)^v3)&mask;
    v3^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[4][index]);
#else
    mask=sigmaWalkNetwork131Masks[4][index];
#endif
    t=((v4 >> 1)^v4)&mask;
    v4^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[5][index]);
#else
    mask=sigmaWalkNetwork131Masks[5][index];
#endif
    t=((v0 >> 2)^v0)&mask;
    v0^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[6][index]);
#else
    mask=sigmaWalkNetwork131Masks[6][index];
#endif
    t=((v1 >> 2)^v1)&mask;
    v1^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[7][index]);
#else
    mask=sigmaWalkNetwork131Masks[7][index];
#endif
    t=((v2 >> 2)^v2)&mask;
    v2^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[8][index]);
#else
    mask=sigmaWalkNetwork131Masks[8][index];
#endif
    t=((v3 >> 2)^v3)&mask;
    v3^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[9][index]);
#else
    mask=sigmaWalkNetwork131Masks[9][index];
#endif
    t=((v4 >> 2)^v4)&mask;
    v4^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[10][index]);
#else
    mask=sigmaWalkNetwork131Masks[10][index];
#endif
    t=((v0 >> 4)^v0)&mask;
    v0^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[11][index]);
#else
    mask=sigmaWalkNetwork131Masks[11][index];
#endif
    t=((v1 >> 4)^v1)&mask;
    v1^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[12][index]);
#else
    mask=sigmaWalkNetwork131Masks[12][index];
#endif
    t=((v2 >> 4)^v2)&mask;
    v2^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[13][index]);
#else
    mask=sigmaWalkNetwork131Masks[13][index];
#endif
    t=((v3 >> 4)^v3)&mask;
    v3^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[14][index]);
#else
    mask=sigmaWalkNetwork131Masks[14][index];
#endif
    t=((v4 >> 4)^v4)&mask;
    v4^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[15][index]);
#else
    mask=sigmaWalkNetwork131Masks[15][index];
#endif
    t=((v0 >> 8)^v0)&mask;
    v0^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[16][index]);
#else
    mask=sigmaWalkNetwork131Masks[16][index];
#endif
    t=((v1 >> 8)^v1)&mask;
    v1^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[17][index]);
#else
    mask=sigmaWalkNetwork131Masks[17][index];
#endif
    t=((v2 >> 8)^v2)&mask;
    v2^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[18][index]);
#else
    mask=sigmaWalkNetwork131Masks[18][index];
#endif
    t=((v3 >> 8)^v3)&mask;
    v3^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[19][index]);
#else
    mask=sigmaWalkNetwork131Masks[19][index];
#endif
    t=((v4 >> 8)^v4)&mask;
    v4^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[20][index]);
#else
    mask=sigmaWalkNetwork131Masks[20][index];
#endif
    t=((v1 >> 16)^v1)&mask;
    v1^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[21][index]);
#else
    mask=sigmaWalkNetwork131Masks[21][index];
#endif
    t=((v2 >> 16)^v2)&mask;
    v2^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[22][index]);
#else
    mask=sigmaWalkNetwork131Masks[22][index];
#endif
    t=((v3 >> 16)^v3)&mask;
    v3^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[23][index]);
#else
    mask=sigmaWalkNetwork131Masks[23][index];
#endif
    t=((v4 >> 16)^v4)&mask;
    v4^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[24][index]);
#else
    mask=sigmaWalkNetwork131Masks[24][index];
#endif
    t=(v2^v3)&mask;
    v2^=t; v3^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[25][index]);
#else
    mask=sigmaWalkNetwork131Masks[25][index];
#endif
    t=(v4^v5)&mask;
    v4^=t; v5^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[26][index]);
#else
    mask=sigmaWalkNetwork131Masks[26][index];
#endif
    t=(v4^v6)&mask;
    v4^=t; v6^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[27][index]);
#else
    mask=sigmaWalkNetwork131Masks[27][index];
#endif
    t=(v5^v7)&mask;
    v5^=t; v7^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[28][index]);
#else
    mask=sigmaWalkNetwork131Masks[28][index];
#endif
    t=(v0^v4)&mask;
    v0^=t; v4^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[29][index]);
#else
    mask=sigmaWalkNetwork131Masks[29][index];
#endif
    t=(v1^v5)&mask;
    v1^=t; v5^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[26][index]);
#else
    mask=sigmaWalkNetwork131Masks[26][index];
#endif
    t=(v2^v6)&mask;
    v2^=t; v6^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[27][index]);
#else
    mask=sigmaWalkNetwork131Masks[27][index];
#endif
    t=(v3^v7)&mask;
    v3^=t; v7^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[30][index]);
#else
    mask=sigmaWalkNetwork131Masks[30][index];
#endif
    t=(v0^v2)&mask;
    v0^=t; v2^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[31][index]);
#else
    mask=sigmaWalkNetwork131Masks[31][index];
#endif
    t=(v1^v3)&mask;
    v1^=t; v3^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[26][index]);
#else
    mask=sigmaWalkNetwork131Masks[26][index];
#endif
    t=(v4^v6)&mask;
    v4^=t; v6^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[27][index]);
#else
    mask=sigmaWalkNetwork131Masks[27][index];
#endif
    t=(v5^v7)&mask;
    v5^=t; v7^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[32][index]);
#else
    mask=sigmaWalkNetwork131Masks[32][index];
#endif
    t=(v0^v1)&mask;
    v0^=t; v1^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[33][index]);
#else
    mask=sigmaWalkNetwork131Masks[33][index];
#endif
    t=(v2^v3)&mask;
    v2^=t; v3^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[25][index]);
#else
    mask=sigmaWalkNetwork131Masks[25][index];
#endif
    t=(v4^v5)&mask;
    v4^=t; v5^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[34][index]);
#else
    mask=sigmaWalkNetwork131Masks[34][index];
#endif
    t=((v0 >> 16)^v0)&mask;
    v0^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[35][index]);
#else
    mask=sigmaWalkNetwork131Masks[35][index];
#endif
    t=((v1 >> 16)^v1)&mask;
    v1^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[36][index]);
#else
    mask=sigmaWalkNetwork131Masks[36][index];
#endif
    t=((v2 >> 16)^v2)&mask;
    v2^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[37][index]);
#else
    mask=sigmaWalkNetwork131Masks[37][index];
#endif
    t=((v3 >> 16)^v3)&mask;
    v3^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[23][index]);
#else
    mask=sigmaWalkNetwork131Masks[23][index];
#endif
    t=((v4 >> 16)^v4)&mask;
    v4^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[38][index]);
#else
    mask=sigmaWalkNetwork131Masks[38][index];
#endif
    t=((v0 >> 8)^v0)&mask;
    v0^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[39][index]);
#else
    mask=sigmaWalkNetwork131Masks[39][index];
#endif
    t=((v1 >> 8)^v1)&mask;
    v1^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[40][index]);
#else
    mask=sigmaWalkNetwork131Masks[40][index];
#endif
    t=((v2 >> 8)^v2)&mask;
    v2^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[41][index]);
#else
    mask=sigmaWalkNetwork131Masks[41][index];
#endif
    t=((v3 >> 8)^v3)&mask;
    v3^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[19][index]);
#else
    mask=sigmaWalkNetwork131Masks[19][index];
#endif
    t=((v4 >> 8)^v4)&mask;
    v4^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[42][index]);
#else
    mask=sigmaWalkNetwork131Masks[42][index];
#endif
    t=((v0 >> 4)^v0)&mask;
    v0^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[43][index]);
#else
    mask=sigmaWalkNetwork131Masks[43][index];
#endif
    t=((v1 >> 4)^v1)&mask;
    v1^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[44][index]);
#else
    mask=sigmaWalkNetwork131Masks[44][index];
#endif
    t=((v2 >> 4)^v2)&mask;
    v2^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[45][index]);
#else
    mask=sigmaWalkNetwork131Masks[45][index];
#endif
    t=((v3 >> 4)^v3)&mask;
    v3^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[14][index]);
#else
    mask=sigmaWalkNetwork131Masks[14][index];
#endif
    t=((v4 >> 4)^v4)&mask;
    v4^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[46][index]);
#else
    mask=sigmaWalkNetwork131Masks[46][index];
#endif
    t=((v0 >> 2)^v0)&mask;
    v0^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[47][index]);
#else
    mask=sigmaWalkNetwork131Masks[47][index];
#endif
    t=((v1 >> 2)^v1)&mask;
    v1^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[48][index]);
#else
    mask=sigmaWalkNetwork131Masks[48][index];
#endif
    t=((v2 >> 2)^v2)&mask;
    v2^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[49][index]);
#else
    mask=sigmaWalkNetwork131Masks[49][index];
#endif
    t=((v3 >> 2)^v3)&mask;
    v3^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[50][index]);
#else
    mask=sigmaWalkNetwork131Masks[50][index];
#endif
    t=((v4 >> 2)^v4)&mask;
    v4^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[51][index]);
#else
    mask=sigmaWalkNetwork131Masks[51][index];
#endif
    t=((v0 >> 1)^v0)&mask;
    v0^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[52][index]);
#else
    mask=sigmaWalkNetwork131Masks[52][index];
#endif
    t=((v1 >> 1)^v1)&mask;
    v1^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[53][index]);
#else
    mask=sigmaWalkNetwork131Masks[53][index];
#endif
    t=((v2 >> 1)^v2)&mask;
    v2^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[54][index]);
#else
    mask=sigmaWalkNetwork131Masks[54][index];
#endif
    t=((v3 >> 1)^v3)&mask;
    v3^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[55][index]);
#else
    mask=sigmaWalkNetwork131Masks[55][index];
#endif
    t=((v4 >> 1)^v4)&mask;
    v4^=t^(t << 1);
    return P131{{v0,v1,v2,v3,v4&7u}};
#endif
}
ECC_SIGMA_INV_STORAGE uint32_t sigmaInvNetwork131Masks[56][4] = {
    {0x15455000u,0x15400000u,0x15100440u,0x00000000u},
    {0x51454000u,0x01400000u,0x54141150u,0x00000000u},
    {0x51014045u,0x00001550u,0x55001400u,0x00000000u},
    {0x00015545u,0x05500550u,0x54054514u,0x00000000u},
    {0x00000004u,0x00000000u,0x00000000u,0x00000000u},
    {0x12211330u,0x31100000u,0x00012110u,0x00000000u},
    {0x33300200u,0x00022202u,0x21232223u,0x00000000u},
    {0x23330011u,0x11100020u,0x02313311u,0x00000000u},
    {0x02301312u,0x33303113u,0x31331213u,0x00000000u},
    {0x00000001u,0x00000003u,0x00000003u,0x00000000u},
    {0x0a080900u,0x050a0200u,0x02080200u,0x00000000u},
    {0x0b050e00u,0x0f0c0c0cu,0x0b0d0604u,0x00000000u},
    {0x0e0c0000u,0x0a0e0709u,0x00000209u,0x00000000u},
    {0x0b000003u,0x070e0901u,0x0a0e0d0du,0x00000000u},
    {0x00000006u,0x00000001u,0x00000008u,0x00000000u},
    {0x00410000u,0x00020000u,0x00570000u,0x00000000u},
    {0x007e009fu,0x00830084u,0x00bd0032u,0x00000000u},
    {0x00c1001bu,0x00c20088u,0x002900cdu,0x00000000u},
    {0x00d500dbu,0x008c00bdu,0x00020055u,0x00000000u},
    {0x00000008u,0x0000001cu,0x00000005u,0x00000000u},
    {0x00003456u,0x0000080au,0x00000240u,0x00000000u},
    {0x000060b8u,0x00004022u,0x00000364u,0x00000000u},
    {0x0000b674u,0x00005c27u,0x0000b100u,0x00000000u},
    {0x00000840u,0x00001c00u,0x00000400u,0x00000000u},
    {0x07094244u,0x1300b31du,0x59e29161u,0x00000000u},
    {0x08400000u,0x10000000u,0x04000080u,0x00000000u},
    {0x00000000u,0x04000000u,0x00000000u,0x00000000u},
    {0x00400000u,0x00000000u,0x00000080u,0x00000000u},
    {0x00000020u,0x08000000u,0x00000100u,0x00000000u},
    {0x08000000u,0x10000000u,0x04000000u,0x00000000u},
    {0xc3e4641eu,0xd0e43c1eu,0x9c711bb6u,0x00000000u},
    {0xcc5bba43u,0xe342cbc1u,0xe39288d5u,0x00000000u},
    {0x15c7ea33u,0xfa23072fu,0xeed5500bu,0x00000000u},
    {0x72c87aa7u,0x1b8f0f2du,0x35eb45cfu,0x00000000u},
    {0x00002ae7u,0x0000896cu,0x0000a5a9u,0x00000000u},
    {0x00000a3fu,0x0000e678u,0x000099e7u,0x00000000u},
    {0x000017e1u,0x000092d4u,0x00002715u,0x00000000u},
    {0x00008a5cu,0x000079c8u,0x000070a8u,0x00000000u},
    {0x008900e7u,0x00d90091u,0x00f90067u,0x00000000u},
    {0x00e800afu,0x00be00acu,0x004800d9u,0x00000000u},
    {0x007f0035u,0x009f00ccu,0x00a40002u,0x00000000u},
    {0x008000c1u,0x007b00f0u,0x00cc0043u,0x00000000u},
    {0x0704060du,0x0f090908u,0x0c0c0c0fu,0x00000000u},
    {0x0b0a0009u,0x07040806u,0x0e0d070fu,0x00000000u},
    {0x0d0f0e03u,0x080d0d09u,0x0d0e0f06u,0x00000000u},
    {0x0e000408u,0x080f0707u,0x08040b09u,0x00000000u},
    {0x13110320u,0x21222212u,0x21300031u,0x00000000u},
    {0x11322211u,0x02013132u,0x02131130u,0x00000000u},
    {0x13313311u,0x23111002u,0x22230233u,0x00000000u},
    {0x12102021u,0x13222011u,0x22131033u,0x00000000u},
    {0x00000001u,0x00000003u,0x00000002u,0x00000000u},
    {0x54150401u,0x50544151u,0x15055411u,0x00000000u},
    {0x00004010u,0x14445111u,0x00110554u,0x00000000u},
    {0x00015455u,0x04441110u,0x55154154u,0x00000000u},
    {0x55554400u,0x44451115u,0x10000045u,0x00000000u},
    {0x00000005u,0x00000001u,0x00000000u,0x00000000u},
};
static ECC_BIG P131 sigmaInvNetwork131(P131 a, int index) {
#if defined(__CUDACC__) && !defined(__CUDA_ARCH__)
    const int exponents[] = {16,32,65};
    for (int i=0;i<exponents[index];i++) a=sqr131(a);
    return a;
#else
    uint32_t v0=a.v[0], v1=a.v[1], v2=a.v[2], v3=a.v[3], v4=a.v[4];
    uint32_t v5=0, v6=0, v7=0, t, mask;
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[0][index];
#else
    mask=sigmaInvNetwork131Masks[0][index];
#endif
    t=((v0 >> 1)^v0)&mask;
    v0^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[1][index];
#else
    mask=sigmaInvNetwork131Masks[1][index];
#endif
    t=((v1 >> 1)^v1)&mask;
    v1^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[2][index];
#else
    mask=sigmaInvNetwork131Masks[2][index];
#endif
    t=((v2 >> 1)^v2)&mask;
    v2^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[3][index];
#else
    mask=sigmaInvNetwork131Masks[3][index];
#endif
    t=((v3 >> 1)^v3)&mask;
    v3^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[4][index];
#else
    mask=sigmaInvNetwork131Masks[4][index];
#endif
    t=((v4 >> 1)^v4)&mask;
    v4^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[5][index];
#else
    mask=sigmaInvNetwork131Masks[5][index];
#endif
    t=((v0 >> 2)^v0)&mask;
    v0^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[6][index];
#else
    mask=sigmaInvNetwork131Masks[6][index];
#endif
    t=((v1 >> 2)^v1)&mask;
    v1^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[7][index];
#else
    mask=sigmaInvNetwork131Masks[7][index];
#endif
    t=((v2 >> 2)^v2)&mask;
    v2^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[8][index];
#else
    mask=sigmaInvNetwork131Masks[8][index];
#endif
    t=((v3 >> 2)^v3)&mask;
    v3^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[9][index];
#else
    mask=sigmaInvNetwork131Masks[9][index];
#endif
    t=((v4 >> 2)^v4)&mask;
    v4^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[10][index];
#else
    mask=sigmaInvNetwork131Masks[10][index];
#endif
    t=((v0 >> 4)^v0)&mask;
    v0^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[11][index];
#else
    mask=sigmaInvNetwork131Masks[11][index];
#endif
    t=((v1 >> 4)^v1)&mask;
    v1^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[12][index];
#else
    mask=sigmaInvNetwork131Masks[12][index];
#endif
    t=((v2 >> 4)^v2)&mask;
    v2^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[13][index];
#else
    mask=sigmaInvNetwork131Masks[13][index];
#endif
    t=((v3 >> 4)^v3)&mask;
    v3^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[14][index];
#else
    mask=sigmaInvNetwork131Masks[14][index];
#endif
    t=((v4 >> 4)^v4)&mask;
    v4^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[15][index];
#else
    mask=sigmaInvNetwork131Masks[15][index];
#endif
    t=((v0 >> 8)^v0)&mask;
    v0^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[16][index];
#else
    mask=sigmaInvNetwork131Masks[16][index];
#endif
    t=((v1 >> 8)^v1)&mask;
    v1^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[17][index];
#else
    mask=sigmaInvNetwork131Masks[17][index];
#endif
    t=((v2 >> 8)^v2)&mask;
    v2^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[18][index];
#else
    mask=sigmaInvNetwork131Masks[18][index];
#endif
    t=((v3 >> 8)^v3)&mask;
    v3^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[19][index];
#else
    mask=sigmaInvNetwork131Masks[19][index];
#endif
    t=((v4 >> 8)^v4)&mask;
    v4^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[20][index];
#else
    mask=sigmaInvNetwork131Masks[20][index];
#endif
    t=((v1 >> 16)^v1)&mask;
    v1^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[21][index];
#else
    mask=sigmaInvNetwork131Masks[21][index];
#endif
    t=((v2 >> 16)^v2)&mask;
    v2^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[22][index];
#else
    mask=sigmaInvNetwork131Masks[22][index];
#endif
    t=((v3 >> 16)^v3)&mask;
    v3^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[23][index];
#else
    mask=sigmaInvNetwork131Masks[23][index];
#endif
    t=((v4 >> 16)^v4)&mask;
    v4^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[24][index];
#else
    mask=sigmaInvNetwork131Masks[24][index];
#endif
    t=(v2^v3)&mask;
    v2^=t; v3^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[25][index];
#else
    mask=sigmaInvNetwork131Masks[25][index];
#endif
    t=(v4^v5)&mask;
    v4^=t; v5^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[26][index];
#else
    mask=sigmaInvNetwork131Masks[26][index];
#endif
    t=(v4^v6)&mask;
    v4^=t; v6^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[27][index];
#else
    mask=sigmaInvNetwork131Masks[27][index];
#endif
    t=(v5^v7)&mask;
    v5^=t; v7^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[28][index];
#else
    mask=sigmaInvNetwork131Masks[28][index];
#endif
    t=(v0^v4)&mask;
    v0^=t; v4^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[29][index];
#else
    mask=sigmaInvNetwork131Masks[29][index];
#endif
    t=(v1^v5)&mask;
    v1^=t; v5^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[26][index];
#else
    mask=sigmaInvNetwork131Masks[26][index];
#endif
    t=(v2^v6)&mask;
    v2^=t; v6^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[27][index];
#else
    mask=sigmaInvNetwork131Masks[27][index];
#endif
    t=(v3^v7)&mask;
    v3^=t; v7^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[30][index];
#else
    mask=sigmaInvNetwork131Masks[30][index];
#endif
    t=(v0^v2)&mask;
    v0^=t; v2^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[31][index];
#else
    mask=sigmaInvNetwork131Masks[31][index];
#endif
    t=(v1^v3)&mask;
    v1^=t; v3^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[26][index];
#else
    mask=sigmaInvNetwork131Masks[26][index];
#endif
    t=(v4^v6)&mask;
    v4^=t; v6^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[27][index];
#else
    mask=sigmaInvNetwork131Masks[27][index];
#endif
    t=(v5^v7)&mask;
    v5^=t; v7^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[32][index];
#else
    mask=sigmaInvNetwork131Masks[32][index];
#endif
    t=(v0^v1)&mask;
    v0^=t; v1^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[33][index];
#else
    mask=sigmaInvNetwork131Masks[33][index];
#endif
    t=(v2^v3)&mask;
    v2^=t; v3^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[25][index];
#else
    mask=sigmaInvNetwork131Masks[25][index];
#endif
    t=(v4^v5)&mask;
    v4^=t; v5^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[34][index];
#else
    mask=sigmaInvNetwork131Masks[34][index];
#endif
    t=((v0 >> 16)^v0)&mask;
    v0^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[35][index];
#else
    mask=sigmaInvNetwork131Masks[35][index];
#endif
    t=((v1 >> 16)^v1)&mask;
    v1^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[36][index];
#else
    mask=sigmaInvNetwork131Masks[36][index];
#endif
    t=((v2 >> 16)^v2)&mask;
    v2^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[37][index];
#else
    mask=sigmaInvNetwork131Masks[37][index];
#endif
    t=((v3 >> 16)^v3)&mask;
    v3^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[23][index];
#else
    mask=sigmaInvNetwork131Masks[23][index];
#endif
    t=((v4 >> 16)^v4)&mask;
    v4^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[38][index];
#else
    mask=sigmaInvNetwork131Masks[38][index];
#endif
    t=((v0 >> 8)^v0)&mask;
    v0^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[39][index];
#else
    mask=sigmaInvNetwork131Masks[39][index];
#endif
    t=((v1 >> 8)^v1)&mask;
    v1^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[40][index];
#else
    mask=sigmaInvNetwork131Masks[40][index];
#endif
    t=((v2 >> 8)^v2)&mask;
    v2^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[41][index];
#else
    mask=sigmaInvNetwork131Masks[41][index];
#endif
    t=((v3 >> 8)^v3)&mask;
    v3^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[19][index];
#else
    mask=sigmaInvNetwork131Masks[19][index];
#endif
    t=((v4 >> 8)^v4)&mask;
    v4^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[42][index];
#else
    mask=sigmaInvNetwork131Masks[42][index];
#endif
    t=((v0 >> 4)^v0)&mask;
    v0^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[43][index];
#else
    mask=sigmaInvNetwork131Masks[43][index];
#endif
    t=((v1 >> 4)^v1)&mask;
    v1^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[44][index];
#else
    mask=sigmaInvNetwork131Masks[44][index];
#endif
    t=((v2 >> 4)^v2)&mask;
    v2^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[45][index];
#else
    mask=sigmaInvNetwork131Masks[45][index];
#endif
    t=((v3 >> 4)^v3)&mask;
    v3^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[14][index];
#else
    mask=sigmaInvNetwork131Masks[14][index];
#endif
    t=((v4 >> 4)^v4)&mask;
    v4^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[46][index];
#else
    mask=sigmaInvNetwork131Masks[46][index];
#endif
    t=((v0 >> 2)^v0)&mask;
    v0^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[47][index];
#else
    mask=sigmaInvNetwork131Masks[47][index];
#endif
    t=((v1 >> 2)^v1)&mask;
    v1^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[48][index];
#else
    mask=sigmaInvNetwork131Masks[48][index];
#endif
    t=((v2 >> 2)^v2)&mask;
    v2^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[49][index];
#else
    mask=sigmaInvNetwork131Masks[49][index];
#endif
    t=((v3 >> 2)^v3)&mask;
    v3^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[50][index];
#else
    mask=sigmaInvNetwork131Masks[50][index];
#endif
    t=((v4 >> 2)^v4)&mask;
    v4^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[51][index];
#else
    mask=sigmaInvNetwork131Masks[51][index];
#endif
    t=((v0 >> 1)^v0)&mask;
    v0^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[52][index];
#else
    mask=sigmaInvNetwork131Masks[52][index];
#endif
    t=((v1 >> 1)^v1)&mask;
    v1^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[53][index];
#else
    mask=sigmaInvNetwork131Masks[53][index];
#endif
    t=((v2 >> 1)^v2)&mask;
    v2^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[54][index];
#else
    mask=sigmaInvNetwork131Masks[54][index];
#endif
    t=((v3 >> 1)^v3)&mask;
    v3^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=sigmaInvNetwork131Masks[55][index];
#else
    mask=sigmaInvNetwork131Masks[55][index];
#endif
    t=((v4 >> 1)^v4)&mask;
    v4^=t^(t << 1);
    return P131{{v0,v1,v2,v3,v4&7u}};
#endif
}
#if ECC_PACKED_WEIGHTED_PREFIX == 2
struct SigmaWalkPair131 { P131 first, second; };
static ECC_BIG SigmaWalkPair131 sigmaWalkNetworkPair131(P131 a, P131 b, int index) {
#if defined(__CUDACC__) && !defined(__CUDA_ARCH__)
    const int exponents[] = {3,4,5,6,7,8,9,10};
    for (int i=0;i<exponents[index];i++) { a=sqr131(a); b=sqr131(b); }
    return SigmaWalkPair131{a,b};
#else
    uint32_t a0=a.v[0], a1=a.v[1], a2=a.v[2], a3=a.v[3], a4=a.v[4];
    uint32_t b0=b.v[0], b1=b.v[1], b2=b.v[2], b3=b.v[3], b4=b.v[4];
    uint32_t a5=0, a6=0, a7=0, b5=0, b6=0, b7=0, t, mask;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[0][index]);
#else
    mask=sigmaWalkNetwork131Masks[0][index];
#endif
    t=((a0 >> 1)^a0)&mask;
    a0^=t^(t << 1);
    t=((b0 >> 1)^b0)&mask;
    b0^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[1][index]);
#else
    mask=sigmaWalkNetwork131Masks[1][index];
#endif
    t=((a1 >> 1)^a1)&mask;
    a1^=t^(t << 1);
    t=((b1 >> 1)^b1)&mask;
    b1^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[2][index]);
#else
    mask=sigmaWalkNetwork131Masks[2][index];
#endif
    t=((a2 >> 1)^a2)&mask;
    a2^=t^(t << 1);
    t=((b2 >> 1)^b2)&mask;
    b2^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[3][index]);
#else
    mask=sigmaWalkNetwork131Masks[3][index];
#endif
    t=((a3 >> 1)^a3)&mask;
    a3^=t^(t << 1);
    t=((b3 >> 1)^b3)&mask;
    b3^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[4][index]);
#else
    mask=sigmaWalkNetwork131Masks[4][index];
#endif
    t=((a4 >> 1)^a4)&mask;
    a4^=t^(t << 1);
    t=((b4 >> 1)^b4)&mask;
    b4^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[5][index]);
#else
    mask=sigmaWalkNetwork131Masks[5][index];
#endif
    t=((a0 >> 2)^a0)&mask;
    a0^=t^(t << 2);
    t=((b0 >> 2)^b0)&mask;
    b0^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[6][index]);
#else
    mask=sigmaWalkNetwork131Masks[6][index];
#endif
    t=((a1 >> 2)^a1)&mask;
    a1^=t^(t << 2);
    t=((b1 >> 2)^b1)&mask;
    b1^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[7][index]);
#else
    mask=sigmaWalkNetwork131Masks[7][index];
#endif
    t=((a2 >> 2)^a2)&mask;
    a2^=t^(t << 2);
    t=((b2 >> 2)^b2)&mask;
    b2^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[8][index]);
#else
    mask=sigmaWalkNetwork131Masks[8][index];
#endif
    t=((a3 >> 2)^a3)&mask;
    a3^=t^(t << 2);
    t=((b3 >> 2)^b3)&mask;
    b3^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[9][index]);
#else
    mask=sigmaWalkNetwork131Masks[9][index];
#endif
    t=((a4 >> 2)^a4)&mask;
    a4^=t^(t << 2);
    t=((b4 >> 2)^b4)&mask;
    b4^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[10][index]);
#else
    mask=sigmaWalkNetwork131Masks[10][index];
#endif
    t=((a0 >> 4)^a0)&mask;
    a0^=t^(t << 4);
    t=((b0 >> 4)^b0)&mask;
    b0^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[11][index]);
#else
    mask=sigmaWalkNetwork131Masks[11][index];
#endif
    t=((a1 >> 4)^a1)&mask;
    a1^=t^(t << 4);
    t=((b1 >> 4)^b1)&mask;
    b1^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[12][index]);
#else
    mask=sigmaWalkNetwork131Masks[12][index];
#endif
    t=((a2 >> 4)^a2)&mask;
    a2^=t^(t << 4);
    t=((b2 >> 4)^b2)&mask;
    b2^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[13][index]);
#else
    mask=sigmaWalkNetwork131Masks[13][index];
#endif
    t=((a3 >> 4)^a3)&mask;
    a3^=t^(t << 4);
    t=((b3 >> 4)^b3)&mask;
    b3^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[14][index]);
#else
    mask=sigmaWalkNetwork131Masks[14][index];
#endif
    t=((a4 >> 4)^a4)&mask;
    a4^=t^(t << 4);
    t=((b4 >> 4)^b4)&mask;
    b4^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[15][index]);
#else
    mask=sigmaWalkNetwork131Masks[15][index];
#endif
    t=((a0 >> 8)^a0)&mask;
    a0^=t^(t << 8);
    t=((b0 >> 8)^b0)&mask;
    b0^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[16][index]);
#else
    mask=sigmaWalkNetwork131Masks[16][index];
#endif
    t=((a1 >> 8)^a1)&mask;
    a1^=t^(t << 8);
    t=((b1 >> 8)^b1)&mask;
    b1^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[17][index]);
#else
    mask=sigmaWalkNetwork131Masks[17][index];
#endif
    t=((a2 >> 8)^a2)&mask;
    a2^=t^(t << 8);
    t=((b2 >> 8)^b2)&mask;
    b2^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[18][index]);
#else
    mask=sigmaWalkNetwork131Masks[18][index];
#endif
    t=((a3 >> 8)^a3)&mask;
    a3^=t^(t << 8);
    t=((b3 >> 8)^b3)&mask;
    b3^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[19][index]);
#else
    mask=sigmaWalkNetwork131Masks[19][index];
#endif
    t=((a4 >> 8)^a4)&mask;
    a4^=t^(t << 8);
    t=((b4 >> 8)^b4)&mask;
    b4^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[20][index]);
#else
    mask=sigmaWalkNetwork131Masks[20][index];
#endif
    t=((a1 >> 16)^a1)&mask;
    a1^=t^(t << 16);
    t=((b1 >> 16)^b1)&mask;
    b1^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[21][index]);
#else
    mask=sigmaWalkNetwork131Masks[21][index];
#endif
    t=((a2 >> 16)^a2)&mask;
    a2^=t^(t << 16);
    t=((b2 >> 16)^b2)&mask;
    b2^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[22][index]);
#else
    mask=sigmaWalkNetwork131Masks[22][index];
#endif
    t=((a3 >> 16)^a3)&mask;
    a3^=t^(t << 16);
    t=((b3 >> 16)^b3)&mask;
    b3^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[23][index]);
#else
    mask=sigmaWalkNetwork131Masks[23][index];
#endif
    t=((a4 >> 16)^a4)&mask;
    a4^=t^(t << 16);
    t=((b4 >> 16)^b4)&mask;
    b4^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[24][index]);
#else
    mask=sigmaWalkNetwork131Masks[24][index];
#endif
    t=(a2^a3)&mask;
    a2^=t; a3^=t;
    t=(b2^b3)&mask;
    b2^=t; b3^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[25][index]);
#else
    mask=sigmaWalkNetwork131Masks[25][index];
#endif
    t=(a4^a5)&mask;
    a4^=t; a5^=t;
    t=(b4^b5)&mask;
    b4^=t; b5^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[26][index]);
#else
    mask=sigmaWalkNetwork131Masks[26][index];
#endif
    t=(a4^a6)&mask;
    a4^=t; a6^=t;
    t=(b4^b6)&mask;
    b4^=t; b6^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[27][index]);
#else
    mask=sigmaWalkNetwork131Masks[27][index];
#endif
    t=(a5^a7)&mask;
    a5^=t; a7^=t;
    t=(b5^b7)&mask;
    b5^=t; b7^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[28][index]);
#else
    mask=sigmaWalkNetwork131Masks[28][index];
#endif
    t=(a0^a4)&mask;
    a0^=t; a4^=t;
    t=(b0^b4)&mask;
    b0^=t; b4^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[29][index]);
#else
    mask=sigmaWalkNetwork131Masks[29][index];
#endif
    t=(a1^a5)&mask;
    a1^=t; a5^=t;
    t=(b1^b5)&mask;
    b1^=t; b5^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[26][index]);
#else
    mask=sigmaWalkNetwork131Masks[26][index];
#endif
    t=(a2^a6)&mask;
    a2^=t; a6^=t;
    t=(b2^b6)&mask;
    b2^=t; b6^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[27][index]);
#else
    mask=sigmaWalkNetwork131Masks[27][index];
#endif
    t=(a3^a7)&mask;
    a3^=t; a7^=t;
    t=(b3^b7)&mask;
    b3^=t; b7^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[30][index]);
#else
    mask=sigmaWalkNetwork131Masks[30][index];
#endif
    t=(a0^a2)&mask;
    a0^=t; a2^=t;
    t=(b0^b2)&mask;
    b0^=t; b2^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[31][index]);
#else
    mask=sigmaWalkNetwork131Masks[31][index];
#endif
    t=(a1^a3)&mask;
    a1^=t; a3^=t;
    t=(b1^b3)&mask;
    b1^=t; b3^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[26][index]);
#else
    mask=sigmaWalkNetwork131Masks[26][index];
#endif
    t=(a4^a6)&mask;
    a4^=t; a6^=t;
    t=(b4^b6)&mask;
    b4^=t; b6^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[27][index]);
#else
    mask=sigmaWalkNetwork131Masks[27][index];
#endif
    t=(a5^a7)&mask;
    a5^=t; a7^=t;
    t=(b5^b7)&mask;
    b5^=t; b7^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[32][index]);
#else
    mask=sigmaWalkNetwork131Masks[32][index];
#endif
    t=(a0^a1)&mask;
    a0^=t; a1^=t;
    t=(b0^b1)&mask;
    b0^=t; b1^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[33][index]);
#else
    mask=sigmaWalkNetwork131Masks[33][index];
#endif
    t=(a2^a3)&mask;
    a2^=t; a3^=t;
    t=(b2^b3)&mask;
    b2^=t; b3^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[25][index]);
#else
    mask=sigmaWalkNetwork131Masks[25][index];
#endif
    t=(a4^a5)&mask;
    a4^=t; a5^=t;
    t=(b4^b5)&mask;
    b4^=t; b5^=t;
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[34][index]);
#else
    mask=sigmaWalkNetwork131Masks[34][index];
#endif
    t=((a0 >> 16)^a0)&mask;
    a0^=t^(t << 16);
    t=((b0 >> 16)^b0)&mask;
    b0^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[35][index]);
#else
    mask=sigmaWalkNetwork131Masks[35][index];
#endif
    t=((a1 >> 16)^a1)&mask;
    a1^=t^(t << 16);
    t=((b1 >> 16)^b1)&mask;
    b1^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[36][index]);
#else
    mask=sigmaWalkNetwork131Masks[36][index];
#endif
    t=((a2 >> 16)^a2)&mask;
    a2^=t^(t << 16);
    t=((b2 >> 16)^b2)&mask;
    b2^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[37][index]);
#else
    mask=sigmaWalkNetwork131Masks[37][index];
#endif
    t=((a3 >> 16)^a3)&mask;
    a3^=t^(t << 16);
    t=((b3 >> 16)^b3)&mask;
    b3^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[23][index]);
#else
    mask=sigmaWalkNetwork131Masks[23][index];
#endif
    t=((a4 >> 16)^a4)&mask;
    a4^=t^(t << 16);
    t=((b4 >> 16)^b4)&mask;
    b4^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[38][index]);
#else
    mask=sigmaWalkNetwork131Masks[38][index];
#endif
    t=((a0 >> 8)^a0)&mask;
    a0^=t^(t << 8);
    t=((b0 >> 8)^b0)&mask;
    b0^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[39][index]);
#else
    mask=sigmaWalkNetwork131Masks[39][index];
#endif
    t=((a1 >> 8)^a1)&mask;
    a1^=t^(t << 8);
    t=((b1 >> 8)^b1)&mask;
    b1^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[40][index]);
#else
    mask=sigmaWalkNetwork131Masks[40][index];
#endif
    t=((a2 >> 8)^a2)&mask;
    a2^=t^(t << 8);
    t=((b2 >> 8)^b2)&mask;
    b2^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[41][index]);
#else
    mask=sigmaWalkNetwork131Masks[41][index];
#endif
    t=((a3 >> 8)^a3)&mask;
    a3^=t^(t << 8);
    t=((b3 >> 8)^b3)&mask;
    b3^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[19][index]);
#else
    mask=sigmaWalkNetwork131Masks[19][index];
#endif
    t=((a4 >> 8)^a4)&mask;
    a4^=t^(t << 8);
    t=((b4 >> 8)^b4)&mask;
    b4^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[42][index]);
#else
    mask=sigmaWalkNetwork131Masks[42][index];
#endif
    t=((a0 >> 4)^a0)&mask;
    a0^=t^(t << 4);
    t=((b0 >> 4)^b0)&mask;
    b0^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[43][index]);
#else
    mask=sigmaWalkNetwork131Masks[43][index];
#endif
    t=((a1 >> 4)^a1)&mask;
    a1^=t^(t << 4);
    t=((b1 >> 4)^b1)&mask;
    b1^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[44][index]);
#else
    mask=sigmaWalkNetwork131Masks[44][index];
#endif
    t=((a2 >> 4)^a2)&mask;
    a2^=t^(t << 4);
    t=((b2 >> 4)^b2)&mask;
    b2^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[45][index]);
#else
    mask=sigmaWalkNetwork131Masks[45][index];
#endif
    t=((a3 >> 4)^a3)&mask;
    a3^=t^(t << 4);
    t=((b3 >> 4)^b3)&mask;
    b3^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[14][index]);
#else
    mask=sigmaWalkNetwork131Masks[14][index];
#endif
    t=((a4 >> 4)^a4)&mask;
    a4^=t^(t << 4);
    t=((b4 >> 4)^b4)&mask;
    b4^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[46][index]);
#else
    mask=sigmaWalkNetwork131Masks[46][index];
#endif
    t=((a0 >> 2)^a0)&mask;
    a0^=t^(t << 2);
    t=((b0 >> 2)^b0)&mask;
    b0^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[47][index]);
#else
    mask=sigmaWalkNetwork131Masks[47][index];
#endif
    t=((a1 >> 2)^a1)&mask;
    a1^=t^(t << 2);
    t=((b1 >> 2)^b1)&mask;
    b1^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[48][index]);
#else
    mask=sigmaWalkNetwork131Masks[48][index];
#endif
    t=((a2 >> 2)^a2)&mask;
    a2^=t^(t << 2);
    t=((b2 >> 2)^b2)&mask;
    b2^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[49][index]);
#else
    mask=sigmaWalkNetwork131Masks[49][index];
#endif
    t=((a3 >> 2)^a3)&mask;
    a3^=t^(t << 2);
    t=((b3 >> 2)^b3)&mask;
    b3^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[50][index]);
#else
    mask=sigmaWalkNetwork131Masks[50][index];
#endif
    t=((a4 >> 2)^a4)&mask;
    a4^=t^(t << 2);
    t=((b4 >> 2)^b4)&mask;
    b4^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[51][index]);
#else
    mask=sigmaWalkNetwork131Masks[51][index];
#endif
    t=((a0 >> 1)^a0)&mask;
    a0^=t^(t << 1);
    t=((b0 >> 1)^b0)&mask;
    b0^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[52][index]);
#else
    mask=sigmaWalkNetwork131Masks[52][index];
#endif
    t=((a1 >> 1)^a1)&mask;
    a1^=t^(t << 1);
    t=((b1 >> 1)^b1)&mask;
    b1^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[53][index]);
#else
    mask=sigmaWalkNetwork131Masks[53][index];
#endif
    t=((a2 >> 1)^a2)&mask;
    a2^=t^(t << 1);
    t=((b2 >> 1)^b2)&mask;
    b2^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[54][index]);
#else
    mask=sigmaWalkNetwork131Masks[54][index];
#endif
    t=((a3 >> 1)^a3)&mask;
    a3^=t^(t << 1);
    t=((b3 >> 1)^b3)&mask;
    b3^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=__ldg(&sigmaWalkNetwork131Masks[55][index]);
#else
    mask=sigmaWalkNetwork131Masks[55][index];
#endif
    t=((a4 >> 1)^a4)&mask;
    a4^=t^(t << 1);
    t=((b4 >> 1)^b4)&mask;
    b4^=t^(t << 1);
    return SigmaWalkPair131{P131{{a0,a1,a2,a3,a4&7u}},P131{{b0,b1,b2,b3,b4&7u}}};
#endif
}
#endif
#if ECC_PACKED_SHARED_SIGMA
#ifdef __CUDACC__
static __shared__ uint32_t sigmaWalkShared131Masks[56][8];
#endif
static ECC_HD void initSigmaWalkShared131() {
#ifdef __CUDA_ARCH__
    for (unsigned i=threadIdx.x; i<448u; i+=blockDim.x)
        sigmaWalkShared131Masks[i/8][i%8]=__ldg(&sigmaWalkNetwork131Masks[i/8][i%8]);
    __syncthreads();
#endif
}
// Host code emulates the post-barrier values through the original
// immutable table; it does not emulate CUDA block concurrency.
#if ECC_PACKED_INLINE_SIGMA
static ECC_HD SigmaWalkPair131 sigmaWalkNetworkPairShared131(P131 a, P131 b, int index) {
#else
static ECC_BIG SigmaWalkPair131 sigmaWalkNetworkPairShared131(P131 a, P131 b, int index) {
#endif
#if defined(__CUDACC__) && !defined(__CUDA_ARCH__)
    const int exponents[] = {3,4,5,6,7,8,9,10};
    for (int i=0;i<exponents[index];i++) { a=sqr131(a); b=sqr131(b); }
    return SigmaWalkPair131{a,b};
#else
    uint32_t a0=a.v[0], a1=a.v[1], a2=a.v[2], a3=a.v[3], a4=a.v[4];
    uint32_t b0=b.v[0], b1=b.v[1], b2=b.v[2], b3=b.v[3], b4=b.v[4];
    uint32_t a5=0, a6=0, a7=0, b5=0, b6=0, b7=0, t, mask;
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[0][index];
#else
    mask=sigmaWalkNetwork131Masks[0][index];
#endif
    t=((a0 >> 1)^a0)&mask;
    a0^=t^(t << 1);
    t=((b0 >> 1)^b0)&mask;
    b0^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[1][index];
#else
    mask=sigmaWalkNetwork131Masks[1][index];
#endif
    t=((a1 >> 1)^a1)&mask;
    a1^=t^(t << 1);
    t=((b1 >> 1)^b1)&mask;
    b1^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[2][index];
#else
    mask=sigmaWalkNetwork131Masks[2][index];
#endif
    t=((a2 >> 1)^a2)&mask;
    a2^=t^(t << 1);
    t=((b2 >> 1)^b2)&mask;
    b2^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[3][index];
#else
    mask=sigmaWalkNetwork131Masks[3][index];
#endif
    t=((a3 >> 1)^a3)&mask;
    a3^=t^(t << 1);
    t=((b3 >> 1)^b3)&mask;
    b3^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[4][index];
#else
    mask=sigmaWalkNetwork131Masks[4][index];
#endif
    t=((a4 >> 1)^a4)&mask;
    a4^=t^(t << 1);
    t=((b4 >> 1)^b4)&mask;
    b4^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[5][index];
#else
    mask=sigmaWalkNetwork131Masks[5][index];
#endif
    t=((a0 >> 2)^a0)&mask;
    a0^=t^(t << 2);
    t=((b0 >> 2)^b0)&mask;
    b0^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[6][index];
#else
    mask=sigmaWalkNetwork131Masks[6][index];
#endif
    t=((a1 >> 2)^a1)&mask;
    a1^=t^(t << 2);
    t=((b1 >> 2)^b1)&mask;
    b1^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[7][index];
#else
    mask=sigmaWalkNetwork131Masks[7][index];
#endif
    t=((a2 >> 2)^a2)&mask;
    a2^=t^(t << 2);
    t=((b2 >> 2)^b2)&mask;
    b2^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[8][index];
#else
    mask=sigmaWalkNetwork131Masks[8][index];
#endif
    t=((a3 >> 2)^a3)&mask;
    a3^=t^(t << 2);
    t=((b3 >> 2)^b3)&mask;
    b3^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[9][index];
#else
    mask=sigmaWalkNetwork131Masks[9][index];
#endif
    t=((a4 >> 2)^a4)&mask;
    a4^=t^(t << 2);
    t=((b4 >> 2)^b4)&mask;
    b4^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[10][index];
#else
    mask=sigmaWalkNetwork131Masks[10][index];
#endif
    t=((a0 >> 4)^a0)&mask;
    a0^=t^(t << 4);
    t=((b0 >> 4)^b0)&mask;
    b0^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[11][index];
#else
    mask=sigmaWalkNetwork131Masks[11][index];
#endif
    t=((a1 >> 4)^a1)&mask;
    a1^=t^(t << 4);
    t=((b1 >> 4)^b1)&mask;
    b1^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[12][index];
#else
    mask=sigmaWalkNetwork131Masks[12][index];
#endif
    t=((a2 >> 4)^a2)&mask;
    a2^=t^(t << 4);
    t=((b2 >> 4)^b2)&mask;
    b2^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[13][index];
#else
    mask=sigmaWalkNetwork131Masks[13][index];
#endif
    t=((a3 >> 4)^a3)&mask;
    a3^=t^(t << 4);
    t=((b3 >> 4)^b3)&mask;
    b3^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[14][index];
#else
    mask=sigmaWalkNetwork131Masks[14][index];
#endif
    t=((a4 >> 4)^a4)&mask;
    a4^=t^(t << 4);
    t=((b4 >> 4)^b4)&mask;
    b4^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[15][index];
#else
    mask=sigmaWalkNetwork131Masks[15][index];
#endif
    t=((a0 >> 8)^a0)&mask;
    a0^=t^(t << 8);
    t=((b0 >> 8)^b0)&mask;
    b0^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[16][index];
#else
    mask=sigmaWalkNetwork131Masks[16][index];
#endif
    t=((a1 >> 8)^a1)&mask;
    a1^=t^(t << 8);
    t=((b1 >> 8)^b1)&mask;
    b1^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[17][index];
#else
    mask=sigmaWalkNetwork131Masks[17][index];
#endif
    t=((a2 >> 8)^a2)&mask;
    a2^=t^(t << 8);
    t=((b2 >> 8)^b2)&mask;
    b2^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[18][index];
#else
    mask=sigmaWalkNetwork131Masks[18][index];
#endif
    t=((a3 >> 8)^a3)&mask;
    a3^=t^(t << 8);
    t=((b3 >> 8)^b3)&mask;
    b3^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[19][index];
#else
    mask=sigmaWalkNetwork131Masks[19][index];
#endif
    t=((a4 >> 8)^a4)&mask;
    a4^=t^(t << 8);
    t=((b4 >> 8)^b4)&mask;
    b4^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[20][index];
#else
    mask=sigmaWalkNetwork131Masks[20][index];
#endif
    t=((a1 >> 16)^a1)&mask;
    a1^=t^(t << 16);
    t=((b1 >> 16)^b1)&mask;
    b1^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[21][index];
#else
    mask=sigmaWalkNetwork131Masks[21][index];
#endif
    t=((a2 >> 16)^a2)&mask;
    a2^=t^(t << 16);
    t=((b2 >> 16)^b2)&mask;
    b2^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[22][index];
#else
    mask=sigmaWalkNetwork131Masks[22][index];
#endif
    t=((a3 >> 16)^a3)&mask;
    a3^=t^(t << 16);
    t=((b3 >> 16)^b3)&mask;
    b3^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[23][index];
#else
    mask=sigmaWalkNetwork131Masks[23][index];
#endif
    t=((a4 >> 16)^a4)&mask;
    a4^=t^(t << 16);
    t=((b4 >> 16)^b4)&mask;
    b4^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[24][index];
#else
    mask=sigmaWalkNetwork131Masks[24][index];
#endif
    t=(a2^a3)&mask;
    a2^=t; a3^=t;
    t=(b2^b3)&mask;
    b2^=t; b3^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[25][index];
#else
    mask=sigmaWalkNetwork131Masks[25][index];
#endif
    t=(a4^a5)&mask;
    a4^=t; a5^=t;
    t=(b4^b5)&mask;
    b4^=t; b5^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[26][index];
#else
    mask=sigmaWalkNetwork131Masks[26][index];
#endif
    t=(a4^a6)&mask;
    a4^=t; a6^=t;
    t=(b4^b6)&mask;
    b4^=t; b6^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[27][index];
#else
    mask=sigmaWalkNetwork131Masks[27][index];
#endif
    t=(a5^a7)&mask;
    a5^=t; a7^=t;
    t=(b5^b7)&mask;
    b5^=t; b7^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[28][index];
#else
    mask=sigmaWalkNetwork131Masks[28][index];
#endif
    t=(a0^a4)&mask;
    a0^=t; a4^=t;
    t=(b0^b4)&mask;
    b0^=t; b4^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[29][index];
#else
    mask=sigmaWalkNetwork131Masks[29][index];
#endif
    t=(a1^a5)&mask;
    a1^=t; a5^=t;
    t=(b1^b5)&mask;
    b1^=t; b5^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[26][index];
#else
    mask=sigmaWalkNetwork131Masks[26][index];
#endif
    t=(a2^a6)&mask;
    a2^=t; a6^=t;
    t=(b2^b6)&mask;
    b2^=t; b6^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[27][index];
#else
    mask=sigmaWalkNetwork131Masks[27][index];
#endif
    t=(a3^a7)&mask;
    a3^=t; a7^=t;
    t=(b3^b7)&mask;
    b3^=t; b7^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[30][index];
#else
    mask=sigmaWalkNetwork131Masks[30][index];
#endif
    t=(a0^a2)&mask;
    a0^=t; a2^=t;
    t=(b0^b2)&mask;
    b0^=t; b2^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[31][index];
#else
    mask=sigmaWalkNetwork131Masks[31][index];
#endif
    t=(a1^a3)&mask;
    a1^=t; a3^=t;
    t=(b1^b3)&mask;
    b1^=t; b3^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[26][index];
#else
    mask=sigmaWalkNetwork131Masks[26][index];
#endif
    t=(a4^a6)&mask;
    a4^=t; a6^=t;
    t=(b4^b6)&mask;
    b4^=t; b6^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[27][index];
#else
    mask=sigmaWalkNetwork131Masks[27][index];
#endif
    t=(a5^a7)&mask;
    a5^=t; a7^=t;
    t=(b5^b7)&mask;
    b5^=t; b7^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[32][index];
#else
    mask=sigmaWalkNetwork131Masks[32][index];
#endif
    t=(a0^a1)&mask;
    a0^=t; a1^=t;
    t=(b0^b1)&mask;
    b0^=t; b1^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[33][index];
#else
    mask=sigmaWalkNetwork131Masks[33][index];
#endif
    t=(a2^a3)&mask;
    a2^=t; a3^=t;
    t=(b2^b3)&mask;
    b2^=t; b3^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[25][index];
#else
    mask=sigmaWalkNetwork131Masks[25][index];
#endif
    t=(a4^a5)&mask;
    a4^=t; a5^=t;
    t=(b4^b5)&mask;
    b4^=t; b5^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[34][index];
#else
    mask=sigmaWalkNetwork131Masks[34][index];
#endif
    t=((a0 >> 16)^a0)&mask;
    a0^=t^(t << 16);
    t=((b0 >> 16)^b0)&mask;
    b0^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[35][index];
#else
    mask=sigmaWalkNetwork131Masks[35][index];
#endif
    t=((a1 >> 16)^a1)&mask;
    a1^=t^(t << 16);
    t=((b1 >> 16)^b1)&mask;
    b1^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[36][index];
#else
    mask=sigmaWalkNetwork131Masks[36][index];
#endif
    t=((a2 >> 16)^a2)&mask;
    a2^=t^(t << 16);
    t=((b2 >> 16)^b2)&mask;
    b2^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[37][index];
#else
    mask=sigmaWalkNetwork131Masks[37][index];
#endif
    t=((a3 >> 16)^a3)&mask;
    a3^=t^(t << 16);
    t=((b3 >> 16)^b3)&mask;
    b3^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[23][index];
#else
    mask=sigmaWalkNetwork131Masks[23][index];
#endif
    t=((a4 >> 16)^a4)&mask;
    a4^=t^(t << 16);
    t=((b4 >> 16)^b4)&mask;
    b4^=t^(t << 16);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[38][index];
#else
    mask=sigmaWalkNetwork131Masks[38][index];
#endif
    t=((a0 >> 8)^a0)&mask;
    a0^=t^(t << 8);
    t=((b0 >> 8)^b0)&mask;
    b0^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[39][index];
#else
    mask=sigmaWalkNetwork131Masks[39][index];
#endif
    t=((a1 >> 8)^a1)&mask;
    a1^=t^(t << 8);
    t=((b1 >> 8)^b1)&mask;
    b1^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[40][index];
#else
    mask=sigmaWalkNetwork131Masks[40][index];
#endif
    t=((a2 >> 8)^a2)&mask;
    a2^=t^(t << 8);
    t=((b2 >> 8)^b2)&mask;
    b2^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[41][index];
#else
    mask=sigmaWalkNetwork131Masks[41][index];
#endif
    t=((a3 >> 8)^a3)&mask;
    a3^=t^(t << 8);
    t=((b3 >> 8)^b3)&mask;
    b3^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[19][index];
#else
    mask=sigmaWalkNetwork131Masks[19][index];
#endif
    t=((a4 >> 8)^a4)&mask;
    a4^=t^(t << 8);
    t=((b4 >> 8)^b4)&mask;
    b4^=t^(t << 8);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[42][index];
#else
    mask=sigmaWalkNetwork131Masks[42][index];
#endif
    t=((a0 >> 4)^a0)&mask;
    a0^=t^(t << 4);
    t=((b0 >> 4)^b0)&mask;
    b0^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[43][index];
#else
    mask=sigmaWalkNetwork131Masks[43][index];
#endif
    t=((a1 >> 4)^a1)&mask;
    a1^=t^(t << 4);
    t=((b1 >> 4)^b1)&mask;
    b1^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[44][index];
#else
    mask=sigmaWalkNetwork131Masks[44][index];
#endif
    t=((a2 >> 4)^a2)&mask;
    a2^=t^(t << 4);
    t=((b2 >> 4)^b2)&mask;
    b2^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[45][index];
#else
    mask=sigmaWalkNetwork131Masks[45][index];
#endif
    t=((a3 >> 4)^a3)&mask;
    a3^=t^(t << 4);
    t=((b3 >> 4)^b3)&mask;
    b3^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[14][index];
#else
    mask=sigmaWalkNetwork131Masks[14][index];
#endif
    t=((a4 >> 4)^a4)&mask;
    a4^=t^(t << 4);
    t=((b4 >> 4)^b4)&mask;
    b4^=t^(t << 4);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[46][index];
#else
    mask=sigmaWalkNetwork131Masks[46][index];
#endif
    t=((a0 >> 2)^a0)&mask;
    a0^=t^(t << 2);
    t=((b0 >> 2)^b0)&mask;
    b0^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[47][index];
#else
    mask=sigmaWalkNetwork131Masks[47][index];
#endif
    t=((a1 >> 2)^a1)&mask;
    a1^=t^(t << 2);
    t=((b1 >> 2)^b1)&mask;
    b1^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[48][index];
#else
    mask=sigmaWalkNetwork131Masks[48][index];
#endif
    t=((a2 >> 2)^a2)&mask;
    a2^=t^(t << 2);
    t=((b2 >> 2)^b2)&mask;
    b2^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[49][index];
#else
    mask=sigmaWalkNetwork131Masks[49][index];
#endif
    t=((a3 >> 2)^a3)&mask;
    a3^=t^(t << 2);
    t=((b3 >> 2)^b3)&mask;
    b3^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[50][index];
#else
    mask=sigmaWalkNetwork131Masks[50][index];
#endif
    t=((a4 >> 2)^a4)&mask;
    a4^=t^(t << 2);
    t=((b4 >> 2)^b4)&mask;
    b4^=t^(t << 2);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[51][index];
#else
    mask=sigmaWalkNetwork131Masks[51][index];
#endif
    t=((a0 >> 1)^a0)&mask;
    a0^=t^(t << 1);
    t=((b0 >> 1)^b0)&mask;
    b0^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[52][index];
#else
    mask=sigmaWalkNetwork131Masks[52][index];
#endif
    t=((a1 >> 1)^a1)&mask;
    a1^=t^(t << 1);
    t=((b1 >> 1)^b1)&mask;
    b1^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[53][index];
#else
    mask=sigmaWalkNetwork131Masks[53][index];
#endif
    t=((a2 >> 1)^a2)&mask;
    a2^=t^(t << 1);
    t=((b2 >> 1)^b2)&mask;
    b2^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[54][index];
#else
    mask=sigmaWalkNetwork131Masks[54][index];
#endif
    t=((a3 >> 1)^a3)&mask;
    a3^=t^(t << 1);
    t=((b3 >> 1)^b3)&mask;
    b3^=t^(t << 1);
#ifdef __CUDA_ARCH__
    mask=sigmaWalkShared131Masks[55][index];
#else
    mask=sigmaWalkNetwork131Masks[55][index];
#endif
    t=((a4 >> 1)^a4)&mask;
    a4^=t^(t << 1);
    t=((b4 >> 1)^b4)&mask;
    b4^=t^(t << 1);
    return SigmaWalkPair131{P131{{a0,a1,a2,a3,a4&7u}},P131{{b0,b1,b2,b3,b4&7u}}};
#endif
}
#endif
#if ECC_FROBENIUS_FUSED
template<int POWER>
static ECC_HD P131 sigmaInverseFixed131(P131 a) {
    static_assert(POWER==4 || POWER==8 || POWER==16 || POWER==32 || POWER==65);
    uint32_t v0=a.v[0],v1=a.v[1],v2=a.v[2],v3=a.v[3],v4=a.v[4],v5=0,v6=0,v7=0,t;
    if constexpr (POWER==4) {
        t=((v1 >> 1)^v1)&0x00015555u;
        v1^=t^(t << 1);
        t=((v2 >> 1)^v2)&0x00000155u;
        v2^=t^(t << 1);
        t=((v0 >> 2)^v0)&0x22112200u;
        v0^=t^(t << 2);
        t=((v1 >> 2)^v1)&0x00223333u;
        v1^=t^(t << 2);
        t=((v3 >> 2)^v3)&0x10000002u;
        v3^=t^(t << 2);
        t=((v4 >> 2)^v4)&0x00000003u;
        v4^=t^(t << 2);
        t=((v0 >> 4)^v0)&0x000a0000u;
        v0^=t^(t << 4);
        t=((v1 >> 4)^v1)&0x03090800u;
        v1^=t^(t << 4);
        t=((v2 >> 4)^v2)&0x08040c01u;
        v2^=t^(t << 4);
        t=((v3 >> 4)^v3)&0x0c04060au;
        v3^=t^(t << 4);
        t=((v4 >> 4)^v4)&0x0000000cu;
        v4^=t^(t << 4);
        v0 = (v0 & ~0xffff0000u) | (goal22BytePerm(v0,v0,0x2301u) & 0xffff0000u);
        v1 = (v1 & ~0x6a6a8d8du) | (goal22BytePerm(v1,v1,0x2301u) & 0x6a6a8d8du);
        v2 = (v2 & ~0xeaea5454u) | (goal22BytePerm(v2,v2,0x2301u) & 0xeaea5454u);
        v3 = (v3 & ~0x06069b9bu) | (goal22BytePerm(v3,v3,0x2301u) & 0x06069b9bu);
        v4 = (v4 & ~0x00004141u) | (goal22BytePerm(v4,v4,0x2301u) & 0x00004141u);
        v1 = (v1 & ~0x50015001u) | (goal22BytePerm(v1,v1,0x1032u) & 0x50015001u);
        v2 = (v2 & ~0x06560656u) | (goal22BytePerm(v2,v2,0x1032u) & 0x06560656u);
        v3 = (v3 & ~0x15501550u) | (goal22BytePerm(v3,v3,0x1032u) & 0x15501550u);
        t=(v2^v3)&0x36001488u;
        v2^=t; v3^=t;
        t=(v4^v5)&0x00004080u;
        v4^=t; v5^=t;
        t=(v4^v6)&0x00000100u;
        v4^=t; v6^=t;
        t=(v5^v7)&0x00004000u;
        v5^=t; v7^=t;
        t=(v1^v5)&0x00000080u;
        v1^=t; v5^=t;
        t=(v2^v6)&0x00000100u;
        v2^=t; v6^=t;
        t=(v3^v7)&0x00004000u;
        v3^=t; v7^=t;
        t=(v0^v2)&0x5a0f0ff0u;
        v0^=t; v2^=t;
        t=(v1^v3)&0x2d29d27cu;
        v1^=t; v3^=t;
        t=(v4^v6)&0x00000100u;
        v4^=t; v6^=t;
        t=(v5^v7)&0x00004000u;
        v5^=t; v7^=t;
        t=(v0^v1)&0x919c9cfcu;
        v0^=t; v1^=t;
        t=(v2^v3)&0x19c9c9cau;
        v2^=t; v3^=t;
        t=(v4^v5)&0x00004080u;
        v4^=t; v5^=t;
        v0 = (v0 & ~0x44ba44bau) | (goal22BytePerm(v0,v0,0x1032u) & 0x44ba44bau);
        v1 = (v1 & ~0x17e917e9u) | (goal22BytePerm(v1,v1,0x1032u) & 0x17e917e9u);
        v2 = (v2 & ~0x4de24de2u) | (goal22BytePerm(v2,v2,0x1032u) & 0x4de24de2u);
        v3 = (v3 & ~0x359e359eu) | (goal22BytePerm(v3,v3,0x1032u) & 0x359e359eu);
        v0 = (v0 & ~0x56563b3bu) | (goal22BytePerm(v0,v0,0x2301u) & 0x56563b3bu);
        v1 = (v1 & ~0x5b5bfcfcu) | (goal22BytePerm(v1,v1,0x2301u) & 0x5b5bfcfcu);
        v2 = (v2 & ~0x2c2cb6b6u) | (goal22BytePerm(v2,v2,0x2301u) & 0x2c2cb6b6u);
        v3 = (v3 & ~0xa3a3cacau) | (goal22BytePerm(v3,v3,0x2301u) & 0xa3a3cacau);
        v4 = (v4 & ~0x00004141u) | (goal22BytePerm(v4,v4,0x2301u) & 0x00004141u);
        t=((v0 >> 4)^v0)&0x0a000905u;
        v0^=t^(t << 4);
        t=((v1 >> 4)^v1)&0x0c0a0400u;
        v1^=t^(t << 4);
        t=((v2 >> 4)^v2)&0x050d060au;
        v2^=t^(t << 4);
        t=((v3 >> 4)^v3)&0x03050b0fu;
        v3^=t^(t << 4);
        t=((v4 >> 4)^v4)&0x0000000cu;
        v4^=t^(t << 4);
        t=((v0 >> 2)^v0)&0x30011333u;
        v0^=t^(t << 2);
        t=((v1 >> 2)^v1)&0x03122200u;
        v1^=t^(t << 2);
        t=((v2 >> 2)^v2)&0x30211133u;
        v2^=t^(t << 2);
        t=((v3 >> 2)^v3)&0x03122200u;
        v3^=t^(t << 2);
        t=((v4 >> 2)^v4)&0x00000003u;
        v4^=t^(t << 2);
        t=((v0 >> 1)^v0)&0x11014054u;
        v0^=t^(t << 1);
        t=((v1 >> 1)^v1)&0x11014454u;
        v1^=t^(t << 1);
        t=((v2 >> 1)^v2)&0x11014454u;
        v2^=t^(t << 1);
        t=((v3 >> 1)^v3)&0x11014454u;
        v3^=t^(t << 1);
    }
    if constexpr (POWER==8) {
        t=((v0 >> 1)^v0)&0x55540000u;
        v0^=t^(t << 1);
        t=((v1 >> 1)^v1)&0x00555501u;
        v1^=t^(t << 1);
        t=((v2 >> 1)^v2)&0x40000400u;
        v2^=t^(t << 1);
        t=((v3 >> 1)^v3)&0x55541555u;
        v3^=t^(t << 1);
        t=((v4 >> 1)^v4)&0x00000005u;
        v4^=t^(t << 1);
        t=((v0 >> 2)^v0)&0x33300020u;
        v0^=t^(t << 2);
        t=((v1 >> 2)^v1)&0x23322001u;
        v1^=t^(t << 2);
        t=((v2 >> 2)^v2)&0x03331002u;
        v2^=t^(t << 2);
        t=((v3 >> 2)^v3)&0x11311200u;
        v3^=t^(t << 2);
        t=((v0 >> 4)^v0)&0x05030c00u;
        v0^=t^(t << 4);
        t=((v1 >> 4)^v1)&0x04030408u;
        v1^=t^(t << 4);
        t=((v2 >> 4)^v2)&0x04030400u;
        v2^=t^(t << 4);
        t=((v3 >> 4)^v3)&0x00030002u;
        v3^=t^(t << 4);
        t=((v4 >> 4)^v4)&0x00000002u;
        v4^=t^(t << 4);
        v0 = (v0 & ~0x22220000u) | (goal22BytePerm(v0,v0,0x2301u) & 0x22220000u);
        v1 = (v1 & ~0xa2a2ccccu) | (goal22BytePerm(v1,v1,0x2301u) & 0xa2a2ccccu);
        v2 = (v2 & ~0x2b2b7070u) | (goal22BytePerm(v2,v2,0x2301u) & 0x2b2b7070u);
        v3 = (v3 & ~0xf0f0c1c1u) | (goal22BytePerm(v3,v3,0x2301u) & 0xf0f0c1c1u);
        v1 = (v1 & ~0x86d786d7u) | (goal22BytePerm(v1,v1,0x1032u) & 0x86d786d7u);
        v2 = (v2 & ~0x59285928u) | (goal22BytePerm(v2,v2,0x1032u) & 0x59285928u);
        v3 = (v3 & ~0x88f088f0u) | (goal22BytePerm(v3,v3,0x1032u) & 0x88f088f0u);
        v4 = (v4 & ~0x00080008u) | (goal22BytePerm(v4,v4,0x1032u) & 0x00080008u);
        t=(v2^v3)&0x03e350d6u;
        v2^=t; v3^=t;
        t=(v4^v5)&0x00000001u;
        v4^=t; v5^=t;
        t=(v4^v6)&0x00000020u;
        v4^=t; v6^=t;
        t=(v0^v4)&0x00080000u;
        v0^=t; v4^=t;
        t=(v1^v5)&0x00000001u;
        v1^=t; v5^=t;
        t=(v2^v6)&0x00000020u;
        v2^=t; v6^=t;
        t=(v0^v2)&0x7adffe00u;
        v0^=t; v2^=t;
        t=(v1^v3)&0x792ca6d7u;
        v1^=t; v3^=t;
        t=(v4^v6)&0x00000020u;
        v4^=t; v6^=t;
        t=(v0^v1)&0xb73fe9f0u;
        v0^=t; v1^=t;
        t=(v2^v3)&0xa6fc2cb8u;
        v2^=t; v3^=t;
        t=(v4^v5)&0x00000001u;
        v4^=t; v5^=t;
        v0 = (v0 & ~0xa99ca99cu) | (goal22BytePerm(v0,v0,0x1032u) & 0xa99ca99cu);
        v1 = (v1 & ~0x51665166u) | (goal22BytePerm(v1,v1,0x1032u) & 0x51665166u);
        v2 = (v2 & ~0x95fe95feu) | (goal22BytePerm(v2,v2,0x1032u) & 0x95fe95feu);
        v3 = (v3 & ~0x12611261u) | (goal22BytePerm(v3,v3,0x1032u) & 0x12611261u);
        v4 = (v4 & ~0x00080008u) | (goal22BytePerm(v4,v4,0x1032u) & 0x00080008u);
        v0 = (v0 & ~0x1a1a0a0au) | (goal22BytePerm(v0,v0,0x2301u) & 0x1a1a0a0au);
        v1 = (v1 & ~0x0c0ce7e7u) | (goal22BytePerm(v1,v1,0x2301u) & 0x0c0ce7e7u);
        v2 = (v2 & ~0xcdcdbebeu) | (goal22BytePerm(v2,v2,0x2301u) & 0xcdcdbebeu);
        v3 = (v3 & ~0x0d0d7373u) | (goal22BytePerm(v3,v3,0x2301u) & 0x0d0d7373u);
        t=((v0 >> 4)^v0)&0x03060f03u;
        v0^=t^(t << 4);
        t=((v1 >> 4)^v1)&0x090c090bu;
        v1^=t^(t << 4);
        t=((v2 >> 4)^v2)&0x090c090bu;
        v2^=t^(t << 4);
        t=((v3 >> 4)^v3)&0x080e090fu;
        v3^=t^(t << 4);
        t=((v4 >> 4)^v4)&0x00000002u;
        v4^=t^(t << 4);
        t=((v0 >> 2)^v0)&0x31321133u;
        v0^=t^(t << 2);
        t=((v1 >> 2)^v1)&0x11311333u;
        v1^=t^(t << 2);
        t=((v2 >> 2)^v2)&0x11111111u;
        v2^=t^(t << 2);
        t=((v3 >> 2)^v3)&0x00101111u;
        v3^=t^(t << 2);
        t=((v4 >> 2)^v4)&0x00000002u;
        v4^=t^(t << 2);
        t=((v0 >> 1)^v0)&0x00010515u;
        v0^=t^(t << 1);
        t=((v4 >> 1)^v4)&0x00000004u;
        v4^=t^(t << 1);
    }
    if constexpr (POWER==16) {
        t=((v0 >> 1)^v0)&0x15455000u;
        v0^=t^(t << 1);
        t=((v1 >> 1)^v1)&0x51454000u;
        v1^=t^(t << 1);
        t=((v2 >> 1)^v2)&0x51014045u;
        v2^=t^(t << 1);
        t=((v3 >> 1)^v3)&0x00015545u;
        v3^=t^(t << 1);
        t=((v4 >> 1)^v4)&0x00000004u;
        v4^=t^(t << 1);
        t=((v0 >> 2)^v0)&0x12211330u;
        v0^=t^(t << 2);
        t=((v1 >> 2)^v1)&0x33300200u;
        v1^=t^(t << 2);
        t=((v2 >> 2)^v2)&0x23330011u;
        v2^=t^(t << 2);
        t=((v3 >> 2)^v3)&0x02301312u;
        v3^=t^(t << 2);
        t=((v4 >> 2)^v4)&0x00000001u;
        v4^=t^(t << 2);
        t=((v0 >> 4)^v0)&0x0a080900u;
        v0^=t^(t << 4);
        t=((v1 >> 4)^v1)&0x0b050e00u;
        v1^=t^(t << 4);
        t=((v2 >> 4)^v2)&0x0e0c0000u;
        v2^=t^(t << 4);
        t=((v3 >> 4)^v3)&0x0b000003u;
        v3^=t^(t << 4);
        t=((v4 >> 4)^v4)&0x00000006u;
        v4^=t^(t << 4);
        v0 = (v0 & ~0x41410000u) | (goal22BytePerm(v0,v0,0x2301u) & 0x41410000u);
        v1 = (v1 & ~0x7e7e9f9fu) | (goal22BytePerm(v1,v1,0x2301u) & 0x7e7e9f9fu);
        v2 = (v2 & ~0xc1c11b1bu) | (goal22BytePerm(v2,v2,0x2301u) & 0xc1c11b1bu);
        v3 = (v3 & ~0xd5d5dbdbu) | (goal22BytePerm(v3,v3,0x2301u) & 0xd5d5dbdbu);
        v4 = (v4 & ~0x00000808u) | (goal22BytePerm(v4,v4,0x2301u) & 0x00000808u);
        v1 = (v1 & ~0x34563456u) | (goal22BytePerm(v1,v1,0x1032u) & 0x34563456u);
        v2 = (v2 & ~0x60b860b8u) | (goal22BytePerm(v2,v2,0x1032u) & 0x60b860b8u);
        v3 = (v3 & ~0xb674b674u) | (goal22BytePerm(v3,v3,0x1032u) & 0xb674b674u);
        v4 = (v4 & ~0x08400840u) | (goal22BytePerm(v4,v4,0x1032u) & 0x08400840u);
        t=(v2^v3)&0x07094244u;
        v2^=t; v3^=t;
        t=(v4^v5)&0x08400000u;
        v4^=t; v5^=t;
        t=(v5^v7)&0x00400000u;
        v5^=t; v7^=t;
        t=(v0^v4)&0x00000020u;
        v0^=t; v4^=t;
        t=(v1^v5)&0x08000000u;
        v1^=t; v5^=t;
        t=(v3^v7)&0x00400000u;
        v3^=t; v7^=t;
        t=(v0^v2)&0xc3e4641eu;
        v0^=t; v2^=t;
        t=(v1^v3)&0xcc5bba43u;
        v1^=t; v3^=t;
        t=(v5^v7)&0x00400000u;
        v5^=t; v7^=t;
        t=(v0^v1)&0x15c7ea33u;
        v0^=t; v1^=t;
        t=(v2^v3)&0x72c87aa7u;
        v2^=t; v3^=t;
        t=(v4^v5)&0x08400000u;
        v4^=t; v5^=t;
        v0 = (v0 & ~0x2ae72ae7u) | (goal22BytePerm(v0,v0,0x1032u) & 0x2ae72ae7u);
        v1 = (v1 & ~0x0a3f0a3fu) | (goal22BytePerm(v1,v1,0x1032u) & 0x0a3f0a3fu);
        v2 = (v2 & ~0x17e117e1u) | (goal22BytePerm(v2,v2,0x1032u) & 0x17e117e1u);
        v3 = (v3 & ~0x8a5c8a5cu) | (goal22BytePerm(v3,v3,0x1032u) & 0x8a5c8a5cu);
        v4 = (v4 & ~0x08400840u) | (goal22BytePerm(v4,v4,0x1032u) & 0x08400840u);
        v0 = (v0 & ~0x8989e7e7u) | (goal22BytePerm(v0,v0,0x2301u) & 0x8989e7e7u);
        v1 = (v1 & ~0xe8e8afafu) | (goal22BytePerm(v1,v1,0x2301u) & 0xe8e8afafu);
        v2 = (v2 & ~0x7f7f3535u) | (goal22BytePerm(v2,v2,0x2301u) & 0x7f7f3535u);
        v3 = (v3 & ~0x8080c1c1u) | (goal22BytePerm(v3,v3,0x2301u) & 0x8080c1c1u);
        v4 = (v4 & ~0x00000808u) | (goal22BytePerm(v4,v4,0x2301u) & 0x00000808u);
        t=((v0 >> 4)^v0)&0x0704060du;
        v0^=t^(t << 4);
        t=((v1 >> 4)^v1)&0x0b0a0009u;
        v1^=t^(t << 4);
        t=((v2 >> 4)^v2)&0x0d0f0e03u;
        v2^=t^(t << 4);
        t=((v3 >> 4)^v3)&0x0e000408u;
        v3^=t^(t << 4);
        t=((v4 >> 4)^v4)&0x00000006u;
        v4^=t^(t << 4);
        t=((v0 >> 2)^v0)&0x13110320u;
        v0^=t^(t << 2);
        t=((v1 >> 2)^v1)&0x11322211u;
        v1^=t^(t << 2);
        t=((v2 >> 2)^v2)&0x13313311u;
        v2^=t^(t << 2);
        t=((v3 >> 2)^v3)&0x12102021u;
        v3^=t^(t << 2);
        t=((v4 >> 2)^v4)&0x00000001u;
        v4^=t^(t << 2);
        t=((v0 >> 1)^v0)&0x54150401u;
        v0^=t^(t << 1);
        t=((v1 >> 1)^v1)&0x00004010u;
        v1^=t^(t << 1);
        t=((v2 >> 1)^v2)&0x00015455u;
        v2^=t^(t << 1);
        t=((v3 >> 1)^v3)&0x55554400u;
        v3^=t^(t << 1);
        t=((v4 >> 1)^v4)&0x00000005u;
        v4^=t^(t << 1);
    }
    if constexpr (POWER==32) {
        t=((v0 >> 1)^v0)&0x15400000u;
        v0^=t^(t << 1);
        t=((v1 >> 1)^v1)&0x01400000u;
        v1^=t^(t << 1);
        t=((v2 >> 1)^v2)&0x00001550u;
        v2^=t^(t << 1);
        t=((v3 >> 1)^v3)&0x05500550u;
        v3^=t^(t << 1);
        t=((v0 >> 2)^v0)&0x31100000u;
        v0^=t^(t << 2);
        t=((v1 >> 2)^v1)&0x00022202u;
        v1^=t^(t << 2);
        t=((v2 >> 2)^v2)&0x11100020u;
        v2^=t^(t << 2);
        t=((v3 >> 2)^v3)&0x33303113u;
        v3^=t^(t << 2);
        t=((v4 >> 2)^v4)&0x00000003u;
        v4^=t^(t << 2);
        t=((v0 >> 4)^v0)&0x050a0200u;
        v0^=t^(t << 4);
        t=((v1 >> 4)^v1)&0x0f0c0c0cu;
        v1^=t^(t << 4);
        t=((v2 >> 4)^v2)&0x0a0e0709u;
        v2^=t^(t << 4);
        t=((v3 >> 4)^v3)&0x070e0901u;
        v3^=t^(t << 4);
        t=((v4 >> 4)^v4)&0x00000001u;
        v4^=t^(t << 4);
        v0 = (v0 & ~0x02020000u) | (goal22BytePerm(v0,v0,0x2301u) & 0x02020000u);
        v1 = (v1 & ~0x83838484u) | (goal22BytePerm(v1,v1,0x2301u) & 0x83838484u);
        v2 = (v2 & ~0xc2c28888u) | (goal22BytePerm(v2,v2,0x2301u) & 0xc2c28888u);
        v3 = (v3 & ~0x8c8cbdbdu) | (goal22BytePerm(v3,v3,0x2301u) & 0x8c8cbdbdu);
        v4 = (v4 & ~0x00001c1cu) | (goal22BytePerm(v4,v4,0x2301u) & 0x00001c1cu);
        v1 = (v1 & ~0x080a080au) | (goal22BytePerm(v1,v1,0x1032u) & 0x080a080au);
        v2 = (v2 & ~0x40224022u) | (goal22BytePerm(v2,v2,0x1032u) & 0x40224022u);
        v3 = (v3 & ~0x5c275c27u) | (goal22BytePerm(v3,v3,0x1032u) & 0x5c275c27u);
        v4 = (v4 & ~0x1c001c00u) | (goal22BytePerm(v4,v4,0x1032u) & 0x1c001c00u);
        t=(v2^v3)&0x1300b31du;
        v2^=t; v3^=t;
        t=(v4^v5)&0x10000000u;
        v4^=t; v5^=t;
        t=(v4^v6)&0x04000000u;
        v4^=t; v6^=t;
        t=(v0^v4)&0x08000000u;
        v0^=t; v4^=t;
        t=(v1^v5)&0x10000000u;
        v1^=t; v5^=t;
        t=(v2^v6)&0x04000000u;
        v2^=t; v6^=t;
        t=(v0^v2)&0xd0e43c1eu;
        v0^=t; v2^=t;
        t=(v1^v3)&0xe342cbc1u;
        v1^=t; v3^=t;
        t=(v4^v6)&0x04000000u;
        v4^=t; v6^=t;
        t=(v0^v1)&0xfa23072fu;
        v0^=t; v1^=t;
        t=(v2^v3)&0x1b8f0f2du;
        v2^=t; v3^=t;
        t=(v4^v5)&0x10000000u;
        v4^=t; v5^=t;
        v0 = (v0 & ~0x896c896cu) | (goal22BytePerm(v0,v0,0x1032u) & 0x896c896cu);
        v1 = (v1 & ~0xe678e678u) | (goal22BytePerm(v1,v1,0x1032u) & 0xe678e678u);
        v2 = (v2 & ~0x92d492d4u) | (goal22BytePerm(v2,v2,0x1032u) & 0x92d492d4u);
        v3 = (v3 & ~0x79c879c8u) | (goal22BytePerm(v3,v3,0x1032u) & 0x79c879c8u);
        v4 = (v4 & ~0x1c001c00u) | (goal22BytePerm(v4,v4,0x1032u) & 0x1c001c00u);
        v0 = (v0 & ~0xd9d99191u) | (goal22BytePerm(v0,v0,0x2301u) & 0xd9d99191u);
        v1 = (v1 & ~0xbebeacacu) | (goal22BytePerm(v1,v1,0x2301u) & 0xbebeacacu);
        v2 = (v2 & ~0x9f9fccccu) | (goal22BytePerm(v2,v2,0x2301u) & 0x9f9fccccu);
        v3 = (v3 & ~0x7b7bf0f0u) | (goal22BytePerm(v3,v3,0x2301u) & 0x7b7bf0f0u);
        v4 = (v4 & ~0x00001c1cu) | (goal22BytePerm(v4,v4,0x2301u) & 0x00001c1cu);
        t=((v0 >> 4)^v0)&0x0f090908u;
        v0^=t^(t << 4);
        t=((v1 >> 4)^v1)&0x07040806u;
        v1^=t^(t << 4);
        t=((v2 >> 4)^v2)&0x080d0d09u;
        v2^=t^(t << 4);
        t=((v3 >> 4)^v3)&0x080f0707u;
        v3^=t^(t << 4);
        t=((v4 >> 4)^v4)&0x00000001u;
        v4^=t^(t << 4);
        t=((v0 >> 2)^v0)&0x21222212u;
        v0^=t^(t << 2);
        t=((v1 >> 2)^v1)&0x02013132u;
        v1^=t^(t << 2);
        t=((v2 >> 2)^v2)&0x23111002u;
        v2^=t^(t << 2);
        t=((v3 >> 2)^v3)&0x13222011u;
        v3^=t^(t << 2);
        t=((v4 >> 2)^v4)&0x00000003u;
        v4^=t^(t << 2);
        t=((v0 >> 1)^v0)&0x50544151u;
        v0^=t^(t << 1);
        t=((v1 >> 1)^v1)&0x14445111u;
        v1^=t^(t << 1);
        t=((v2 >> 1)^v2)&0x04441110u;
        v2^=t^(t << 1);
        t=((v3 >> 1)^v3)&0x44451115u;
        v3^=t^(t << 1);
        t=((v4 >> 1)^v4)&0x00000001u;
        v4^=t^(t << 1);
    }
    if constexpr (POWER==65) {
        t=((v0 >> 1)^v0)&0x15100440u;
        v0^=t^(t << 1);
        t=((v1 >> 1)^v1)&0x54141150u;
        v1^=t^(t << 1);
        t=((v2 >> 1)^v2)&0x55001400u;
        v2^=t^(t << 1);
        t=((v3 >> 1)^v3)&0x54054514u;
        v3^=t^(t << 1);
        t=((v0 >> 2)^v0)&0x00012110u;
        v0^=t^(t << 2);
        t=((v1 >> 2)^v1)&0x21232223u;
        v1^=t^(t << 2);
        t=((v2 >> 2)^v2)&0x02313311u;
        v2^=t^(t << 2);
        t=((v3 >> 2)^v3)&0x31331213u;
        v3^=t^(t << 2);
        t=((v4 >> 2)^v4)&0x00000003u;
        v4^=t^(t << 2);
        t=((v0 >> 4)^v0)&0x02080200u;
        v0^=t^(t << 4);
        t=((v1 >> 4)^v1)&0x0b0d0604u;
        v1^=t^(t << 4);
        t=((v2 >> 4)^v2)&0x00000209u;
        v2^=t^(t << 4);
        t=((v3 >> 4)^v3)&0x0a0e0d0du;
        v3^=t^(t << 4);
        t=((v4 >> 4)^v4)&0x00000008u;
        v4^=t^(t << 4);
        v0 = (v0 & ~0x57570000u) | (goal22BytePerm(v0,v0,0x2301u) & 0x57570000u);
        v1 = (v1 & ~0xbdbd3232u) | (goal22BytePerm(v1,v1,0x2301u) & 0xbdbd3232u);
        v2 = (v2 & ~0x2929cdcdu) | (goal22BytePerm(v2,v2,0x2301u) & 0x2929cdcdu);
        v3 = (v3 & ~0x02025555u) | (goal22BytePerm(v3,v3,0x2301u) & 0x02025555u);
        v4 = (v4 & ~0x00000505u) | (goal22BytePerm(v4,v4,0x2301u) & 0x00000505u);
        v1 = (v1 & ~0x02400240u) | (goal22BytePerm(v1,v1,0x1032u) & 0x02400240u);
        v2 = (v2 & ~0x03640364u) | (goal22BytePerm(v2,v2,0x1032u) & 0x03640364u);
        v3 = (v3 & ~0xb100b100u) | (goal22BytePerm(v3,v3,0x1032u) & 0xb100b100u);
        v4 = (v4 & ~0x04000400u) | (goal22BytePerm(v4,v4,0x1032u) & 0x04000400u);
        t=(v2^v3)&0x59e29161u;
        v2^=t; v3^=t;
        t=(v4^v5)&0x04000080u;
        v4^=t; v5^=t;
        t=(v5^v7)&0x00000080u;
        v5^=t; v7^=t;
        t=(v0^v4)&0x00000100u;
        v0^=t; v4^=t;
        t=(v1^v5)&0x04000000u;
        v1^=t; v5^=t;
        t=(v3^v7)&0x00000080u;
        v3^=t; v7^=t;
        t=(v0^v2)&0x9c711bb6u;
        v0^=t; v2^=t;
        t=(v1^v3)&0xe39288d5u;
        v1^=t; v3^=t;
        t=(v5^v7)&0x00000080u;
        v5^=t; v7^=t;
        t=(v0^v1)&0xeed5500bu;
        v0^=t; v1^=t;
        t=(v2^v3)&0x35eb45cfu;
        v2^=t; v3^=t;
        t=(v4^v5)&0x04000080u;
        v4^=t; v5^=t;
        v0 = (v0 & ~0xa5a9a5a9u) | (goal22BytePerm(v0,v0,0x1032u) & 0xa5a9a5a9u);
        v1 = (v1 & ~0x99e799e7u) | (goal22BytePerm(v1,v1,0x1032u) & 0x99e799e7u);
        v2 = (v2 & ~0x27152715u) | (goal22BytePerm(v2,v2,0x1032u) & 0x27152715u);
        v3 = (v3 & ~0x70a870a8u) | (goal22BytePerm(v3,v3,0x1032u) & 0x70a870a8u);
        v4 = (v4 & ~0x04000400u) | (goal22BytePerm(v4,v4,0x1032u) & 0x04000400u);
        v0 = (v0 & ~0xf9f96767u) | (goal22BytePerm(v0,v0,0x2301u) & 0xf9f96767u);
        v1 = (v1 & ~0x4848d9d9u) | (goal22BytePerm(v1,v1,0x2301u) & 0x4848d9d9u);
        v2 = (v2 & ~0xa4a40202u) | (goal22BytePerm(v2,v2,0x2301u) & 0xa4a40202u);
        v3 = (v3 & ~0xcccc4343u) | (goal22BytePerm(v3,v3,0x2301u) & 0xcccc4343u);
        v4 = (v4 & ~0x00000505u) | (goal22BytePerm(v4,v4,0x2301u) & 0x00000505u);
        t=((v0 >> 4)^v0)&0x0c0c0c0fu;
        v0^=t^(t << 4);
        t=((v1 >> 4)^v1)&0x0e0d070fu;
        v1^=t^(t << 4);
        t=((v2 >> 4)^v2)&0x0d0e0f06u;
        v2^=t^(t << 4);
        t=((v3 >> 4)^v3)&0x08040b09u;
        v3^=t^(t << 4);
        t=((v4 >> 4)^v4)&0x00000008u;
        v4^=t^(t << 4);
        t=((v0 >> 2)^v0)&0x21300031u;
        v0^=t^(t << 2);
        t=((v1 >> 2)^v1)&0x02131130u;
        v1^=t^(t << 2);
        t=((v2 >> 2)^v2)&0x22230233u;
        v2^=t^(t << 2);
        t=((v3 >> 2)^v3)&0x22131033u;
        v3^=t^(t << 2);
        t=((v4 >> 2)^v4)&0x00000002u;
        v4^=t^(t << 2);
        t=((v0 >> 1)^v0)&0x15055411u;
        v0^=t^(t << 1);
        t=((v1 >> 1)^v1)&0x00110554u;
        v1^=t^(t << 1);
        t=((v2 >> 1)^v2)&0x55154154u;
        v2^=t^(t << 1);
        t=((v3 >> 1)^v3)&0x10000045u;
        v3^=t^(t << 1);
    }
    return P131{{v0,v1,v2,v3,v4&7u}};
}
#endif
#undef ECC_SIGMA_WALK_STORAGE
#undef ECC_SIGMA_INV_STORAGE
