// Generated by codegen/genshiftedsigma.py; inside eccPacked131.
#pragma once
#ifdef __CUDACC__
static __device__ const
#else
static const
#endif
uint32_t sigmaShiftedWalkMasks131[61][8] = {
    {0x00000000u,0x55550000u,0x55015500u,0x00000000u,0x00000000u,0x55540000u,0x55540445u,0x00000000u},
    {0x00000000u,0x00000001u,0x00540101u,0x00000000u,0x11111100u,0x01555505u,0x00000015u,0x00000000u},
    {0x00000000u,0x55540000u,0x50015400u,0x00000000u,0x00000111u,0x40000000u,0x00000000u,0x40000000u},
    {0x00000000u,0x00000005u,0x00015001u,0x50500000u,0x44440000u,0x55545555u,0x00005444u,0x00000055u},
    {0x00000000u,0x00000000u,0x00000004u,0x00000000u,0x00000004u,0x00000005u,0x00000000u,0x00000000u},
    {0x00000000u,0x11332222u,0x20100203u,0x22002200u,0x31203130u,0x22202222u,0x01000120u,0x00000000u},
    {0x00000000u,0x33111113u,0x00200002u,0x00000000u,0x21202021u,0x31200002u,0x00000020u,0x32220001u},
    {0x00000000u,0x22200001u,0x01120002u,0x00100000u,0x10001120u,0x11110233u,0x11233020u,0x20022222u},
    {0x00000000u,0x00020000u,0x00030200u,0x12300010u,0x21200000u,0x33331113u,0x11113321u,0x12220000u},
    {0x00000000u,0x00000002u,0x00000000u,0x00000000u,0x00000000u,0x00000003u,0x00000001u,0x00000001u},
    {0x02020303u,0x040c0001u,0x00020200u,0x00000904u,0x0c0c0108u,0x08000e0eu,0x0f070701u,0x00000404u},
    {0x04040606u,0x00060204u,0x0e050c0du,0x0a020800u,0x0d080304u,0x040c0c08u,0x050c0405u,0x01010003u},
    {0x00000404u,0x0200090cu,0x0f0f0801u,0x04000908u,0x05040307u,0x0808080cu,0x01040100u,0x0c090908u},
    {0x00000808u,0x0c000608u,0x00020009u,0x0c010304u,0x0c010a08u,0x00010f0eu,0x080b0808u,0x0e050204u},
    {0x00000000u,0x00000000u,0x00000003u,0x00000004u,0x00000001u,0x00000000u,0x00000000u,0x00000003u},
    {0x25252020u,0x85852222u,0x00000000u,0xc0c02222u,0x12121212u,0xa6a61414u,0x2626c4c4u,0x4a4a6464u},
    {0xb8b88a8au,0x8c8c5d5du,0x10100303u,0x7979c5c5u,0x63630c0cu,0x82827171u,0x08080f0fu,0x18188e8eu},
    {0x17175d5du,0x7272c3c3u,0x0707ffffu,0x28280909u,0x22221818u,0x42423a3au,0xc3c30202u,0x7171dedeu},
    {0x40403232u,0x30304646u,0x7b7be0e0u,0x41413232u,0xcdcd2c2cu,0x2a2a5252u,0xcacac3c3u,0xa4a40101u},
    {0x00000505u,0x00000d0du,0x00000000u,0x00000000u,0x00000202u,0x00000c0cu,0x00000101u,0x00001010u},
    {0xc89ac89au,0xa28aa28au,0x84008400u,0x80028002u,0x15001500u,0x05430543u,0x0bd90bd9u,0x94429442u},
    {0x3b683b68u,0x15d015d0u,0x30103010u,0x00050005u,0x43254325u,0x101a101au,0x642a642au,0x23342334u},
    {0x44154415u,0xe80fe80fu,0x58b858b8u,0x008e008eu,0x94869486u,0xe920e920u,0xe028e028u,0x38b138b1u},
    {0x782d782du,0x55705570u,0x051f051fu,0x00560056u,0x84198419u,0x9c419c41u,0xc475c475u,0x80098009u},
    {0x01020102u,0x00000000u,0x00080008u,0x00000000u,0x00000000u,0x00000000u,0x01000100u,0x00200020u},
    {0xb0620901u,0xb05008e4u,0x489082a8u,0xa1502403u,0x816944aeu,0x620b0845u,0x1a80d500u,0x83203f90u},
    {0x1321c288u,0x06239198u,0x5500004cu,0x0b208108u,0xb2088870u,0x11b2310cu,0x39151122u,0x62225014u},
    {0x00000000u,0x00000800u,0x00000000u,0x00000002u,0x00000000u,0x00000002u,0x00000000u,0x00000000u},
    {0x780014b8u,0x4c232485u,0x90c8004au,0xc11884a9u,0xc2d4483cu,0xa8840a12u,0x01242404u,0x05819f00u},
    {0xa0042582u,0x029c0b41u,0x12010e14u,0x2040008au,0x000402c3u,0x2948084cu,0xb241f316u,0x41872016u},
    {0x01020408u,0x00000500u,0x00080070u,0x00000041u,0x00000618u,0x00000c00u,0x01028006u,0x80201004u},
    {0x00000000u,0x00002800u,0x00000000u,0x00008002u,0x00000000u,0x00000002u,0x00000000u,0x00000000u},
    {0x84010b02u,0x90c01220u,0x2c021631u,0x06064244u,0x0009b518u,0x42116d00u,0xc0c01820u,0x5020202eu},
    {0x00495240u,0x60000018u,0x24348120u,0x18895c02u,0x4002a438u,0x86a41413u,0x08080000u,0x80500088u},
    {0x2c840050u,0x3b756129u,0x200ee211u,0x140a0aa1u,0x40021e14u,0x1f25ea48u,0x04210096u,0x10995248u},
    {0x444c4a18u,0x49000614u,0x10563812u,0x125dd055u,0x04130201u,0xc0509e00u,0x8248aa11u,0x00c005a5u},
    {0x50745074u,0x04630463u,0x61f261f2u,0x01880188u,0x002a002au,0x926d926du,0x56935693u,0xc900c900u},
    {0xb65ab65au,0x31283128u,0xa801a801u,0x67706770u,0x86828682u,0xee04ee04u,0x08040804u,0x445a445au},
    {0x24032403u,0x0c040c04u,0x80208020u,0x00610061u,0x8be78be7u,0x1b161b16u,0x10aa10aau,0x116f116fu},
    {0x08e408e4u,0x0b950b95u,0x0a100a10u,0x1dbc1dbcu,0x72d872d8u,0x24832483u,0xa304a304u,0xf050f050u},
    {0x01020102u,0x00000000u,0x00080008u,0x00000000u,0x00000000u,0x00000000u,0x01020102u,0x80208020u},
    {0x78784040u,0x8383c5c5u,0xa2a22a2au,0x2b2bc6c6u,0xf0f04040u,0x4b4b6868u,0x4f4f9c9cu,0xa2a25c5cu},
    {0xa0a0d6d6u,0xcecec0c0u,0x01010101u,0x9c9cc4c4u,0x49498a8au,0x00003131u,0x3939a0a0u,0xa2a20303u},
    {0x8686babau,0x31319292u,0x00001212u,0x2525e2e2u,0xe4e41515u,0xe0e05c5cu,0x4646e9e9u,0xb3b30101u},
    {0x5d5d2929u,0x38383434u,0x88880909u,0x8f8f1010u,0x90907d7du,0x0e0e1010u,0x1010c5c5u,0x45454848u},
    {0x00000505u,0x00002d2du,0x00000000u,0x00008080u,0x00000606u,0x00000c0cu,0x00008181u,0x00009090u},
    {0x0703070fu,0x00000e05u,0x020e000au,0x0509040au,0x0e00020cu,0x00010104u,0x0f010004u,0x0604010eu},
    {0x080c0800u,0x04000000u,0x03000100u,0x020d040bu,0x000a0605u,0x00000100u,0x0a000008u,0x040c0d01u},
    {0x0703070fu,0x0b0b010eu,0x00020002u,0x010f020du,0x0a000c08u,0x00000000u,0x07000e03u,0x050d010du},
    {0x080c0800u,0x010b0b0cu,0x00070a01u,0x0a000d06u,0x0e07070bu,0x08020008u,0x00070606u,0x0e010808u},
    {0x00000000u,0x00000002u,0x00000007u,0x0000000cu,0x00000001u,0x00000000u,0x00000008u,0x0000000bu},
    {0x22031130u,0x31331100u,0x32112303u,0x02031130u,0x13200300u,0x00100110u,0x30011000u,0x00211302u},
    {0x22031130u,0x02000223u,0x30220113u,0x30203113u,0x00320021u,0x00000000u,0x02312233u,0x33322333u},
    {0x22031130u,0x31333312u,0x03011000u,0x13020311u,0x21133013u,0x00000000u,0x33002110u,0x00311220u},
    {0x22031130u,0x00000021u,0x01103020u,0x11302031u,0x12113200u,0x00220020u,0x20012120u,0x13000000u},
    {0x00000000u,0x00000002u,0x00000002u,0x00000003u,0x00000000u,0x00000000u,0x00000001u,0x00000001u},
    {0x05500550u,0x00115500u,0x15405404u,0x01540550u,0x40110044u,0x00000414u,0x54500015u,0x14054154u},
    {0x05500550u,0x00115544u,0x40010101u,0x50154055u,0x44011004u,0x00000000u,0x14450041u,0x54150140u},
    {0x05500550u,0x00115544u,0x15555450u,0x54015005u,0x04401100u,0x00000000u,0x41545044u,0x40140541u},
    {0x05500550u,0x00115544u,0x40000105u,0x05401500u,0x00440110u,0x40000000u,0x40145500u,0x41541501u},
    {0x00000000u,0x00000004u,0x00000000u,0x00000000u,0x00000001u,0x00000000u,0x00000000u,0x00000005u},
};
#ifdef __CUDACC__
static __shared__ uint32_t sigmaShiftedWalkShared131[61][8];
#endif
ECC_HD void initShiftedSigmaWalk131() {
#ifdef __CUDA_ARCH__
    for (unsigned i=threadIdx.x; i<488; i+=blockDim.x)
        sigmaShiftedWalkShared131[i/8][i%8] = __ldg(&sigmaShiftedWalkMasks131[i/8][i%8]);
    __syncthreads();
#endif
}
ECC_HD P131 expandedPolynomial131(const P131 &a) {
    uint32_t v0=a.v[0];
    uint32_t v1=a.v[1];
    uint32_t v2=a.v[2];
    uint32_t v3=a.v[3];
    uint32_t v4=a.v[4];
    // shift 64
    v1 ^= v3;
    // shift 32
    v0 ^= (v1) & 0xffff0000u;
    v1 ^= (v2) & 0xffff0000u;
    v2 ^= (v3) & 0xffff0000u;
    // shift 16
    v0 ^= ((v0 >> 16) | (v1 << 16)) & 0xff00ff00u;
    v1 ^= ((v1 >> 16) | (v2 << 16)) & 0xff00ff00u;
    v2 ^= ((v2 >> 16) | (v3 << 16)) & 0xff00ff00u;
    v3 ^= ((v3 >> 16) | (v4 << 16)) & 0x0000ff00u;
    // shift 8
    v0 ^= ((v0 >> 8) | (v1 << 24)) & 0xf0f0f0f0u;
    v1 ^= ((v1 >> 8) | (v2 << 24)) & 0xf0f0f0f0u;
    v2 ^= ((v2 >> 8) | (v3 << 24)) & 0xf0f0f0f0u;
    v3 ^= ((v3 >> 8) | (v4 << 24)) & 0x00f0f0f0u;
    // shift 4
    v0 ^= ((v0 >> 4) | (v1 << 28)) & 0xccccccccu;
    v1 ^= ((v1 >> 4) | (v2 << 28)) & 0xccccccccu;
    v2 ^= ((v2 >> 4) | (v3 << 28)) & 0xccccccccu;
    v3 ^= ((v3 >> 4) | (v4 << 28)) & 0x4cccccccu;
    // shift 2
    v0 ^= ((v0 >> 2) | (v1 << 30)) & 0xaaaaaaaau;
    v1 ^= ((v1 >> 2) | (v2 << 30)) & 0xaaaaaaaau;
    v2 ^= ((v2 >> 2) | (v3 << 30)) & 0xaaaaaaaau;
    v3 ^= ((v3 >> 2) | (v4 << 30)) & 0xaaaaaaaau;
    return P131{{v0,v1,v2,v3,v4}};
}
ECC_HD P131 normalFromExpanded131(const P131 &a) {
    const uint32_t sign = 0u - (a.v[0] & 1u);
    P131 out;
    out.v[0] = ((a.v[0] >> 1) | (a.v[1] << 31)) ^ sign;
    out.v[1] = ((a.v[1] >> 1) | (a.v[2] << 31)) ^ sign;
    out.v[2] = ((a.v[2] >> 1) | (a.v[3] << 31)) ^ sign;
    out.v[3] = ((a.v[3] >> 1) | (a.v[4] << 31)) ^ sign;
    out.v[4] = ((a.v[4] >> 1) ^ sign) & 7u;
    return out;
}
ECC_HD P131 polynomialFromShiftedDifference131(const P131 &a) {
    const uint32_t sign = 0u - ((a.v[4] >> 3) & 1u);
    uint32_t v0 = (a.v[0] & ~1u) ^ sign;
    uint32_t v1 = a.v[1] ^ sign;
    uint32_t v2 = a.v[2] ^ sign;
    uint32_t v3 = a.v[3] ^ sign;
    uint32_t v4 = (a.v[4] ^ sign) & 7u;
    // shift 2
    v0 ^= ((v0 >> 2) | (v1 << 30)) & 0xaaaaaaaau;
    v1 ^= ((v1 >> 2) | (v2 << 30)) & 0xaaaaaaaau;
    v2 ^= ((v2 >> 2) | (v3 << 30)) & 0xaaaaaaaau;
    v3 ^= ((v3 >> 2) | (v4 << 30)) & 0xaaaaaaaau;
    // shift 4
    v0 ^= ((v0 >> 4) | (v1 << 28)) & 0x66666666u;
    v1 ^= ((v1 >> 4) | (v2 << 28)) & 0x66666666u;
    v2 ^= ((v2 >> 4) | (v3 << 28)) & 0x66666666u;
    v3 ^= ((v3 >> 4) | (v4 << 28)) & 0x66666666u;
    // shift 8
    v0 ^= ((v0 >> 8) | (v1 << 24)) & 0x88888888u;
    v1 ^= ((v1 >> 8) | (v2 << 24)) & 0x88888888u;
    v2 ^= ((v2 >> 8) | (v3 << 24)) & 0x88888888u;
    v3 ^= ((v3 >> 8) | (v4 << 24)) & 0x00888888u;
    // shift 8
    v0 ^= ((v0 >> 8) | (v1 << 24)) & 0x96969696u;
    v1 ^= ((v1 >> 8) | (v2 << 24)) & 0x96969696u;
    v2 ^= ((v2 >> 8) | (v3 << 24)) & 0x96969696u;
    v3 ^= ((v3 >> 8) | (v4 << 24)) & 0x06969696u;
    // shift 16
    v0 ^= ((v0 >> 16) | (v1 << 16)) & 0xe8e8e8e8u;
    v1 ^= ((v1 >> 16) | (v2 << 16)) & 0xe8e8e8e8u;
    v2 ^= ((v2 >> 16) | (v3 << 16)) & 0xe8e8e8e8u;
    v3 ^= ((v3 >> 16) | (v4 << 16)) & 0x0000e8e8u;
    // shift 16
    v0 ^= ((v0 >> 16) | (v1 << 16)) & 0x69966996u;
    v1 ^= ((v1 >> 16) | (v2 << 16)) & 0x69966996u;
    v2 ^= ((v2 >> 16) | (v3 << 16)) & 0x69966996u;
    v3 ^= ((v3 >> 16) | (v4 << 16)) & 0x00066996u;
    // Compose the word-aligned triangular transform stages.
    v0 ^= (v1 & 0xe881177eu) ^ (v2 & 0x177ffffeu) ^ (v3 & 0x0001177eu) ^ (v4 & 0x00000006u);
    v1 ^= (v2 & 0xe881177eu) ^ (v3 & 0xe8800001u);
    v2 ^= (v3 & 0xe881177eu) ^ (v4 & 0x00000006u);
    v3 ^= (v4 & 0x00000006u);
    return P131{{v0,v1,v2,v3,v4}};
}
ECC_HD SigmaWalkPair131 sigmaShiftedWalkPair131(P131 a, P131 b, int index) {
#if defined(__CUDACC__) && !defined(__CUDA_ARCH__)
    a.v[0] &= ~1u; b.v[0] &= ~1u;
    a = normalFromExpanded131(a); b = normalFromExpanded131(b);
    for (int i=0;i<index+3;++i) { a=sqr131(a); b=sqr131(b); }
    P131 aa, bb;
    aa.v[0] = a.v[0] << 1;
    aa.v[1] = (a.v[1] << 1) | (a.v[0] >> 31);
    aa.v[2] = (a.v[2] << 1) | (a.v[1] >> 31);
    aa.v[3] = (a.v[3] << 1) | (a.v[2] >> 31);
    aa.v[4] = (a.v[4] << 1) | (a.v[3] >> 31);
    bb.v[0] = b.v[0] << 1;
    bb.v[1] = (b.v[1] << 1) | (b.v[0] >> 31);
    bb.v[2] = (b.v[2] << 1) | (b.v[1] >> 31);
    bb.v[3] = (b.v[3] << 1) | (b.v[2] >> 31);
    bb.v[4] = (b.v[4] << 1) | (b.v[3] >> 31);
    return SigmaWalkPair131{aa,bb};
#else
    uint32_t a0=a.v[0]&~1u, a1=a.v[1], a2=a.v[2], a3=a.v[3], a4=a.v[4];
    uint32_t a5=0, a6=0, a7=0;
    uint32_t b0=b.v[0]&~1u, b1=b.v[1], b2=b.v[2], b3=b.v[3], b4=b.v[4];
    uint32_t b5=0, b6=0, b7=0;
    uint32_t t, mask;
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[0][index];
#else
    mask=sigmaShiftedWalkMasks131[0][index];
#endif
    t=((a0>>1)^a0)&mask;
    a0^=t^(t<<1);
    t=((b0>>1)^b0)&mask;
    b0^=t^(t<<1);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[1][index];
#else
    mask=sigmaShiftedWalkMasks131[1][index];
#endif
    t=((a1>>1)^a1)&mask;
    a1^=t^(t<<1);
    t=((b1>>1)^b1)&mask;
    b1^=t^(t<<1);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[2][index];
#else
    mask=sigmaShiftedWalkMasks131[2][index];
#endif
    t=((a2>>1)^a2)&mask;
    a2^=t^(t<<1);
    t=((b2>>1)^b2)&mask;
    b2^=t^(t<<1);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[3][index];
#else
    mask=sigmaShiftedWalkMasks131[3][index];
#endif
    t=((a3>>1)^a3)&mask;
    a3^=t^(t<<1);
    t=((b3>>1)^b3)&mask;
    b3^=t^(t<<1);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[4][index];
#else
    mask=sigmaShiftedWalkMasks131[4][index];
#endif
    t=((a4>>1)^a4)&mask;
    a4^=t^(t<<1);
    t=((b4>>1)^b4)&mask;
    b4^=t^(t<<1);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[5][index];
#else
    mask=sigmaShiftedWalkMasks131[5][index];
#endif
    t=((a0>>2)^a0)&mask;
    a0^=t^(t<<2);
    t=((b0>>2)^b0)&mask;
    b0^=t^(t<<2);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[6][index];
#else
    mask=sigmaShiftedWalkMasks131[6][index];
#endif
    t=((a1>>2)^a1)&mask;
    a1^=t^(t<<2);
    t=((b1>>2)^b1)&mask;
    b1^=t^(t<<2);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[7][index];
#else
    mask=sigmaShiftedWalkMasks131[7][index];
#endif
    t=((a2>>2)^a2)&mask;
    a2^=t^(t<<2);
    t=((b2>>2)^b2)&mask;
    b2^=t^(t<<2);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[8][index];
#else
    mask=sigmaShiftedWalkMasks131[8][index];
#endif
    t=((a3>>2)^a3)&mask;
    a3^=t^(t<<2);
    t=((b3>>2)^b3)&mask;
    b3^=t^(t<<2);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[9][index];
#else
    mask=sigmaShiftedWalkMasks131[9][index];
#endif
    t=((a4>>2)^a4)&mask;
    a4^=t^(t<<2);
    t=((b4>>2)^b4)&mask;
    b4^=t^(t<<2);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[10][index];
#else
    mask=sigmaShiftedWalkMasks131[10][index];
#endif
    t=((a0>>4)^a0)&mask;
    a0^=t^(t<<4);
    t=((b0>>4)^b0)&mask;
    b0^=t^(t<<4);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[11][index];
#else
    mask=sigmaShiftedWalkMasks131[11][index];
#endif
    t=((a1>>4)^a1)&mask;
    a1^=t^(t<<4);
    t=((b1>>4)^b1)&mask;
    b1^=t^(t<<4);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[12][index];
#else
    mask=sigmaShiftedWalkMasks131[12][index];
#endif
    t=((a2>>4)^a2)&mask;
    a2^=t^(t<<4);
    t=((b2>>4)^b2)&mask;
    b2^=t^(t<<4);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[13][index];
#else
    mask=sigmaShiftedWalkMasks131[13][index];
#endif
    t=((a3>>4)^a3)&mask;
    a3^=t^(t<<4);
    t=((b3>>4)^b3)&mask;
    b3^=t^(t<<4);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[14][index];
#else
    mask=sigmaShiftedWalkMasks131[14][index];
#endif
    t=((a4>>4)^a4)&mask;
    a4^=t^(t<<4);
    t=((b4>>4)^b4)&mask;
    b4^=t^(t<<4);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[15][index];
#else
    mask=sigmaShiftedWalkMasks131[15][index];
#endif
    a0=(a0&~mask)|(goal22BytePerm(a0,a0,0x2301u)&mask);
    b0=(b0&~mask)|(goal22BytePerm(b0,b0,0x2301u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[16][index];
#else
    mask=sigmaShiftedWalkMasks131[16][index];
#endif
    a1=(a1&~mask)|(goal22BytePerm(a1,a1,0x2301u)&mask);
    b1=(b1&~mask)|(goal22BytePerm(b1,b1,0x2301u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[17][index];
#else
    mask=sigmaShiftedWalkMasks131[17][index];
#endif
    a2=(a2&~mask)|(goal22BytePerm(a2,a2,0x2301u)&mask);
    b2=(b2&~mask)|(goal22BytePerm(b2,b2,0x2301u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[18][index];
#else
    mask=sigmaShiftedWalkMasks131[18][index];
#endif
    a3=(a3&~mask)|(goal22BytePerm(a3,a3,0x2301u)&mask);
    b3=(b3&~mask)|(goal22BytePerm(b3,b3,0x2301u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[19][index];
#else
    mask=sigmaShiftedWalkMasks131[19][index];
#endif
    a4=(a4&~mask)|(goal22BytePerm(a4,a4,0x2301u)&mask);
    b4=(b4&~mask)|(goal22BytePerm(b4,b4,0x2301u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[20][index];
#else
    mask=sigmaShiftedWalkMasks131[20][index];
#endif
    a0=(a0&~mask)|(goal22BytePerm(a0,a0,0x1032u)&mask);
    b0=(b0&~mask)|(goal22BytePerm(b0,b0,0x1032u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[21][index];
#else
    mask=sigmaShiftedWalkMasks131[21][index];
#endif
    a1=(a1&~mask)|(goal22BytePerm(a1,a1,0x1032u)&mask);
    b1=(b1&~mask)|(goal22BytePerm(b1,b1,0x1032u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[22][index];
#else
    mask=sigmaShiftedWalkMasks131[22][index];
#endif
    a2=(a2&~mask)|(goal22BytePerm(a2,a2,0x1032u)&mask);
    b2=(b2&~mask)|(goal22BytePerm(b2,b2,0x1032u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[23][index];
#else
    mask=sigmaShiftedWalkMasks131[23][index];
#endif
    a3=(a3&~mask)|(goal22BytePerm(a3,a3,0x1032u)&mask);
    b3=(b3&~mask)|(goal22BytePerm(b3,b3,0x1032u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[24][index];
#else
    mask=sigmaShiftedWalkMasks131[24][index];
#endif
    a4=(a4&~mask)|(goal22BytePerm(a4,a4,0x1032u)&mask);
    b4=(b4&~mask)|(goal22BytePerm(b4,b4,0x1032u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[25][index];
#else
    mask=sigmaShiftedWalkMasks131[25][index];
#endif
    t=(a0^a1)&mask;
    a0^=t; a1^=t;
    t=(b0^b1)&mask;
    b0^=t; b1^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[26][index];
#else
    mask=sigmaShiftedWalkMasks131[26][index];
#endif
    t=(a2^a3)&mask;
    a2^=t; a3^=t;
    t=(b2^b3)&mask;
    b2^=t; b3^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[27][index];
#else
    mask=sigmaShiftedWalkMasks131[27][index];
#endif
    t=(a4^a5)&mask;
    a4^=t; a5^=t;
    t=(b4^b5)&mask;
    b4^=t; b5^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[28][index];
#else
    mask=sigmaShiftedWalkMasks131[28][index];
#endif
    t=(a0^a2)&mask;
    a0^=t; a2^=t;
    t=(b0^b2)&mask;
    b0^=t; b2^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[29][index];
#else
    mask=sigmaShiftedWalkMasks131[29][index];
#endif
    t=(a1^a3)&mask;
    a1^=t; a3^=t;
    t=(b1^b3)&mask;
    b1^=t; b3^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[30][index];
#else
    mask=sigmaShiftedWalkMasks131[30][index];
#endif
    t=(a0^a4)&mask;
    a0^=t; a4^=t;
    t=(b0^b4)&mask;
    b0^=t; b4^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[31][index];
#else
    mask=sigmaShiftedWalkMasks131[31][index];
#endif
    t=(a1^a5)&mask;
    a1^=t; a5^=t;
    t=(b1^b5)&mask;
    b1^=t; b5^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[32][index];
#else
    mask=sigmaShiftedWalkMasks131[32][index];
#endif
    t=(a0^a2)&mask;
    a0^=t; a2^=t;
    t=(b0^b2)&mask;
    b0^=t; b2^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[33][index];
#else
    mask=sigmaShiftedWalkMasks131[33][index];
#endif
    t=(a1^a3)&mask;
    a1^=t; a3^=t;
    t=(b1^b3)&mask;
    b1^=t; b3^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[34][index];
#else
    mask=sigmaShiftedWalkMasks131[34][index];
#endif
    t=(a0^a1)&mask;
    a0^=t; a1^=t;
    t=(b0^b1)&mask;
    b0^=t; b1^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[35][index];
#else
    mask=sigmaShiftedWalkMasks131[35][index];
#endif
    t=(a2^a3)&mask;
    a2^=t; a3^=t;
    t=(b2^b3)&mask;
    b2^=t; b3^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[31][index];
#else
    mask=sigmaShiftedWalkMasks131[31][index];
#endif
    t=(a4^a5)&mask;
    a4^=t; a5^=t;
    t=(b4^b5)&mask;
    b4^=t; b5^=t;
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[36][index];
#else
    mask=sigmaShiftedWalkMasks131[36][index];
#endif
    a0=(a0&~mask)|(goal22BytePerm(a0,a0,0x1032u)&mask);
    b0=(b0&~mask)|(goal22BytePerm(b0,b0,0x1032u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[37][index];
#else
    mask=sigmaShiftedWalkMasks131[37][index];
#endif
    a1=(a1&~mask)|(goal22BytePerm(a1,a1,0x1032u)&mask);
    b1=(b1&~mask)|(goal22BytePerm(b1,b1,0x1032u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[38][index];
#else
    mask=sigmaShiftedWalkMasks131[38][index];
#endif
    a2=(a2&~mask)|(goal22BytePerm(a2,a2,0x1032u)&mask);
    b2=(b2&~mask)|(goal22BytePerm(b2,b2,0x1032u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[39][index];
#else
    mask=sigmaShiftedWalkMasks131[39][index];
#endif
    a3=(a3&~mask)|(goal22BytePerm(a3,a3,0x1032u)&mask);
    b3=(b3&~mask)|(goal22BytePerm(b3,b3,0x1032u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[40][index];
#else
    mask=sigmaShiftedWalkMasks131[40][index];
#endif
    a4=(a4&~mask)|(goal22BytePerm(a4,a4,0x1032u)&mask);
    b4=(b4&~mask)|(goal22BytePerm(b4,b4,0x1032u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[41][index];
#else
    mask=sigmaShiftedWalkMasks131[41][index];
#endif
    a0=(a0&~mask)|(goal22BytePerm(a0,a0,0x2301u)&mask);
    b0=(b0&~mask)|(goal22BytePerm(b0,b0,0x2301u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[42][index];
#else
    mask=sigmaShiftedWalkMasks131[42][index];
#endif
    a1=(a1&~mask)|(goal22BytePerm(a1,a1,0x2301u)&mask);
    b1=(b1&~mask)|(goal22BytePerm(b1,b1,0x2301u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[43][index];
#else
    mask=sigmaShiftedWalkMasks131[43][index];
#endif
    a2=(a2&~mask)|(goal22BytePerm(a2,a2,0x2301u)&mask);
    b2=(b2&~mask)|(goal22BytePerm(b2,b2,0x2301u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[44][index];
#else
    mask=sigmaShiftedWalkMasks131[44][index];
#endif
    a3=(a3&~mask)|(goal22BytePerm(a3,a3,0x2301u)&mask);
    b3=(b3&~mask)|(goal22BytePerm(b3,b3,0x2301u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[45][index];
#else
    mask=sigmaShiftedWalkMasks131[45][index];
#endif
    a4=(a4&~mask)|(goal22BytePerm(a4,a4,0x2301u)&mask);
    b4=(b4&~mask)|(goal22BytePerm(b4,b4,0x2301u)&mask);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[46][index];
#else
    mask=sigmaShiftedWalkMasks131[46][index];
#endif
    t=((a0>>4)^a0)&mask;
    a0^=t^(t<<4);
    t=((b0>>4)^b0)&mask;
    b0^=t^(t<<4);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[47][index];
#else
    mask=sigmaShiftedWalkMasks131[47][index];
#endif
    t=((a1>>4)^a1)&mask;
    a1^=t^(t<<4);
    t=((b1>>4)^b1)&mask;
    b1^=t^(t<<4);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[48][index];
#else
    mask=sigmaShiftedWalkMasks131[48][index];
#endif
    t=((a2>>4)^a2)&mask;
    a2^=t^(t<<4);
    t=((b2>>4)^b2)&mask;
    b2^=t^(t<<4);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[49][index];
#else
    mask=sigmaShiftedWalkMasks131[49][index];
#endif
    t=((a3>>4)^a3)&mask;
    a3^=t^(t<<4);
    t=((b3>>4)^b3)&mask;
    b3^=t^(t<<4);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[50][index];
#else
    mask=sigmaShiftedWalkMasks131[50][index];
#endif
    t=((a4>>4)^a4)&mask;
    a4^=t^(t<<4);
    t=((b4>>4)^b4)&mask;
    b4^=t^(t<<4);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[51][index];
#else
    mask=sigmaShiftedWalkMasks131[51][index];
#endif
    t=((a0>>2)^a0)&mask;
    a0^=t^(t<<2);
    t=((b0>>2)^b0)&mask;
    b0^=t^(t<<2);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[52][index];
#else
    mask=sigmaShiftedWalkMasks131[52][index];
#endif
    t=((a1>>2)^a1)&mask;
    a1^=t^(t<<2);
    t=((b1>>2)^b1)&mask;
    b1^=t^(t<<2);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[53][index];
#else
    mask=sigmaShiftedWalkMasks131[53][index];
#endif
    t=((a2>>2)^a2)&mask;
    a2^=t^(t<<2);
    t=((b2>>2)^b2)&mask;
    b2^=t^(t<<2);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[54][index];
#else
    mask=sigmaShiftedWalkMasks131[54][index];
#endif
    t=((a3>>2)^a3)&mask;
    a3^=t^(t<<2);
    t=((b3>>2)^b3)&mask;
    b3^=t^(t<<2);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[55][index];
#else
    mask=sigmaShiftedWalkMasks131[55][index];
#endif
    t=((a4>>2)^a4)&mask;
    a4^=t^(t<<2);
    t=((b4>>2)^b4)&mask;
    b4^=t^(t<<2);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[56][index];
#else
    mask=sigmaShiftedWalkMasks131[56][index];
#endif
    t=((a0>>1)^a0)&mask;
    a0^=t^(t<<1);
    t=((b0>>1)^b0)&mask;
    b0^=t^(t<<1);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[57][index];
#else
    mask=sigmaShiftedWalkMasks131[57][index];
#endif
    t=((a1>>1)^a1)&mask;
    a1^=t^(t<<1);
    t=((b1>>1)^b1)&mask;
    b1^=t^(t<<1);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[58][index];
#else
    mask=sigmaShiftedWalkMasks131[58][index];
#endif
    t=((a2>>1)^a2)&mask;
    a2^=t^(t<<1);
    t=((b2>>1)^b2)&mask;
    b2^=t^(t<<1);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[59][index];
#else
    mask=sigmaShiftedWalkMasks131[59][index];
#endif
    t=((a3>>1)^a3)&mask;
    a3^=t^(t<<1);
    t=((b3>>1)^b3)&mask;
    b3^=t^(t<<1);
#ifdef __CUDA_ARCH__
    mask=sigmaShiftedWalkShared131[60][index];
#else
    mask=sigmaShiftedWalkMasks131[60][index];
#endif
    t=((a4>>1)^a4)&mask;
    a4^=t^(t<<1);
    t=((b4>>1)^b4)&mask;
    b4^=t^(t<<1);
    return SigmaWalkPair131{P131{{a0,a1,a2,a3,a4&15u}},P131{{b0,b1,b2,b3,b4&15u}}};
#endif
}
