// Generated by codegen/gensquareraw.py; inside eccPacked131.
#pragma once
#include "zip_square.h"
ECC_HD P131 goal22SquareReduced(P131 a) {
    const uint32_t b0=a.v[2], b1=a.v[3], b2=a.v[4];
    const uint32_t r0=b0 ^ ((b0 >> 1) | (b1 << 31)) ^ ((b0 >> 3) | (b1 << 29));
    const uint32_t r1=b1 ^ ((b1 >> 1) | (b2 << 31)) ^ ((b1 >> 3) | (b2 << 29));
    const uint32_t r2=b2 ^ ((b2 >> 1));
    const uint32_t s=b0 ^ ((b0 >> 4) | (b1 << 28)) ^ ((b0 >> 12) | (b1 << 20)) ^ ((b0 >> 28) | (b1 << 4)) ^ ((b1 >> 28) | (b2 << 4));
    const uint32_t qe=s>>2, qo=(b0>>2)^(s>>3)^(s>>4);
    const uint32_t te0=(b0 & ~3u) | ((qe ^ (qe<<1)) & 3u);
    const uint32_t te1=b1, te2=b2;
    const uint32_t to0=((((b0 >> 4) | (b1 << 28)) ^ ((r0 >> 5) | (r1 << 27)) ^ ((r0 >> 13) | (r1 << 19)) ^ ((r0 >> 29) | (r1 << 3)) ^ ((r1 >> 29) | (r2 << 3))) & ~1u) | (qo & 1u);
    const uint32_t to1=((b1 >> 4) | (b2 << 28)) ^ ((r1 >> 5) | (r2 << 27)) ^ ((r1 >> 13) | (r2 << 19)) ^ ((r1 >> 29) | (r2 << 3));
    const uint32_t to2=0u;
    const uint32_t ev0=a.v[0] ^ te0;
    const uint32_t ev1=a.v[1] ^ te1 ^ te0 ^ ((te0 << 16)) ^ ((te0 << 24)) ^ ((te0 << 28)) ^ (qe << 30);
    const uint32_t ev2=(a.v[2] ^ te2 ^ te1 ^ ((te1 << 16) | (te0 >> 16)) ^ ((te1 << 24) | (te0 >> 8)) ^ ((te1 << 28) | (te0 >> 4)) ^ te0 ^ (qe >> 2)) & 3u;
    const uint32_t od0=to0;
    const uint32_t od1=to1 ^ to0 ^ ((to0 << 16)) ^ ((to0 << 24)) ^ ((to0 << 28)) ^ (qo << 30);
    const uint32_t od2=(to2 ^ to1 ^ ((to1 << 16) | (to0 >> 16)) ^ ((to1 << 24) | (to0 >> 8)) ^ ((to1 << 28) | (to0 >> 4)) ^ to0 ^ (qo >> 2)) & 1u;
    P131 out;
    goal22Zip2(ev0,od0,&out.v[0],&out.v[1]);
    goal22Zip2(ev1,od1,&out.v[2],&out.v[3]);
    out.v[4]=(ev2&1u)|((od2&1u)<<1)|((ev2&2u)<<1);
    return out;
}
