// Generated by research/gen_square_reduce.py; inside eccPacked131.
// Checked against polynomial long division on 10133 inputs.
#pragma once
#include "zip_square.h"
ECC_HD P131 goal22SquareReduced(P131 a) {
    const uint32_t b0 = (a.v[2] >> 2) | (a.v[3] << 30);
    const uint32_t b1 = (a.v[3] >> 2) | (a.v[4] << 30);
    const uint32_t b2 = (a.v[4] >> 2);
    const uint32_t e0 = (b0) ^ ((b0 >> 4) | (b1 << 28)) ^ ((b0 >> 12) | (b1 << 20)) ^ ((b0 >> 28) | (b1 << 4)) ^ ((b1 >> 28) | (b2 << 4));
    const uint32_t e1 = (b1) ^ ((b1 >> 4) | (b2 << 28)) ^ ((b1 >> 12) | (b2 << 20)) ^ ((b1 >> 28) | (b2 << 4));
    const uint32_t e2 = ((b2)) & 1u;
    const uint32_t o0 = (b0) ^ ((e0 >> 1) | (e1 << 31)) ^ ((e0 >> 2) | (e1 << 30));
    const uint32_t o1 = (b1) ^ ((e1 >> 1) | (e2 << 31)) ^ ((e1 >> 2) | (e2 << 30));
    const uint32_t o2 = ((b2)) & 1u;
    const uint32_t te0 = (e0) ^ ((e0 << 1)) ^ ((o0 << 2));
    const uint32_t te1 = (e1) ^ ((e0 >> 31) | (e1 << 1)) ^ ((o0 >> 30) | (o1 << 2));
    const uint32_t te2 = ((e2) ^ ((e1 >> 31) | (e2 << 1)) ^ ((o1 >> 30) | (o2 << 2))) & 3u;
    const uint32_t to0 = (o0) ^ ((o0 << 1)) ^ ((e0 << 1));
    const uint32_t to1 = (o1) ^ ((o0 >> 31) | (o1 << 1)) ^ ((e0 >> 31) | (e1 << 1));
    const uint32_t to2 = ((o2) ^ ((o1 >> 31) | (o2 << 1)) ^ ((e1 >> 31) | (e2 << 1))) & 1u;
    const uint32_t ev0 = a.v[0] ^ (te0);
    const uint32_t ev1 = a.v[1] ^ (te1) ^ (te0) ^ ((te0 << 16)) ^ ((te0 << 24)) ^ ((te0 << 28)) ^ ((e0 << 30));
    const uint32_t ev2 = (a.v[2] ^ (te2) ^ (te1) ^ ((te0 >> 16) | (te1 << 16)) ^ ((te0 >> 8) | (te1 << 24)) ^ ((te0 >> 4) | (te1 << 28)) ^ (te0) ^ ((e0 >> 2) | (e1 << 30))) & 3u;
    const uint32_t od0 = (to0);
    const uint32_t od1 = (to1) ^ (to0) ^ ((to0 << 16)) ^ ((to0 << 24)) ^ ((to0 << 28)) ^ ((o0 << 30));
    const uint32_t od2 = ((to2) ^ (to1) ^ ((to0 >> 16) | (to1 << 16)) ^ ((to0 >> 8) | (to1 << 24)) ^ ((to0 >> 4) | (to1 << 28)) ^ (to0) ^ ((o0 >> 2) | (o1 << 30))) & 1u;
    P131 out;
    goal22Zip2(ev0, od0, &out.v[0], &out.v[1]);
    goal22Zip2(ev1, od1, &out.v[2], &out.v[3]);
    out.v[4] = (ev2 & 1u) | ((od2 & 1u) << 1) | ((ev2 & 2u) << 1);
    return out;
}
